In [1]:
import pandas as pd
import numpy as np
import string
import re

from rapidfuzz import process, fuzz, distance


pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
cols_to_use = ['filer_committee_id_number',
                    'form_type',
                    'payee_organization_name',
                    'payee_last_name',
                    'payee_first_name',
                    'expenditure_date',
                    'expenditure_amount',
                    'expenditure_purpose_descrip',
                    'beneficiary_candidate_last_name',
                    'beneficiary_candidate_first_name',
                    'memo_code',
                    'memo_text_description']

# Load data 
sb_data = pd.read_csv('../data/raw/SB_dataset.csv', usecols = cols_to_use)

/var/folders/cl/bdrh3m8j0fdfj6zm7zhhc2ch0000gn/T/ipykernel_76724/1335903702.py:15: DtypeWarning: Columns (7,8,20,27,28,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  sb_data = pd.read_csv('../data/raw/SB_dataset.csv', usecols = cols_to_use)

## Process SB Data

We start by dropping any rows with missing filer committee ID numbers and any rows in which the filer committee ID number does not match the C####### pattern we expect

In [3]:
# drop rows where filer_committee_id_number is null
sb_data = sb_data.dropna(subset=['filer_committee_id_number'])

# drop rows without a properly formated committee id
pattern = r'^C\d{8}$'
sb_data = sb_data[sb_data['filer_committee_id_number'].str.contains(pattern, na=False)]


### Form Types
Form types code each expenditure into categories defined by the FEC. All form types in the SB (schedule B - expenditure) data should begin with the letters SB. 

Looking at the data there is 1 observation where this is not the case. It is associated with payments to ActBlue for credit card processing expenses. Given the small sample, I will update the form type to reflect SB21.  

SB17 isn't a disbursement lineitem associated with PAC filings. There is one observation with this coding from the 2023 Year End filing (1761077) from the Ryman Hospitality Properties Political Action Committee (C00183707). I'm going to reassign this to SB23, as it is described as a campaign contribution.

SB27 isn't a disbursement lineitem associated with PAC filings. I'm going to reassign this to SB29, as it is described as a mistaken loan.

| Form Type       | Description         |
|-----------------|---------------------|
| SB21            | Operating Expenditures |
| SB21B           | Other Operating Expenditures |
| SB22            | Transfers to Affiliated  Other Party Committees |
| SB23            | Contributions to Fed. Candidates Committees and other political committees |
| SB26            | Loan repayments made |
| SB28A           | Refunds to Individuals |
| SB28B           | Refunds to Party Committees |
| SB28C           | Refunds to Other Committees |
| SB29            | Other Disbursements |
| SB30B           | Federal Election Activity |

In [4]:
# Recode obviously miscodded form types
sb_data.loc[sb_data['form_type'] == 'SB17', 'form_type'] = 'SB23'
sb_data.loc[sb_data['form_type'] == '1b', 'form_type'] = 'SB21B'
sb_data.loc[sb_data['form_type'].isin(['27','SB27']), 'form_type'] = 'SB29'

# Capitalize form_type to standardize SB21b SB21B etc
sb_data['form_type'] = sb_data['form_type'].str.upper()

In [5]:
# Create form_type_desc column to help me remember what i'm looking at 
form_type_map = {
    'SB21' : 'Operating Expenditures',
    'SB21B' : 'Other Operating Expenditures',
    'SB22' : 'Transfers to Affiliated Committees',
    'SB23' : 'Contributions to Candidates and Committees', 
    'SB26' : 'Loan repayments made',
    'SB28A' : 'Refunds to Individuals',
    'SB28B' : 'Refunds to Party Committees',
    'SB28C' : 'Refunds to Other Committees',
    'SB29' : 'Other Disbursements',
    'SB30B': 'Federal Election Activity',
}

sb_data['form_type_desc'] = sb_data['form_type'].map(form_type_map)

In [6]:
sb_data.form_type_desc.value_counts()

form_type_desc
Contributions to Candidates and Committees    580591
Other Operating Expenditures                  417375
Other Disbursements                           152392
Refunds to Individuals                        116754
Transfers to Affiliated Committees             15473
Refunds to Other Committees                      335
Loan repayments made                             150
Federal Election Activity                        147
Refunds to Party Committees                       68
Operating Expenditures                            19
Name: count, dtype: int64

For the purpose of this work, we are not interested in refunds so we'd like to drop all refund rows. First we must check to make sure there isnt evidence of large scale mis categorization of expenses as refunds.

In [7]:
# Check to make sure everything in refunds categories contain refund (or seomthing related) as purpose descrips
print("Refunds:")
sb_data[(sb_data['form_type'].isin(['SB28A','SB28B''SB28C'])) & 
        ~sb_data['expenditure_purpose_descrip'].str.contains('REFUND|VOID|REIMBURSE|ERRO|RETURN', na = False, case = False) ].expenditure_purpose_descrip.unique().tolist()

Refunds:

[nan,
 'Duplicate PayPal Transaction',
 'SEE MEMO ATTACHED',
 'Reissue of 12/13/2022 check',
 'Contribution to Committee',
 'Contribution Ref to Corporation',
 'Contribution Ref to Individual',
 'See Line 28a - US Travel Association',
 'GiveSmart',
 'Mark C Mckean ran card by mistake',
 'Contribution Rerfund',
 'Dispute Reversed',
 'Original contribution 3/3/24',
 'Earmarked through ACTBlue',
 'See Line 28 - US Travel Association',
 'See Line 28, U.S. Travel Association',
 'Chargeback',
 'Donor made Chargeback',
 'Member accidently put $1.00 to the PAC fund.  Member corrected PAC contribution to 0.05 cents.',
 'Adjustment to Payroll Deduction',
 'ANTONIA SACCHETTI',
 'Disputed contribution, originally received 4/21/23',
 'Fundraising Consulting Fee',
 'Legal Fees',
 'PARKING SERVICES',
 'Mistaken contribution',
 'Donor incorrectly selected monthly recurring payment.',
 'Meeting venue',
 'Print cards for Holiday Party',
 'Flowers for retiring Club President',
 'Repay Contribution Made on 02/14/24',
 'Chargeback dated 4/4/23',
 'Chargeback dated 4/7/23',
 'CHARGE BACK OF CONTRIBUTION DATED  11.7.2022',
 'Closed PAC Account',
 "DISGORGEMENT OF MOYLE'S CENTRAL VALLEY HEALTH DONATION",
 'Duplicate contribution',
 'Payroll Correction',
 'Contribution',
 'Contribution exceeded maximum allowed',
 'Facebook Ad',
 'No new check issued. Reconciling $500 check contribution reported 11/21/24 that did not clear bank.',
 '2023Contribution',
 'credit given to incorrect individual',
 'Wrong Amount',
 'credit_not_processed chargeback',
 'Mistake Express Lane',
 'Earmarked through ActBlue',
 'See Line 29 - US Travel Association',
 'requested',
 'CHARGEBACK',
 'See Line 28 US Travel Association',
 'See report memo for details',
 'Other',
 'Reund for contribution on 2/2/2024',
 'Duplicate Contribution',
 'Excess Contribution',
 'Account balance for loan repayment - remainder forgiven']

In [8]:
# filter out refunds 
spending_data = sb_data[~sb_data['form_type_desc'].str.contains('Refund', na=False)].copy()

In [9]:
spending_data.form_type_desc.value_counts()

form_type_desc
Contributions to Candidates and Committees    580591
Other Operating Expenditures                  417375
Other Disbursements                           152392
Transfers to Affiliated Committees             15473
Loan repayments made                             150
Federal Election Activity                        147
Operating Expenditures                            19
Name: count, dtype: int64

In [10]:
# A lot of the other operating expenditures are contributions to committees. I want to recategorize those to contributions to committees because I'll try to clean those differently 

cont_cmte_pattern = 'FOR (?:CONGRESS|SENATE|STATE|ASSEMB|GOV|ALABAMA|\bAL\b|ALASKA|\bAK\b|ARIZONA|\bAZ\b|ARKANSAS|\bAR\b|CALIFORNIA|\bCA\b|COLORADO|\bCO\b|CONNECTICUT|\bCT\b|DELAWARE|\bDE\b|FLORIDA|\bFL\b|GEORGIA|\bGA\b|HAWAII|\bHI\b|IDAHO|\bID\b|ILLINOIS|\bIL\b|INDIANA|\bIN\b|IOWA|\bIA\b|KANSAS|\bKS\b|KENTUCKY|\bKY\b|LOUISIANA|\bLA\b|MAINE|\bME\b|MARYLAND|\bMD\b|MASSACHUSETTS|\bMA\b|MICHIGAN|\bMI\b|MINNESOTA|\bMN\b|MISSISSIPPI|\bMS\b|MISSOURI|\bMO\b|MONTANA|\bMT\b|NEBRASKA|\bNE\b|NEVADA|\bNV\b|NEW HAMPSHIRE|\bNH\b|NEW JERSEY|\bNJ\b|NEW MEXICO|\bNM\b|NEW YORK|\bNY\b|NORTH CAROLINA|\bNC\b|NORTH DAKOTA|\bND\b|OHIO|\bOH\b|OKLAHOMA|\bOK\b|OREGON|\bOR\b|PENNSYLVANIA|\bPA\b|RHODE ISLAND|\bRI\b|SOUTH CAROLINA|\bSC\b|SOUTH DAKOTA|\bSD\b|TENNESSEE|\bTN\b|TEXAS|\bTX\b|UTAH|\bUT\b|VERMONT|\bVT\b|VIRGINIA|\bVA\b|WASHINGTON|\bWA\b|WEST VIRGINIA|\bWV\b|WISCONSIN|\bWI\b|WYOMING|\bWY\b)|ELECT\b|FRIENDS OF|\bPAC\b?|\bCOMMITTEE\b?|\bCMTE\b|\bVICTORY\b|\bFUND\b?'

recat_payee_org_name = spending_data[(spending_data['form_type_desc'].isin(['Other Operating Expenditures','Other Disbursements'])) & (spending_data['payee_organization_name'].str.contains(pat = cont_cmte_pattern, regex = True, case = False) ) ].payee_organization_name.unique()

# Check to make sure this is working like I think it should
recat_payee_org_name

array(['Friends of Kim Ward', 'LISA MCCLAIN FOR CONGRESS',
       'Amy Walen for State House', ..., 'Chas Cannon for State House',
       'Meeks for Georgia', 'Cmte to Elect Patty Stinson for State House'],
      dtype=object)

In [11]:
# Recode the form_type 
spending_data['form_type'] = np.where(
                                (spending_data['payee_organization_name'].isin(recat_payee_org_name)) & (spending_data['form_type_desc']=='Other Operating Expenditures'),
                                'SB23',
                                spending_data['form_type']
)

# Recode the form_type_desc
spending_data['form_type_desc'] = np.where(
                                (spending_data['payee_organization_name'].isin(recat_payee_org_name)) & (spending_data['form_type_desc']=='Other Operating Expenditures'),
                                'Contributions to Candidates and Committees',
                                spending_data['form_type_desc']
)

spending_data.form_type_desc.value_counts()

form_type_desc
Contributions to Candidates and Committees    581186
Other Operating Expenditures                  416780
Other Disbursements                           152392
Transfers to Affiliated Committees             15473
Loan repayments made                             150
Federal Election Activity                        147
Operating Expenditures                            19
Name: count, dtype: int64

In [12]:
# Define numeric columns as numeric
spending_data['expenditure_amount'] = pd.to_numeric(spending_data['expenditure_amount'])

In [13]:
# Normalize all string data 

def normalize_string_columns(df):
    """
    Function to normalize all string columns to uppercase, remove punctuation, strip whitespace 
    """
    for col in df.columns:
        # If the column is an object
        if df[col].dtype == 'object':
           df[col] = (
           df[col]
           # remove punctuation
           .str.replace(f"[{string.punctuation}]", " ", regex=True)
           # remove trailing whitespace and multiple spaces
           .str.replace(r"\s+"," ", regex = True)
           # remove common suffixes
           .str.replace(r'\b(LLC|INC|LTD|LLP|PLCC|PLC|PC|STRATEGIES|SERVICES|ASSOCIATES|CONSULTING|GROUP|CORPORATION|COM|ORG|PAC|PARTNERS|ASSOCIATION|NET|CONTRIBUTIONS)\b$', '', regex=True, case=False)
           # remove numbers by themselves ie 1223 but not 1223abc
           .str.replace(r'\b\d+\b\.?', '', regex=True, case=False)
           # remove whitespaces again
           .str.strip()
           # capitalize everything
           .str.upper()
           )
    return df

# Apply to our DF
spending_data = normalize_string_columns(spending_data)

In [14]:
## columns are filled out depending on the payee type - an organization, individual, or candidate, I want one column that concatenates all of this information

# Build component strings safely, ensuring no NaN text appears
spending_data['payee_name'] = (
    spending_data['payee_last_name'].fillna('') + ' ' +
    spending_data['payee_first_name'].fillna('')
    # removed city because we were grouping all of the payees from the same city together 
).str.strip()

spending_data['beneficiary_cand_name'] = (
    spending_data['beneficiary_candidate_first_name'].fillna('') + ' ' +
    spending_data['beneficiary_candidate_last_name'].fillna('')
).str.strip()

# Select the first non-null (and non-empty) among the three
spending_data['payee_id'] = (
    spending_data[['payee_organization_name', 'payee_name', 'beneficiary_cand_name']]
    .replace('', pd.NA)         
    .bfill(axis=1)              
    .iloc[:, 0]                 
)

n_original_payees = len(spending_data['payee_id'].unique())

In [15]:
# drop rows where payee_id is null 
spending_data.dropna(subset='payee_id', inplace=True)
spending_data.isna().sum()

form_type                                 0
filer_committee_id_number                 0
payee_organization_name               68124
payee_last_name                     1097884
payee_first_name                    1097887
expenditure_date                          0
expenditure_amount                        0
expenditure_purpose_descrip           40562
beneficiary_candidate_last_name      793925
beneficiary_candidate_first_name     794095
memo_code                            811658
memo_text_description                850078
form_type_desc                            0
payee_name                                0
beneficiary_cand_name                     0
payee_id                                  0
dtype: int64

In [16]:
# Replace state abbreviations in strings with state names to futher standardize texts
# EX. TEXAS DEMOCRATIC PARTY -> TX DEMOCRATIC PARTY
state_map = {
    'ALABAMA': 'AL',
    'ALASKA': 'AK',
    'ARIZONA': 'AZ',
    'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA',
    'COLORADO': 'CO',
    'CONNECTICUT': 'CT',
    'DELAWARE': 'DE',
    'FLORIDA': 'FL',
    'GEORGIA': 'GA',
    'HAWAII': 'HI',
    'IDAHO': 'ID',
    'ILLINOIS': 'IL',
    'INDIANA': 'IN',
    'IOWA': 'IA',
    'KANSAS': 'KS',
    'KENTUCKY': 'KY',
    'LOUISIANA': 'LA',
    'MAINE': 'ME',
    'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA',
    'MICHIGAN': 'MI',
    'MINNESOTA': 'MN',
    'MISSISSIPPI': 'MS',
    'MISSOURI': 'MO',
    'MONTANA': 'MT',
    'NEBRASKA': 'NE',
    'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH',
    'NEW JERSEY': 'NJ',
    'NEW MEXICO': 'NM',
    'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC',
    'NORTH DAKOTA': 'ND',
    'OHIO': 'OH',
    'OKLAHOMA': 'OK',
    'OREGON': 'OR',
    'PENNSYLVANIA': 'PA',
    'RHODE ISLAND': 'RI',
    'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN',
    'TEXAS': 'TX',
    'UTAH': 'UT',
    'VERMONT': 'VT',
    'VIRGINIA': 'VA',
    'WASHINGTON': 'WA',
    'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI',
    'WYOMING': 'WY'
}


pattern = r'\b(' + '|'.join(state_map.keys()) + r')\b'

def replace_state_abbrev(string_):
    """
    Use state_map to replace all state names with state abbrev
    to further normalize strings
    """
    return re.sub(pattern,
                  lambda x: state_map[x.group(0)],
                  string_)

# Apply replace state abbrev to payee_id 
spending_data['payee_id'] =  spending_data['payee_id'].apply(replace_state_abbrev)

In [17]:
# Retry the suffix stripping in cases where there may have been multiple 
spending_data['payee_id'] = spending_data['payee_id'].str.replace(r'\s*(INC|CPA|COMPANY|CO|N A|LLC|P C)\s*$','',regex = True, case = False)

spending_data[spending_data['form_type']=='SB21B'].payee_id.unique().tolist()

['KEVIN L BOYCE COMMITTEE',
 'CFS COMPLIANCE',
 'THE TOWNSEND',
 'TRUIST',
 'COMERICA BANK',
 'BIPARTISAN CLIMATE ACTION',
 'JPMORGAN CHASE BANK',
 'SQUARESPACE',
 'ARISTOTLE INTERNATIONAL',
 'FACEBOOK',
 'GOOGLE',
 'HAWATMEH NICK',
 'PROFESSIONAL DATA',
 'ACTBLUE',
 'AMALGAMATED BANK',
 'KESWICK HALL',
 'TIBER CREEK',
 'AMERICAN EXPRESS',
 'LYFT RIDE',
 'UBER',
 'HYATT REGENCY ORLANDO',
 'MARCO PROMOTIONAL PRODUCTS',
 'JOSELITO CASA',
 'CUSTOM INK',
 'L ARDENTE',
 'UNITED AIRLINES',
 'AMERICAN AIRLINES',
 'MLT STRATEGIC FUNDRAISING',
 'PENDRY MANHATTAN',
 'AMTRAK',
 'HOTEL SAN FRANCIS',
 'ALL ABOUT PARKINSAN',
 'DONNELL PAYNE',
 'BROWNS CAB',
 'FARAWAY NANTUCKET',
 'HILTON GARDEN INN',
 'NGP VAN',
 'TOTAL WINE MORE',
 'AT ANY TABLE',
 'SAVOYA',
 'PURPURA SALVATORE',
 'HUCKABY DAVIS LISKER',
 'WINRED',
 'NASW',
 'LIEB SARAH',
 'CREST STRATEGIES',
 'WELLS FARGO',
 'THE MONEY WHEEL',
 'EVERYACTION',
 'AMALGAMATED',
 'VICTORY FORWARD SOLUTIONS',
 'THE COLIBRI COLLECTIVE',
 'CHAIN BRIDGE BANK',
 'ACTBLUE TECHNICAL',
 'NEXT LEVEL PARTNERS',
 'SABATO',
 'TRACY AUSTIN',
 'CROSBY OTTENHOFF',
 'DEMOCRACY ENGINE',
 'INTRUST BANK',
 'STRIPE',
 'ANEDOT',
 'T2V',
 'VA CONSULTING GROUP',
 'ADP',
 'CITIZENS BANK',
 'TABAIE MARY',
 'HONEYLEAF PLATTERS',
 'NGPVAN',
 'PAYCHEX',
 'PCMS',
 'CM',
 'DRUCKER LAWHON',
 'HOLTZMAN VOGEL P',
 'RODNEY TREGEMBO SW PARKING',
 'SOCKO STRATEGIES',
 'TARGETED VICTORY',
 'TWITTER',
 'WORD PRESS',
 'USPS',
 'GA SECRETARY OF STATE',
 'ARISTOTLE',
 'WINRED TECHNICAL SERVICES',
 'BOLD COLORS GROUP',
 'CONCEPT',
 'ELECTIONS',
 'IMPACT STRATEGIES',
 'PROFESSIONAL DATA SERVICES',
 'ZEALOUS',
 'ROBERT WATKINS COMPANY P A',
 'CONSTANT CONTACT',
 'CMDI',
 'ROLLINS EDWARD',
 'DELANO JOSHUA',
 'LEFF CAROLYN',
 'ZENICA',
 'KGLOBAL',
 'BEST GUEST MEDIA',
 'THE RAINMAKERS ORGANIZATION',
 'IMPACT SOCIAL',
 'AMERICAN CAGING',
 'CAMPAIGN SOLUTIONS',
 'EDONATION',
 'I3VERTICALS',
 'PAC MANAGEMENT SERVICES',
 'POSTAGE FOR DIRECT MAIL FUNDRAISING',
 'RODRIGUEZ BAZ LILIAN',
 'ELAVON',
 'AXCAPITAL',
 'LINEMARK',
 'OK STATE SOCIETY',
 'NORTHERN TRUST',
 'CAPITOL COMPLIANCE ASSOCIATES',
 'WHEELS UP CONSULTING',
 'FACEBOOK ADVERTISING USA',
 'TATANGO',
 'ANNE LEWIS STRATEGIES',
 'DATA FARM',
 'HELIX CAMPAIGNS',
 'PREMIER POLITICAL COMPLIANCE',
 'SWITCHBOARD PUBLIC BENEFIT CORP',
 'CAPITAL ONE BANK',
 'THE CONGRESSIONAL CLUB MUSEUM AND FOUNDATION',
 'NORTH PHILADELPHIA LEAGUE OF VOTERS',
 'DEMAND ELECTIONS',
 'CITIBANK',
 'THE BROADMOOR',
 'WIN RED TECHNICAL',
 'HOLTZMAN VOGEL JOSEFIAK TORCHINSKY P',
 'CFO COMPLIANCE',
 'BOYLAN EMERY',
 'GUSTO',
 'INTEGRATED SOLUTIONS POLITICAL',
 'KRON',
 'MAI ASSOCIATES',
 'OLD FRIENDS PIZZA',
 'SAMSAR',
 'THE CW',
 'CONSULTING',
 'ELECTION CFO',
 'APOLLO ARTISTRY',
 'INTUIT',
 'MOTHERSHIP',
 'MY WARCHEST',
 'MASTERCARD TCM BANK',
 'STRIPE PAYMENTS',
 'BB T',
 'SFOGLINA',
 'US SENATE GIFT SHOP',
 'THE MORNING',
 'WINCO FUNDRAISING',
 'BISON',
 'CLARITY CAMPAIGN LABS',
 'COVINGTON BURLING',
 'SCHOEN SURVEY RESEARCH',
 'NIELSEN MERKSAMER PARRINELLO GROSS LEONI',
 'SAME DAY PROCESSING',
 'ZERO TO ONE VENTURES',
 'KOCH HOOS',
 'DEANE',
 'T L PROPERTIES',
 'TRUIST VISA',
 'HOTEL RENOVO',
 'DOT THE I DESIGN AND GRAPHICS',
 'PRECISION MARKETING',
 'RIGHTSIDE COMPLIANCE',
 'VENABLE',
 'AMAZON',
 'AUDACY OPERATIONS',
 'SCALE TO WIN',
 'SNAP',
 'SUMMITMEDIA',
 'TIDEWATER COMMUNICATIONS',
 'VA MEDIA',
 'WORLDPAY',
 'BANK OF AMERICA',
 'WELLS FARGO BANK',
 'ALIISA LEE DESIGN AND COMMUNICATIONS',
 'CAPITOL ADVANTAGE',
 'FEDERAL EXPRESS',
 'FEDEX OFFICE',
 'K L GATES',
 'SANTANDER BANK',
 'UNITED STATES POSTAL SERVICE',
 'VISTA PRINT',
 'CLUB FOR GROWTH',
 'SUTTON JOSEPH',
 'REICHERT LOGAN',
 'COMPLIANCE CONSULTING CO OF VA',
 'MGM RESORTS INTERNATIONAL',
 'SOLUTIONS FOR FUNDRAISING IN TX',
 'TAG',
 'TONY S CATERING',
 'EARL DAVID',
 'THE LS GROUP',
 'ASSOCIATED BANK',
 'CAPITOL TECH SOLUTIONS',
 'CAMPAIGN COMPLIANCE',
 'CONSOLIDATED MAILING',
 'D D UNLIMITED',
 'DONOR BUREAU',
 'FIRST VA COMMUNITY BANK',
 'MADERA ESCROW',
 'TRANSFIRST',
 'FEDEX',
 'GUIDRY MALOY GROUP',
 'KATZ COMPLIANCE',
 'PEOPLE FOR BIKES COALITION LTD POLITICAL ACTION COMMITTEE DBA BIKESPAC',
 'COMCAST',
 'ZOOM',
 'BALONICK MARCIA',
 'BEAL PROPERTIES',
 'BLANCO JOSE',
 'COMMONWEALTH EDISON',
 'IL DEPT OF REVENUE',
 'INTERNAL REVENUE SERVICE',
 'JUST CAUSE',
 'NORTH SHORE GAS',
 'SCHOENBERG DANIELLE',
 'SHAEWITZ ALLISON',
 'WEIN HOLLIS',
 'WILGUS MIRANDA',
 'YOUNG DENISE',
 'ELECTION CFO II',
 'PAYA',
 'PAYPAL',
 'CONNECTED',
 'ELEVATED LIVING',
 'FII MARKETING',
 'GHOST NOTE MEDIA',
 'INTERCONTINENTAL CHICAGO',
 'ONE DEF',
 'ONE HILL SOUTH',
 'SANDERS J',
 'SANDLER REIFF LAMB ROSENSTEIN BIRKENSTOCK',
 'SOUTHWEST AIRLINES',
 'THE CARAWAY GROUP',
 'THOMAS THYME',
 'WEGMANS',
 'ZAZZLE',
 'ADDISON',
 'BILL',
 'NATIONAL DEMOCRATIC CLUB',
 'BRILLIANT CORNERS RESEARCH',
 'BUFFER PRO SYSTEMS',
 'ELIAS LAW',
 'FIRST BANKCARD',
 'APPLE',
 'BOLSER REBEKAH',
 'CHARLIE PALMER STEAKHOUSE',
 'DELTA AIRLINES',
 'DOORDASH INC POLITICAL ACTION COMMITTEE DASH PAC',
 'JW MARRIOTT HOTELS',
 'MFABI',
 'NEW ORLEANS JAZZ HERITAGE MUSEUM',
 'RSVP CATERING',
 'SHOPIFY',
 'TEN EIGHTY',
 'THE RITZ CARLTON HOTEL',
 'UBER TECHNOLOGIES',
 'FROBENIUS CONAWAY',
 'LIFTOFF CAMPAIGNS',
 'TAYLOR CHRISTOPHER',
 'WALL STREET JOURNAL',
 'YOUR WAY IT SOLUTIONS',
 'ZOOM VIDEO COMMUNICATIONS',
 'CAPITOL HILL CLUB',
 'WHITEMAN TODD',
 'SUNTRUST BANK',
 'THE FROST',
 'CHASE CARD',
 'MBA CONSULTING',
 'SONOMA RESTAURANT AND WINE BAR',
 'KMA',
 'NOBLE BANK',
 'PARAGON',
 'AISLE',
 'CAPITAL HILL WINE SPIRITS',
 'DROPBOX',
 'NETROOTS NATION',
 'SCHNEIDER S LIQUOR',
 'W MILLAR CO CATERING',
 'BROWN EVAN',
 'DATA FOR PROGRESS',
 'DC HEALTH LINK',
 'FIDELITY INVESTMENTS INSTITUTIONAL OPERATIONS',
 'BAILEY ERNEST',
 'DARNER MICHAEL',
 'HINES GILLIAN',
 'KIELOCH',
 'LEXISNEXIS',
 'OLSON REMCHO',
 'SITEGROUND',
 'TABULARIUS',
 'WPAI',
 'ANHEUSER BUSCH COMPANIES',
 'OORBEEK MEMMOTT',
 'BEAVER LEGAL CORPRATION',
 'RESILIENT',
 'AIR BNB',
 'ALAMO REBTAL CAR',
 'ALAMO RENTAL CAR',
 'AMTRAV DELTA',
 'CAPITAL ONE TRAVEL',
 'COMFORT SUITES HOTELATLANTA GA',
 'DOLLAR RENTAL CAR',
 'ENTERPRISE',
 'HOME2 SUITES',
 'HYATT HOUSE',
 'JANICE LUO',
 'AMTRAV',
 'DAVID SHOR',
 'DAVIS SHOR',
 'DOLLAR RENT A CAR',
 'EXPEDIA',
 'LYFT',
 'MASSIMO LAMBERT MULLEN',
 'RESIDENCE INN BY MARDULUTH GA',
 'SIXT CAR RENTAL',
 'COSTCO AVIS RENTAL CAR',
 'SONESTA SELECT ATLANTA MIDTOWN GA TECH',
 'ANDREW SCHNEIDER',
 'AVIS CAR RENTAL',
 'AVIS RENTAL',
 'AVIS',
 'BUDGET',
 'DEION ROBERTSON',
 'DYLAN COOKE',
 'GRAND SIERRA RESORT AND CASINO',
 'LAGUARDIA AIRPORT PARKING',
 'SEBASTIAN CURIEL COTA',
 'SONESTA ES SUITES SCSCOTTSDALE AZ',
 'SONESTA GWINNETT PLACE ATLANTA',
 'THRIFTY CAR RENTAL',
 'ALLIANCE GRAPHICS',
 'CLICK   CONSULTING',
 'CORY MICHAEL FONG',
 'GREGORY CLUSTER',
 'MICAH BAZANT',
 'MOLLY J MCCLURE',
 'MOLLY MCCLURE',
 'QUALTRICS',
 'THE SUBURBIA JONATHAN SPENCE',
 'WEPAY',
 'BENDER DAVE',
 'BRINKLEY CLAIRE',
 'WALLACE KYLE',
 'NIEVES NELSON',
 'WINTERS BRIAN',
 'ZIMMERMAN DAN',
 'MARTIN S EVENT CENTER',
 'Q  ENTERTAINMENT',
 'ACCESS PARTY RENTALS',
 'SHERIFF ANTHONY',
 'HOLLYWOOD ELITE SECURITY',
 'CA BANK TRUST',
 'KIMPTON AERTSON HOTEL',
 'JW MARRIOTT',
 'TRUIST BANK',
 'HELLOFRESH',
 'ENTERPRISE RENT A CAR',
 'LAKE LBJ BOUTIQUE RESORT',
 'ESCONDIDO CLUB',
 'FUNDRAISING',
 'OMNI SHOREHAM HOTEL',
 'CAPITAL HOUSE CONSULTING',
 'IGNITE STRATEGIES',
 'GRANT JENNIFER',
 'JEWISH COMMUNITY CENTER',
 'NGP',
 'TX SOUTHWESTERN CATTLE RAISERS',
 'VANTAGE LEGAL',
 'CAPITOL COMPLIANCE',
 'BLUEFOOT POLITICAL',
 'PACTION DATA',
 'CAPLIN DRYSDALE',
 'MCTIGUE COLOMBO',
 'TIGEREYE PROMOTIONS',
 'PNC BANK',
 'K F  PARTNERS',
 'WPA INTELLIGENCE',
 'CATHY SCOTT AND',
 'MOBLYZE',
 'BESPEAK NETWORK',
 'PROJECT ALAMO',
 'S E OWENS',
 'UNITED STATES LIABILITY INSURANCE',
 'COMPLIANCE CONSULTING',
 'ACT BLUE',
 'FINANCIAL INNOVATIONS',
 'AT T',
 'ADOBE',
 'ANIMOTO',
 'BUFFER',
 'CONSERVATIVE PARTNER INSTITUTE',
 'TYPEFORM',
 'VERIZON WIRELESS',
 'BANKCARD USA',
 'MONMOUTH',
 'NORTH AMERICAN FULFILLMENT',
 'RESIDENTIAL PROGRAMS',
 'WINPISINGER ASSOCIATES',
 'FISCALNOTE',
 'ST STRATEGIES',
 'SUNTRUST',
 'SHQ',
 'U S POSTAL SERVICE',
 'TAYLOR MAMIE',
 'RICHARDSON MICHELLE',
 'BRADLEY PATRICK GROUP',
 'WATERCOLOR INN RESORT',
 'FMM CONSULTING GROUP',
 'GEORGE S AT ALLYS BEACH',
 'PUBLIX',
 'WINE BAR',
 'CAFE THIRTY A',
 'NATIONAL CAR RENTAL',
 'BARCLAYS',
 'THE POINT',
 'NEW CONGRESSIONAL LIQUOR DELI',
 'CAPITAL GRILLE',
 'TUNE INN',
 'SICHUAN PAVILION',
 'SQUARE CAPITAL',
 'DCAN PRODUCTIONS',
 'LAUKIEN FRANK',
 'OPINION DIAGNOSTICS',
 'PAC MANAGEMENT',
 'BELL JACKSON',
 'BLANK ROME',
 'BULLDOG COMPLIANCE',
 'CLANCY COMMUNICATIONS',
 'DAVIDSON GROUP',
 'EDGE MEDIA',
 'KNUPP DAVID',
 'MARINE LANE',
 'HART RESEARCH',
 'RAMP',
 'SILICON VALLEY BANK',
 'WELLS FARGO BANK NA',
 'ARISTEIA GROUP',
 'DLA PIPER US',
 'LEVY RATNER',
 'CORCORAN CATERERS',
 'GREAT TURTLE BREWERY',
 'LGM CONSULTING GROUP',
 'MARI VINEYARDS',
 'RUSHORDER',
 'ABRUZZO NANCY',
 'RHOADES MARGARET',
 'KIRSTIN HOPKINS',
 'SCR AND',
 'SHANNA WOODBURY CONSULTING',
 'BROWN WINNICK LAW',
 'FAILOR ED',
 'MCM LAW',
 'OBJECTIVE MEDIA',
 'AUSTIN DAVID',
 'BLUEUTOPIA',
 'THE COOK POLITICAL REPORT',
 'RAISE MORE',
 'EMAIL ON ACID',
 'CIVIC SHOUT',
 'CIVITECH',
 'FRAISER',
 'L2 DATA',
 'QUILLER',
 'SWITCHBOARD',
 'VICTORY FIRST',
 'WILDFLOWER',
 'GRAND VALLEY',
 'DREAM CHARTER SCHOOL',
 'GENOVA BURNS',
 'CAMPAIGN TECHNOLOGY PROFESSIONALS',
 'FIRST DATA',
 'MEMBERS DINING ROOM',
 'SALT CAFE',
 'HYATT HOTELS',
 'UBER EATS',
 'LOT  ESPRESSO',
 'RPM ITALIAN RESTAURANT',
 'SROA',
 'UNITED STEELWORKERS',
 'AUTHORIZE',
 'CITY NATIONAL BANK',
 'ELAVON MERCHANT',
 'ACTION NETWORK',
 'VIEW AVENUE',
 'WP ENGINE',
 'MANDALAY HOTEL',
 'DEVELOPWELL',
 'DOUBLETREE HOTEL',
 'PROFORMA',
 'SFO PARKING CENTER',
 'LERNER SYLVIE',
 'MWAMLIMIA SARA',
 'PFLUEGER ANNALISE',
 'POWELL KIERRA',
 'ROYBAL ISEZ',
 'CEP TOWN COUNTRY',
 'HOTEL PALOMAR',
 'GSUITE',
 'HILTON INTERNATIONAL HOTEL',
 'LURIE',
 'MASON STACY',
 'TAKECOMMAND',
 'SLACK',
 'COOK POLITICAL REPORT',
 'FRONTIER',
 'THOMAS OF WRIGHT',
 'UPPER CANAL',
 'AL ADVISING',
 'ALAMO',
 'PANTHEON SYSTEMS',
 'BROWN PALACE HOTEL',
 'THE DUPONT HOTEL',
 'MOMENTOUS INSURANCE BROKERAGE',
 'HERTZ',
 'HARVEY MEGHAN',
 'LAW OFFICES OF KATHERINE S CLARK',
 'HIGH BRIDGE CONSULTING',
 'PARAGON PAYMENT SOLUTIONS',
 'CHAINBRIDGE ALTRIA OPERATING',
 'HSBC BANK',
 'SUMMIT CAMPAIGN',
 'UTRECHT KLEINFELD FIORI CLARK',
 'PLUS  STRATEGIES',
 'BLUE WAVE POLITICAL PARTNERS',
 'BOYSENBERRY STRATEGIES',
 'CIVIS ANALYTICS',
 'EVERYTOWN FOR GUN SAFETY ACTION FUND',
 'GELLER',
 'GROSSMAN MARKETING',
 'PARAGON SOLUTION',
 'TRAIL BLAZER CAMPAIGN SERVICES',
 'NCMIC FINANCE',
 'MASTERCARD',
 'MARRIOTT WEST PALM BEACH',
 'U S BANK',
 'REVV',
 'AMERICA RISING',
 'BLACK ROCK GROUP',
 'CAVALRY',
 'DRIVER EIGHT MEDIA',
 'RED OAK STRATEGIC',
 'ALLIED TELECOM',
 'ATLANTIC SERVICES GROUP',
 'CAMPAIGNMONITOR',
 'CAPITOL COMPUTER EXCHANGE',
 'DATAWATCH SYSTEMS',
 'MICROSOFT',
 'NATIONAL JOURNAL GROUP',
 'NAUTICON OFFICE SOLUTIONS',
 'NY TIMES',
 'CROSBY OTTENHOFF GROUP',
 'BEYERSDORFER ANNE',
 'ATMOSPHERE DIGITAL',
 'INTEGRATED CAMPAIGN SOLUTIONS',
 'ONE NATION',
 'FAY JENNIFER',
 'SINCLAIR TORUNN',
 'CFC CONSULTING',
 'CONNEX INTERNATIONAL',
 'CONFERENCE AMERICA',
 'GUERNSEY OFFICE PRODUCTS',
 'JOE S DC',
 'WALDORF ASTORIA',
 'MCBEATH BILLY',
 'HAMPTON INN SUITES',
 'GODADDY',
 'INTRADO',
 'US DEPARTMENT OF THE TREASURY',
 'COASTAL PENSION',
 'THE TARRANCE GROUP',
 'DT CLIENT SERVICES',
 'CHICAGO PRIVATE CAR SERVICE',
 'HILTON CHICAGO OHARE AIRPORT',
 'HOTEL ZAZA DALLAS',
 'THE CAPITAL GRILLE',
 'SELINA UNION MARKET',
 'ATCHLEY ASSOCIATES',
 'ALA',
 'LEGISTORM',
 'RARE STEAKHOUSE TAVERN',
 'RPM ITALIAN',
 'WHITE ELEPHANT PALM BEACH',
 'CALDWELL KATHARYN',
 'CONCORD FLOWER SHOP',
 'DELMA S THE FLOWER SHOP',
 'CHICK FIL A',
 'JETBLUE AIRWAYS',
 'SFOGLINA DOWNTOWN',
 'THE MAYFLOWER HOTEL',
 'DEEP ROOT ANALYTICS',
 'JULIE ANDREWS ASSOCIATES',
 'PARTRIDGE CARMEN',
 'PARTRIDGE WARING',
 'SHM NEWPORT SHIPYARD',
 'THE KAUFFMAN',
 'FULKERSON KENNEDY',
 'JBW CONSULTING',
 'FIRST NATIONAL BANK OF OMAHA',
 'INTERCONTINENTAL MINNEAPOLIS ST PAUL AIRPORT',
 'BEST WESTERN THE HOTEL CHEQUAMEGON',
 'HILTON HOTELS RESORTS',
 'THE KAL GROUP',
 'AMP CAPITOL SOLUTIONS',
 'RIPPLING',
 'META FORMERLY FACEBOOK',
 'BANK OF LABOR',
 'K R PROMOTIONAL PRODUCTS',
 'BURKE BRYAN',
 'CANVA PTY',
 'DAVIS LISA',
 'HORNISH MICHELE',
 'MONSTER INSIGHTS',
 'NEWTEK MERCHANT SOLUTIONS',
 'PRESSABLE',
 'TEXTIFUL',
 'THE ROCKET SCIENCE GROUP',
 'TWILIO',
 'VIMEO',
 'WELLMAN FREDERICK',
 'X CORP',
 'LES WILLIAMSON',
 'LVH CONSULTING',
 'POLITICAL',
 'AD VICTORIAM',
 'BETTER MOUSETRAP DIGITAL',
 'FATLAB',
 'FRONTLINE',
 'IMGE',
 'POPACTA',
 'THE TRADE DESK',
 'TMA',
 'TRUIST MERCHANT',
 'WILEY REIN',
 'ADMINISTRATIVE BUSINESS SERVICES',
 'JOTFORM',
 'GILLESPIES FLOWERS',
 'HOTEL GEORGE',
 'SINPLICITY CATERING',
 'SUN VALLEY',
 'ATA POSTAGE AMERICAN TARGET ADVERTISING POSTAGE',
 'SMS',
 'PLAN BEE',
 'MILLER JULIAN',
 'DELTA AIR LINES',
 'AK AIRLINES',
 'MYERS PATRICIA',
 'GROUNDSWELL',
 'SCHWARTZ LAURA',
 'PUBLIC AFFAIRS SUPPORT SERVICES',
 'JP MORGAN CHASE',
 'STEPTOE',
 'BEAU CADEAU FOODS INC DBA HEIRLOOM CATERING',
 'CHRISTINA GUTIERREZ DBA J S QUALITY PRINTING',
 'PLANNED PARENTHOOD ADVOCATES MAR MONTE',
 'BLUE WAVE POLITICAL',
 'JPMORGAN CHASE BANK NA',
 'TX SECURITY BANK',
 'PAYROLL DATA PROCESSING',
 'LAYMAN KYLE',
 'POLITICAL COMMUNICATIONS',
 'DONELSON TOM',
 'VCREEK',
 'IN COMPLIANCE',
 'CASHMAN PRODUCTIONS',
 'CHERRY DANIELLE',
 'OFFICE DEPOT',
 'FMM',
 'JERAMIELU PHOTOGRAPHY',
 'PLP ENTERPRISES',
 'HERTZ CAR RENTAL',
 'LILLY',
 'MARRIOTT',
 'TURO',
 'BRIARWOOD',
 'GEN2 SOLUTIONS',
 'THE ACTION NETWORK',
 'THE WA POST',
 'AMERICAN CONSERVATIVE UNION',
 'BEST BUY',
 'GAYLORD NATIONAL RESORT',
 'HILTON MIAMI DOWNTOWN',
 'VIRGINIAN HOTEL',
 'COLDSPARK',
 'RED CURVE SOLUTIONS',
 'CLOUD DATA',
 'DEADWOOD INTERACTIVE SOLUTIONS',
 'GROUP CONSULTANTS',
 'LAV SERVICES',
 'RALLYPAY',
 'STANDARD DATA SERVICES',
 'WIRED4DATA',
 'ROBINSON VICKIE',
 'PARAGON SOLUTIONS',
 'DIGITAL MARKETING SOLUTIONS GROUP',
 'HOLTZMAN VOGEL BARAN JOSEFIAK TORCHINSKY P',
 'WIN RED TECHNICAL SERVICES',
 'INTELLIGENT OFFICE RESTON',
 'PEERLY',
 'AJ',
 'O MELVENY MYERS',
 'MONDAY',
 'BIPAC BUSINESS INSTITUTE FOR POLITICAL ANALYSIS',
 'CORETELLIGENT',
 'KNOWLES KELLY',
 'BOLDER FUNDRAISING',
 'CAPITAL LAW',
 'GRASSROOTS ANALYTICS',
 'MAILERLITE',
 'MARRIOTT RALEIGH CTY',
 'NUMERO',
 'SAPPHIRE',
 'SPECTRUM',
 'THE LONGLEAF HOTEL',
 'WHEELER DAVID',
 'NUVEI TECHNOLOGIES',
 'COMMONCENTSCONSULTING',
 'RESIST THIS',
 'BAYOU STATE STRATEGIES',
 'CANYON PLAZA SOUTH C O GPS ASSET MGMT',
 'MOLLY ALLEN ASSOCIATES',
 'TORREY PINES GOLF COURSE',
 'NMB',
 'MOTHERSHIP STRATEGIES',
 'STRATEGIC ADVANCE',
 'CORCORAN',
 'NUNGESSER',
 'GULF COAST BANK AND TRUST',
 'CAPITAL CAGING',
 'DIRECT SUPPORT',
 'DIRECT SUPPORT SYSTEMS',
 'INTEGRAM',
 'LEGACY LISTS',
 'MADEIRA ESCROW',
 'AFJ STRATEGIES',
 'CHRISTIE DAVID',
 'NH DEMOCRATIC PARTY',
 'WALSH BRIAN',
 'LANGDON LAW',
 'PHONE AT T',
 'EZPASS MD',
 'UPS STORE',
 'BRANCH BANKING TRUST',
 'COX COMMUNICATIONS',
 'PACSMART FILING SERVICES',
 'LEXINGTON AVENUE',
 'TIME WARNER CABLE OF NYC',
 'ADOBE SYSTEMS',
 'CURB TAXI',
 'UPS',
 'SISTINA RESTAURANT',
 'EMPIRE BLUECROSS',
 'EXPRESS EMPS',
 'GUARDIAN',
 'BART SAMUEL',
 'KUTRYB NICHOLAS',
 'NEWTON SAMUEL',
 'SECURE BLUE',
 'VERDOLINO LOWEY',
 'AIRBNB',
 'MERCHANT BANKCARD',
 'NOLAN RONNELL',
 'PROFIT MAX ACCOUNTING',
 'QUICKBOOKS',
 'THE GEORGE',
 'THE WILLARD',
 'ANYWHERE PAYMENTS',
 'NEWTEK',
 'FIRST DATA MERCHANT SERVICES',
 'TD BANK',
 'ROBERT WATKINS',
 'ACKERMAN WILLIAM',
 'CHILLIAK MATT',
 'KRANTZ ROSS',
 'SIMON SYDNEY',
 'SOPHIA TREMBLAY',
 'SUCHECKI MICHAEL',
 'VAN LARE ROWAN',
 'WISE HANNAH',
 'INSIDE ELECTIONS',
 'TIKU CONSULTING',
 'COMMON CENTS CONSULTING',
 'TRUE BLUE ANALYTICS',
 'COATS ERIC',
 'BNSF RAILWAY',
 'THE DUBLINER',
 'DUNCAN HALLIE',
 'LEBIN YATES CONSULTING',
 'CA DEPARTMENT OF TAX AND FEE ADMINISTRATION',
 'MIDDLE SEAT',
 'DISRUPTOR RADIO',
 'FORBRIGHT BANK',
 'THE STRATHDEE',
 'US BANK',
 'BENCHMARK',
 'CHARLIE PALMER',
 'SURVEYMONKEY',
 'FIRST INTERSTATE BANK',
 'MANDATE MEDIA',
 'NORTHERN COMPASS GROUP',
 'BAULD DENISE',
 'PALMETTO DEVELOPMENT STRATEGIES',
 'CARDMEMBER SERVICE CHASE',
 'KIAWAH ISLAND GOLF RESORT',
 'AGARWAL PRINCE',
 'DUMOUCHELLE LAURENE',
 'HAYES ROGER',
 'CUSTOMINK',
 'HUTT JEFF',
 'L2',
 'OTHERS INC DESIGN AND GRAPHICS',
 'PROWLY',
 'SENECA CLARK',
 'CHEESECAKE FACTORY',
 'HYATT REGENCY',
 'VANDERBOEGH ANDREW',
 'BOROUGH OF CLIFFSIDE PARK',
 'FIDELITY PAYMENT',
 'GEI',
 'JEWISH MEDIA GROUP',
 'SCHRANZ JOSEF',
 'THE JEWISH LINK OF NJ',
 'UNITED STATES POSTAL SERVICE LOCAL',
 'VALLEY NATIONAL BANK',
 'SANDLER REIFF',
 'CUCINA MORINI',
 'THE BRISTOL HOTEL SAN DIEGO',
 'HOTEL WA',
 'CORCORAN STREET GROUP',
 'WINRED TECHNICAL',
 'REGIONS BANK II',
 'CAMPAIGN REPORTS',
 'CHESAPEAKE BANK',
 'BACK OFFICE FOR ORGANIZING IN MI BOOM',
 'ACTION COMMITTEE MARKETING',
 'AMERICAN MARKETING SERVICES',
 'AVERY SERVICES',
 'CONTACT LOGISTIC CORP',
 'DONOR SOLUTION',
 'DS3 MARKETING',
 'EMPX',
 'GSI',
 'INTERNATIONAL UNION OF POLICE OFFICERS',
 'M D LOGISTICS',
 'OFFICE EDGE',
 'PACSMART FILING SERVICE',
 'POLITICAL RESPONSE',
 'PRO SPEAKING',
 'STATEWIDE PROFESSIONAL GROUP',
 'JBEST',
 'COREATIVE',
 'STAPLES',
 'VOUGHT STRATEGIES',
 'MO BANKERS',
 'SALK',
 'ITRIP',
 'EFUNDRAISING CONNECTIONS',
 'TRI COUNTIES BANK',
 'CONSERVATIVE CONNECTOR',
 'MOONSHINE MARKETING',
 'DAVEY CONSULTING',
 'GUARASCIO TIFFANY',
 'FITZSIMMONS LIAM',
 'THOMAS VALENTINA MANZO',
 'OCEAN CASINO RESORT',
 'SERENDIPITY',
 'HARD ROCK AC',
 'LANDSHARK ATLANTIC CITY',
 'INTUIT QUICKBOOKS',
 'ANE STRATEGIES',
 'HOAR KEVIN',
 'HOLTZMAN VOGEL',
 'MONUMENT',
 'NATIONAL RIFLE ASSOCIATION OF AMERICA INSTITUTE FOR LEGISLATIVE ACTION',
 'ASPECT CONSULTING',
 'ISTREAM FINANCIAL',
 'JOHNSON BANK',
 'RALLY DIGITAL',
 'TD MERCHANT',
 'ADCREATIVE AI',
 'AMH PRINT',
 'BORRELLI CHANTELLE',
 'CAMPAIGN FUNDING DIRECT',
 'CP DIRECT',
 'DJON S RESTAURANT',
 'DONORBUREAU',
 'ECG DATA CENTER',
 'ESPRESSO MAIL',
 'EXCEL MAILING',
 'EXTRA SPACE',
 'FIRST VA BANK',
 'HALL GRAPHIC DESIGN',
 'IMAGE DIRECT',
 'IVY ENDEAVORS',
 'LGM CONSULTING',
 'MDI IMAGING MAIL',
 'MILLER DONN',
 'MOORE RESPONSE MANAGEMENT',
 'MORALES ADA',
 'NORCROSS VICTORIA',
 'OMEGA LIST',
 'POLITICAL MEDIA',
 'PRUITT AND WALL',
 'RALLY PAY',
 'ROTERTECH SERVICES',
 'SELENA PARSONS',
 'STRIKINGLY',
 'SUNSHINE COMMUNICATION SERVICES',
 'THOUGHT LEADER',
 'VILLANO MICHELE',
 'VOTER INFUSION',
 'WALKER NAAR CHRISTINA',
 'WA INTELLIGENCE BUREAU',
 'HAMKAE CENTRE',
 'INDIA K RAJA',
 'KAGW',
 'ANGERHOLZER BROZ CONSULTING',
 'BLUEPRINT INTERACTIVE',
 'MOMENTUM CAMPAIGNS',
 'HELFRICH ANDREA',
 'HSBC',
 'COURTYARD MARRIOTT',
 'JERUSALEM MEDITERRANEAN CUISINE',
 'UNBOUGHT POWER',
 'JETBLUE',
 'BUMPERACTIVE',
 'BRICK AND MORTAR',
 'DISCREET SECURITY SERVICES AND INVESTIGATIONS',
 'CUNNINGHAM REGINALD',
 'BROWN DIOR',
 '2INFINITE PHOTOGRAPHY',
 'DETACHMENT',
 'SECURITY DETECTION',
 'NABILA S LEBANESE',
 'CLARKE SAMPSON',
 'DOCUSIGN',
 'TERRANCE BRONOWSKI',
 'WINPISINGER',
 '2CHECKOUT VERIFONE',
 'C2G STRATEGIES',
 'CHRISTIAN JERRAD',
 'COX TIMOTHY',
 'GRIFFIN RESEARCH CONSULTING',
 'ISTOCK BY GETTY IMAGES',
 'MAILCHIMP',
 'POLLOCK WILL',
 'SHUTTERSTOCK',
 'SITEGROUND HOSTING',
 'MICROSEARCH',
 'NEI BENEFIT PLANS',
 'NC STATE BOARD OF ELECTIONS',
 'ELECTRONIC MERCHANT SYSTEMS',
 'CHAVEZ DEREMER LORI',
 'CURB MOBILITY',
 'MOXY HOTELS',
 '9SEVEN',
 'DAVIS RODNEY',
 'CITI CREDIT CARD',
 'MAI TAI BAR',
 'PAPA FRANKS',
 'CORNERSTONE PAYMENT SYSTEMS',
 'NICO DIGITAL PRIVATE LIMITED',
 'US SMALL BUSINESS ADMINISTRATION',
 'PALLANTE JASON',
 'CLOUDFLARE',
 'PROPAY',
 'FIVERR FREELANCER PLATFORM MICHA KAUFMAN',
 'SG HOSTING',
 'DOMAIN',
 'SQUARE',
 'IMPRENTA COMMUNICATIONS GROUP',
 'REED DAVIDSON',
 'LANDSLIDE POLITICAL',
 'SAFARI CLUB INTERNATIONAL',

In [18]:
# Look at the largest vendors by amount paid by pacs
spending_data[spending_data['form_type']=='SB21B'].groupby('payee_organization_name').expenditure_amount.sum().sort_values(ascending=False)

payee_organization_name
MOTHERSHIP                                                                                                  6.496067e+07
LAUNCHPAD STRATEGIES                                                                                        5.863227e+07
UNITED STATES OF AMERICA                                                                                    5.200895e+07
WINRED TECHNICAL SERVICES                                                                                   5.194731e+07
COINBASE                                                                                                    4.801604e+07
META PLATFORMS INC                                                                                          4.675449e+07
AMERICAN EXPRESS                                                                                            4.319817e+07
TARGETED VICTORY                                                                                            3.738768e+07
EVENT STRATEGIES INC                                                                                        3.716968e+07
MOVEON ORG CIVIC ACTION                                                                                     3.026838e+07
GOOGLE                                                                                                      2.954901e+07
ACTBLUE TECHNICAL                                                                                           2.889216e+07
PATRIOT GRASSROOTS                                                                                          2.626798e+07
RED CURVE SOLUTIONS                                                                                         2.306900e+07
MISSIONWIRED                                                                                                2.191324e+07
MESSAGE DIGITAL                                                                                             2.175552e+07
ACE SPECIALTIES                                                                                             1.953407e+07
SHAWMUT SERVICES                                                                                            1.570906e+07
MAIN STREET MEDIA                                                                                           1.532010e+07
MIDDLE SEAT                                                                                                 1.343000e+07
PAYCHEX                                                                                                     1.331637e+07
RED BEACON STRATEGIES                                                                                       1.199836e+07
BLITZ CANVASSING                                                                                            1.182554e+07
NEXUS DIRECT                                                                                                1.180432e+07
DONALD J TRUMP FOR PRESIDENT  INC                                                                           1.178861e+07
DIRECTSND                                                                                                   1.175804e+07
TEAMDIRECT                                                                                                  1.124575e+07
PACTION DATA INC                                                                                            1.122852e+07
CANVASS AMERICA                                                                                             1.122701e+07
VANGUARD FIELD                                                                                              1.122491e+07
BUMPERACTIVE                                                                                                1.104528e+07
TAG                                                                                                         1.066316e+07
DNC SERVICES CORP DEM NAT L COMMITTEE                                                                       1.008463e+07
SAPPHIRE                                                                                                    1.005104e+07
SCALE TO WIN                                                                                                9.985339e+06
ROBERT ROBERT PLLC                                                                                          9.565825e+06
GEN2 SOLUTIONS                                                                                              9.428533e+06
RALLY BY RELENTLESS                                                                                         9.358283e+06
GRASSROOTS ANALYTICS                                                                                        9.114200e+06
CAMPAIGN INBOX                                                                                              9.067164e+06
STRATEGIC MEDIA PLACEMENT                                                                                   7.772658e+06
FABRIZIO LEE ASSOCIATES                                                                                     7.497250e+06
LIFTOFF CAMPAIGNS                                                                                           7.251393e+06
TATANGO                                                                                                     7.210223e+06
FRONTLINE STRATEGIES                                                                                        7.178236e+06
WPA INTELLIGENCE                                                                                            6.731698e+06
PAYLOCITY                                                                                                   6.562463e+06
PEERLY INC                                                                                                  6.506625e+06
THE OUTREACH TEAM                                                                                           6.486652e+06
OTG                                                                                                         6.430706e+06
WATERFRONT                                                                                                  6.364107e+06
DIRECT SUPPORT                                                                                              6.360564e+06
STRATEGIC ADVANCE                                                                                           6.319583e+06
BETTER MOUSETRAP DIGITAL                                                                                    6.114611e+06
TARGETED PLATFORM MEDIA                                                                                     6.094973e+06
DNC TRAVEL ESCROW                                                                                           6.041487e+06
JOHN F LAURO P A                                                                                            6.010004e+06
U S MARSHALS SERVICE                                                                                        6.000000e+06
PARAGON SOLUTIONS                                                                                           5.981288e+06
GRASSROOTS MEDIA                                                                                            5.895929e+06
TMA DIRECT INC                                                                                              5.795053e+06
SCREEN STRATEGIES MEDIA                                                                                     5.707550e+06
AMERICAN ISRAEL PUBLIC AFFAIRS COMMITTEE                                                                    5.624400e+06
COMMUNICATIONS CORPORATION OF AMERICA                                                                       5.468083e+06
HABBA MADAIO ASSOCIATES                                                                                     5.465870e+06
CONTINENTAL PLLC                                                                                            5.453048e+06
GUSTO                                                                                                       5.408776e+06
BLANCHE LAW                                                                                                 5.287573e+06
GDA WINS                                                                                                    5.252800e+06
NJ STATE LABORERS                                                                                           5.250000e+06
CHRIS KISE ASSOCIATES P A                                                                                   5.061868e+06
PLANNED PARENTHOOD ACTION FUND INC                                                                          5.048681e+06
MOUNTAIN MEDIA                                                                                              5.017044e+06
MOORE A SERIES                                                                                              4.726641e+06
GRASSROOTS FOR YOU                                                                                          4.659403e+06
AUTHENTIC CAMPAIGNS                                                                                         4.648675e+06
HMP                                                                                                         4.639000e+06
ONE NATION                                                                                                  4.603097e+06
DONORBUREAU                                                                                                 4.563113e+06
SOCKO STRATEGIES                                                                                            4.547805e+06
AISLE  STRATEGIES                                                                                           4.538790e+06
M2 PLACEMENT                                                                                                4.502279e+06
AB                                                                                                          4.387393e+06
PREMIER POLITICAL COMPLIANCE INC                                                                            4.363079e+06
AD PLACEMENT RESULTS                                                                                        4.291737e+06
ONMESSAGE INC                                                                                               4.241908e+06
FULFILLMENT SOLUTIONS INC                                                                                   4.240170e+06
ELAN EVENT STUDIO                                                                                           4.223266e+06
PACTION DATA                                                                                                4.165743e+06
WORKER POWER                                                                                                4.157705e+06
ANEDOT                                                                                                      4.063964e+06
SWITCHBOARD                                                                                                 3.974613e+06
MAJORITY STRATEGIES                                                                                         3.887619e+06
THE MAJORITY INSTITUTE                                                                                      3.796940e+06
FLEXPOINT MEDIA                                                                                             3.724591e+06
STRATEGIC ADVANCE SEVICES                                                                                   3.693039e+06
IMGE                                                                                                        3.684126e+06
BIDEN FOR PRESIDENT                                                                                         3.545667e+06
ANNE LEWIS                                                                                                  3.460070e+06
PUBLIC SUPPORT SERVICES                                                                                     3.444799e+06
TAG AIR INC                                                                                                 3.395948e+06
WIRED4DATA                                                                                                  3.388241e+06
ADP INC                                                                                                     3.353685e+06
MENTZER MEDIA                                                                                               3.298504e+06
VICTORY FORWARD SOLUTIONS                                                                                   3.276576e+06
NGP VAN INC                                                                                                 3.259540e+06
OPN SESAME                                                                                                  3.252477e+06
SEIU GENERAL FUND                                                                                           3.235913e+06
HARRIS FOR PRESIDENT                                                                                        3.213731e+06
NGP VAN                                                                                                     3.212775e+06
MDI IMAGING MAIL                                                                                            3.142412e+06
CAMPAIGN DATA GROUP                                                                                         3.110323e+06
RISING TIDE INTERACTIVE                                                                                     3.086387e+06
INTERNAL REVENUE SERVICE                                                                                    3.003531e+06
JUSTWORKS INC AND AFFILIATES                                                                                2.996111e+06
DIRECT MAIL SOLUTIONS                                                                                       2.989830e+06
ELIAS LAW                                                                                                   2.973614e+06
MOTHERSHIP STRATEGIES                                                                                       2.954891e+06
BLUEFOOT POLITICAL                                                                                          2.937366e+06
PLANET DIRECT                                                                                               2.931293e+06
GUIDANT POLLING AND STRATEGY                                                                                2.897248e+06
FORWARD STRATEGIES INC                                                                                      2.886144e+06
LONGWELL PARTNERS INC                                                                                       2.872265e+06
APEX STRATEGIES                                                                                             2.828203e+06
M STREET REIT LP                                                                                            2.757503e+06
INFORMATION CATALOGING                                                                                      2.744816e+06
GROSSMAN MARKETING                                                                                          2.721612e+06
HSP DIRECT                                                                                                  2.712775e+06
CONSOLIDATED MAILING                                                                                        2.701111e+06
PLANET DIRECT MAIL                                                                                          2.692209e+06
EVERYTOWN FOR GUN SAFETY ACTION FUND                                                                        2.688116e+06
NINE ONE SIX                                                                                                2.672076e+06
FINANCIAL INNOVATIONS                                                                                       2.669487e+06
ASCENSUS TRUST                                                                                              2.646520e+06
SILVERMAN THOMPSON SLUTKIN WHITE                                                                            2.627541e+06
TARGETSMART COMMUNICATIONS                                                                                  2.622967e+06
SWITCHBOARD PUBLIC BENEFIT CORP                                                                             2.550799e+06
AMALGAMATED BANK                                                                                            2.516063e+06
SWITCHBOARD PUBLIC BENEFIT                                                                                  2.478120e+06
VAN NESS CREATIVE STRATEGIES                                                                                2.470558e+06
HIGHWOOD CAPITAL                                                                                            2.466592e+06
FULKERSON KENNEDY COMPANY                                                                                   2.461829e+06
A TEAM DIGITAL                                                                                              2.459931e+06
LILLY COMPANY                                                                                               2.430002e+06
MEDIUM BUYING                                                                                               2.429800e+06
CLOUD DATA                                                                                                  2.421689e+06
WATERFRONT STRATEGIES INC                                                                                   2.420822e+06
WINRED TECHNICAL                                                                                            2.384570e+06
ACTBLUE                                                                                                     2.376313e+06
COMMUNITY LABOR ADMINISTRATIVE                                                                              2.350634e+06
2M DOCUMENT MANAGEMENT AND IMAGING                                                                          2.348471e+06
WINDWARD                                                                                                    2.329507e+06
AISLE                                                                                                       2.324123e+06
PENNSYLVANIA SEIU COPE                                                                                      2.321478e+06
DHILLON LAW GROUP INC                                                                                       2.303314e+06
TATANGO INC                                                                                                 2.297809e+06
STARBOARD                                                                                                   2.296928e+06
STRATEGIC ADVANCE SERVICES                                                                                  2.284391e+06
DRUCKER LAWHON                                                                                              2.278287e+06
MBA CONSULTING                                                                                              2.266642e+06
CALIFORNIA STATE COUNCIL SEIU                                                                               2.236974e+06
RWT PRODUCTION                                                                                              2.216620e+06
ROLLA GROUP                                                                                                 2.171901e+06
CMDI                                                                                                        2.151179e+06
DEMOCRACY ENGINE                                                                                            2.149350e+06

In [19]:
# Define dictionary for large vendors
#https://medium.com/@_bryceli/using-dictionaries-as-regex-in-python-de9033bb3e0f

def parse(input_str):
    # Dictionary with regex keys will be used as the pattern by turning it into a list then to a string.
    vendor_name_dict = {
        #'regex pattern': 'category'
        r'ACTBLUE|ACT BLUE|ACTBLEU|ACT BLEU|ACBLUE': 'ActBlue',
        r'WINRED|WIN RED': 'WinRed',
        r'\s?HILTON\s?|CONRAD (?:NY|NEW|WASHINGTON)|EMBASSY SUITES?|HAMPTON INN|HOME2|HOME\s?WOOD|WALDORF': 'HILTON HOTEL',
        r'UNITED STATES POSTAL|USPS|U S POSTAL': 'USPS',
        r'AMERIC?AN EXPRESS|AM\s?EX': 'AMERICAN EXPRESS',
        r'NGP\s?VAN|EVERY\s?ACTION': 'NGPVAN',
        r'FACEBOOK|META|INTEGRAM|INSTAGRAM': 'META',
        r'SIEU': 'SIEU',
        r'7 ELEVEN': '7ELEVEN',
        r'AC HOTEL|MARRIOTT|ALOFT|CITIZENM|RITZ CARLTON|ST REGIS|W HOTEL|SHERATON|DELTA HOTEL|WESTIN|RENAISSANCE|COURT\s?YARD HOTEL|SPRINGHILL SUITES?|DOUBLE\s?TREE|ELEMENT\b|FAIRFIELD\b|FOUR POINTS|\bJW\b|MERIDIEN|MOXY|RESIDENCE INN':'MARRIOTT HOTEL',
        r'\b(?:ACEC|AMERICAN COUNCIL OF ENGINEERING)\b':'ACEC PAC',
        r'\b(?:ACLI|AMERICAN COUNCIL OF LIFE INS)':'ACLI PAC',
        r'\bADOBE\b':'ADOBE',
        r'\bADP\b':'ADP',
        r'\bADT\b':'ADT',
        r'\bAFL\s?CIO\b': 'AFL CIO',
        r'ALAMO.+CAR': 'ALAMO CAR RENTAL',
        r'ALASKAN? AIR':'ALASKA AIRLINES',
        r'\bALLIANZ':'ALLIANZ TRAVEL SERVICES',
        r'AMALGAMATED': 'AMALGAMATED BANK',
        r'\b(?:AMAZON|AWS)\b': 'AMAZON',
        r'AMERICAN AIR': 'AMERICAN AIRLINES',
        r'AMERICAN LEGION':'AMERICAN LEGION',
        r'AMERICAN PROPERTY CASUALTY|APCIA':'APCIA PAC',
        r'ANNE LEWIS|MISSIONWIRED':'MISSIONWIRED',
        r'APPLE (?:CO\w+|ONLINE)': 'APPLE',
        r'ARIZONA DEMOCRATIC PARTY':'ARIZONA DEMOCRATIC PARTY',
        r'ASSEMBLY DEMOCRATIC CAMP|ASSEMBLY DEMOCRATIC COMM':'ASSEMBLE DEMOCRATIC CAMPAIGN COMMITEE',
        r'\bAT T\b': 'AT&T',
        r'\bLOCAL \d+\b|^LOCAL (?:\d+|(?:A )?INTERNATIONAL|IUOE|UNITE|TEAMSTER|SCHOOL|UNION)':'LOCAL UNION',
        r'\bAVIS\b':'AVIS RENTAL CAR',
        r'BANK OF AMERICA':'BANK OF AMERICA',
        r'\bBB T\b':'BB&T BANK',
        r'BELLAGIO':'BELLAGIO HOTEL',
        r'\bBEST\s?BUY\b': 'BEST BUY',
        r'\bBEST WESTERN\b': 'BEST WESTERN HOTEL',
        r'BLOOMBERG':'BLOOMBERG',
        r'BLUE\s?CROSS BLUE|BCBS|BLUE\s?PAC':'BLUE CROSS BLUE SHIELD',
        r'\bBMO\b':'BMO BANK',
        r'BOLD ACTIVE CON':'BOLD ACTIVE CONSERVATIVES PAC',
        r'BOSTON GLOBE':'BOSTON GLOBE',
        r'BOYS AND GIRLS CLUB|BOYS GIRLS CLUB':'BOYS AND GIRLS CLUB',
        r'BRETTPAC': 'BRETTPAC',
        r'BUDGET R':'BUDGET RENT A CAR',
        r'\bBWI\b':'BWI AIRPORT',
        r'CA LUV PAC': 'CA LUV PAC',
        r'\bCANVA\b':'CANVA',
        r'CAPITAL BANK':'CAPITAL BANK',
        r'CAPITAL GRILL':'CAPITAL GRILLE',
        r'CAPTIAL ONE [^ARENA]': 'CAPITAL ONE',
        r'CARMINES?': 'CARMINES',
        r'\bCAVA\b': 'CAVA',
        r'CHAIN\s?BRIDGE': 'CHANI BRIDGE BANK',
        r'CHARLIE PALMER STEAK':'CHARLIE PALMER STEAK HOUSE',
        r'CHARTER COMMUNICATIONS': 'CHARTER COMMUNICATIONS PAC',
        r'^CHASE (?:CARD|BANK|CO|CREDIT|VISA)': 'CHASE BANK',
        r'CHESTER CO\w+ DEM':'CHESTER COUNTY DEMOCRATIC COMMITEE',
        r'CHEVRON':'CHEVRON',
        r'CHICK? FIL A': 'CHICK FIL A',
        r'CHILI S\b': 'CHILIS',
        r'CHIPOTLE': 'CHIPOTLE',
        r'CHOICE HOTELS?|COMFORT INN|COUNTRY INN': 'CHOICE HOTELS',
        r'CIBC\b': 'CIBC BANK',
        r'CIRCLE K\b':'CIRCLE K',
        r'CITGO':'CITGO',
        r'\bCITI\s?(?:BANK|CARDS?|VISA|BUSINESS|CREDIT)':'CITI BANK',
        r'CITIZENS BANK':'CITIZEN BANK',
        r'COLONIAL PARK':'COLONIAL PARKING',
        r'COMCAST':'COMCAST',
        r'CONGRESSIONAL BLACK|\bCBC\b':'CONGRESSIONAL BLACK CAUCUS',
        r'CONGRESSIONAL HISPANIC|\bCHC\b':'CONGRESSIONAL HISPANIC CAUCUS',
        r'COSTCO\b':'COSTCO',
        r'CROWN PLAZA|HOLIDAY INN|IHG HOTEL|INTERCONTINENTAL|KIMP?TON|YOURS TRULY':'IHG HOTEL AND RESORTS',
        r'CURB (?:w\+)? TAXI': 'CURB TAXI',
        r'\bCVS\b':'CVS',
        r'\bCWA\b':'CWA UNION',
        r'DATA FOR PROGRESS|DATA FOR THE SOCIAL GOOD':'DATA FOR PROGRESS',
        r'\bDCA\b':'DCA AIRPORT',
        r'\bDCCC\b|DEMOCRATIC CONGRESSIONAL CAMP':'DCCC',
        r'DEL\s?FRISCO':'DEL FRISCOS',
        r'DELAWARE COUNTY DEM':'DELAWARE COUNTY DEMOCRATS',
        r'^DELTA$|DELTA AIR':'DELTA AIRLINES',
        r'DELUX (?:BUSINESS|CHECKS|ENTERPRISE|FOR|PRINTING)':'DELUX BUSINESS',
        r'DEMOCRATIC ATTORNEYS? GENERALS?':'DEMOCRATIC ATTORNEYS GENERAL ASSOCIATION',
        r'DEMOCRATIC GOVERNORS ASSOC|\bDGA\b':'DEMOCRATIC GOVERNORS ASSOCIATION',
        r'\bDLCC\b|DEMOCRATIC LEGISLATIVE CAMP':'DLCC',
        r'DEMOCRATIC (?:LIEUTENANT|LT) GOVERNORS?|\bDLGA\b':'DEMOCRATIC LIEUTENANT GOVERNORS ASSOCIATION',
        r'DEMOCRATIC MAJORITY':'DEMOCRATIC MAJORITY',
        r'\bDNC\b|DEMOCRATIC NATIONAL COM':'DNC',
        r'\bDSCC\b|DEMOCRATIC (?:SENATE|SENATORIAL) CAM':'DSCC',
        r'DEPARTMENT OF (?:THE |THE US )?TREASUR|\bIRS\b|INTERNAL REVENUE SERVICE': 'IRS',
        r'DISCOVER\s?(?:CARD|CREDIT)':'DISCOVER CARD',
        r'DISNEY':'DISNEY',
        r'DOLLAR A DAY|DOLLAR RENT':'DOLLAR RENT A CAR',
        r'DOMINION ENERGY':'DOMINION ENERGY',
        r'DOMINO\s?S':'DOMINOS PIZZA',
        r'DOOR\s?DASH':'DOOR DASH',
        r'DROP\s?BOX':'DROP BOX',
        r'\bDTW\b':'DTW AIRPORT',
        r'DUNKIN(?: DONUTS)?':'DUNKIN DONUTS',
        r'EINSTEIN (?:BROS|BROTHERS|BAGELS)':'EINSTEIN BROS BAGELS',
        r'\bEMERGE\b':'EMERGE ORG',
        r'EMILY\s?S LIST':'EMILYS LIST',
        r'EMPLOYERS? (?:\w+)? INS':'EMPLOYERS INSURANCE',
        r'\bENCORE\b|WYNN LAS':'ENCORE RESORTS',
        r'ENTERPRISE (?:CAR|HOLDING|R A C|RAC|RENT|TOLL)':'ENTERPRISE RAC',
        r'EQUALITY CALIFORNIA':'EQUALITY CALIFORNIA',
        r'EVERYTOWN FOR':'EVERYTOWN FOR GUN SAFETY',
        r'EXPEDIA|EXPIDA':'EXPEDIA',
        r'EXXON':'EXXON',
        r'EZ\s?CATER':'EX CATER',
        r'E\s?Z\s?PASS':'EZ PASS',
        r'FAIRMONT\b':'FAIRMONT HOTELS',
        r'\bFEC\b|FEDERAL ELECTIONS? COMM':'FEDERAL ELECTIONS COMMISSION',
        r'FED\s?EX|FEDERAL EXPRESS':'FEDEX',
        r'FIDELITY':'FIDELITY',
        r'FIRST (?:CITIZENS |NATIONAL |REPUBLIC )?BANK|FNB':'FIRST BANK',
        r'FONTAINBLE':'FONTAINBLEU',
        r'FORWARD MAJORITY':'FORWARD MAJORITY PAC',
        r'FOUNDING FARMERS?':'FOUNDING FARMERS',
        r'FOUR SEASONS?':'FOUR SEASONS HOTEL',
        r'FRESH MARKET':'FRESH MARKET',
        r'FRONTIER':'FRONTIER AIRLINES',
        r'FUTURE FORWARD':'FUTURE FORWARD PAC',
        r'GET\s?THRU':'GET THRU',
        r'GIANT':'GIANT SUPERMARKET',
        r'GIRL SCOUT':'GIRL SCOUTS',
        r'GO\s?DADDY':'GO DADDY',
        r'GOOGLE|GSUITE':'GOOGLE',
        r'GRAND BOH':'GRAND BOHEMIAN',
        r'\bHYATT\b':'HYATT HOTEL',
        r'GRASSROOTS DEM':'GRASSROOTS DEMOCRATS',
        r'GROUND\s?GAME':'GROUND GAME',
        r'NOMINEE FUND':'NOMINEE FUND',
        r'GRUB\s?HUB':'GRUBHUB',
        r'^GULF$|GULF OIL':'GULF',
        r'\bGUSTO\b':'GUSTO',
        r'HAPPY [C|D]OG':'HAPPY DOG',
        r'HARD ROCK':'HARD ROCK HOTEL',
        r'HARRIS\s?TEETER':'HARRIS TEETER',
        r'(?:BIDEN|HARRIS) VICTORY?|(?:BIDEN|HARRIS) FOR':'BIDEN/HARRIS COMMITTEES',
        r'HART RESEARCH':'HART RESEARCH',
        r'HAWKEYE':'HAWKEYE PAC',
        r'HEARTLAND (?:PAYROLL|PAYMENT|TRAVEL)':'HEARTLAND PAYROLL',
        r'HERTZ(?: CAR| AUTO| FINANCIAL| GLOBAL| HQ| RENT| SYSTEMS)|HER?TZ$':'HERTZ CAR RENTAL',
        r'^HOTELS?\b|^INN AT':'HOTEL',
        r'HOUSE MAJORITY':'HOUSE MAJORITY PAC',
        r'HOUSE REP\w+ CA|\bHRCC\b': 'HOUSE REPUBLICAN CAMPAIGN COMMITTEE',
        r'HOUSE DEM\w+ CA|\bHDCC\b': 'HOUSE DEMOCRATIC CAMPAIGN COMMITTEE',
        r'HOUSE REPw\+ MAJORITY':'HOUSE REPUBLICAN MAJORITY PAC',
        r'HOUSE VICTORY':'HOUSE VICTORY PAC',
        r'HSB?C':'HSBC BANK',
        r'HUDSON NEWS?':'HUDSON NEWS',
        r'HUMAN RIGHTS CAMPAIGN|\bHRC\b':'HUMAN RIGHTS CAMPAIGN',
        r'IBEW':'IBEW UNION',
        r'ICELAND(IC)?\s?AIR':'ICELAND AIR',
        r'STATE DEM\w+ PARTY':'STATE DEMOCRATIC PARTY',
        r'STATE REP\w+ PARTY':'STATE REPUBLICAN PARTY',
        r'ILLINOIS LIFE (?:HEALTH)? INSURANCE':'ILLINOIS LIFE HEALTH INSURANC COUNCIL',
        r'^IMPACT\b':'IMPACT CONSULTING',
        r'IN N OUT':'IN N OUT',
        r'INTEGRATED SOLUTION':'INTERGRATED SOLUTIONS',
        r'INTELSAT': 'IN FLIGHT WIFI',
        r'INT?UIT': 'INTUIT',
        r'IPOSTAL':'IPOSTAL',
        r'ISTOCK':'ISTOCK PHOTO',
        r'J\s?P\s?MORGAN|JPM CHASE':'JP MORGAN',
        r'J\s?STREET':'JSTREET PAC',
        r'JET (?:ACCESS)?AVIATION':'JET AVIATION',
        r'JET\s?BLUE': 'JETBLUE AIRLINES',
        r'^JFK\b':'JFK AIRPORT',
        r'JOBS EDUCATION':'JOBS EDUCATION AND FAMILIES FIRST PAC',
        r'JOE\s?S PIZZA':'JOES PIZZA',
        r'JOE\s?S SEA':'JOES SEAFOOD',
        r'JOE\s?S STONE':'JOES STONE CRAB',
        r'JOE THE JUICE':'JOE THE JUICE',
        r'K L GATES': 'KL GATES',
        r'K R\b': 'KR BRANDING',
        r'KEY\s?BANK': 'KEY BANK',
        r'KIRWAN\s?S': 'KIRWANS',
        r'KLAVIYO': 'KLAVIYO',
        r'KRASON (?:AND )?WOOD': 'KRASON AND WOOD STRATEGY',
        r'L2': 'L2 INC',
        r'LA COLOMBE': 'LA COLOMBE',
        r'LA GRANDE? BOU': 'LA GRANDE BOUCHERIE',
        r'LA\s?QUINTA':'LA QUINTA HOTEL',
        r'LA\s?ARDENTE':'LA ARDENTE',
        r'LAGUARDIA|LGA\b':'LAGUARDIA AIRPORT',
        r'LARRY W POTTS':'LARRY W POTTS FOR NC HOUSE OF REPRESENTATIVES',
        r'LAX\b': 'LAX AIRPORT',
        r'LAZ\b': 'LAZ PARKING',
        r'LEGACY LIST':'LEGACY LISTS INC',
        r'LEGAL SEA\s?FOODS':'LEGAL SEAFOODS',
        r'LEX[I|U]S\s?NEX[I|U]S': 'LEXIS NEXIS',
        r'LGM\b':'LGMM CONSULTING',
        r'LIBERTARIAN MUTUAL AID':'LIBERTARIAN MUTUAL AID',
        r'LIBERTY MUTU?AL':'LIBERTY MUTUAL INSURANCE',
        r'LIGHTHOUSE (?:MEDIA )?PRODUCTIONS':'LIGHTHOUSE PRODUCTIONS',
        r'LINKEDIN':'LINKEDIN',
        r'LITTLE CEASARS':'LITTLE CEASARS PIZZA',
        r'LL\s?BEAN':'LL BEAN',
        r'LOEWS|LOWE S HOTEL':'LOEWS',
        r'LOGAN AIR':'LOGAN AIRPORT',
        r'LOGAN CIRCLE':'LOGAN CIRCLE GROUP',
        r'LOGICTECH':'LOGICTECH',
        r'LOTTE':'LOTTE HOTEL',
        r'LYFT':'LYFT',
        r'M (?:AND )?T\s?BANK': 'M AND T BANK',
        r'MAIL\s?CH[I|A]MP': 'MAILCHIMP',
        r'MAILER\sLITE':'MAILER LITE',
        r'MAJORITY COMMITTEE':'MAJORITY COMMITTEE',
        r'MAR A LAGO': 'MAR A LAGO',
        r'MARATHON (?:GAS|FUEL|PETROL)':'MARATHON GAS',
        r'MARGARITAVILLE':'MARGARITAVILLE',
        r'MASTERCARD':'MASTERCARD',
        r'MASTRO\s?S\b':'MASTROS',
        r'MBA (?:CONSULTING|DATA)':'MBA CONSULTING',
        r'MDI IMAG':'MDI IMAGING',
        r'MEETING STREET':'MEETING STREET RESEARCH',
        r'MEMBERS? DINING':'MEMBERS DINING',
        r'MERCANTILE':'MERCANTILE BANK',
        r'MERCHANT (?:BANK|CARD|SERVICE)': 'MERCHANT BANK',
        r'MGM\s?GRAND':'MGM GRAND HOTEL',
        r'MICROSOFT':'MICROSOFT',
        r'MIDDLE\s?SEAT':'MIDDLE SEAT CONSULTING',
        r'MINUTE\s?MAN':'MINUTE MAN PRESS',
        r'MISSIONs?WIRED': 'MISSIONWIRED',
        r'MOE S':'MOES SW GRILL',
        r'MOORE RESPONSE':'MOORE RESPONSE MANAGEMENT GROUP',
        r'MORTGAGE BANKERS':'MORTGAGE BANKERS PAC',
        r'MORTON\s?S':'MORTONS STEAKHOUSE',
        r'MOTHERSHIP (?:STRATEGIES)?':'MOTHERSHIP',
        r'MOVEON ORG':'MOVEON ORG',
        r'MSP AIR':'MSP AIRPORT',
        r'MTA':'NEW YORK SUBWAY',
        r'NAACP':'NAACP',
        r'NASW \w+ CHAPTER PACE': 'NATIONAL ASSOCIATION OF SOCIAL WORKERS',
        r'NATIONAL AIR TRAFF': 'NATIONAL AIR TRAFFIC CONTROLLERS ASSOCIATION',
        r'NATIONAL (?:RENTAL )?CAR\b':'NATIONAL CAR RENTAL',
        r'NATIONAL JOURNAL':'NATIONAL JOURNAL GROUP',
        r'NATIONAL REP\w+ CONG|\bNRCC\b':'NRCC',
        r'NATIONAL REP\w+ SEN|\bNRSC\b':'NRSC',
        r'NATIONAL RESEARCH':'NATIONAL RESEARCH INC',
        r'NATIONAL RESTA':'NATIONAL RESTAURANT ASSOCIATION',
        r'NATIONAL RIFLE|\bNRA\b':'NRA',
        r'NBC\s?UNIVERSAL':'NBC UNIVERSAL',
        r'NEW YORK TIME|NY\s?TIMES?': 'NEW YORK TIMES',
        r'NEWRK (?:LIBERTY )AIR': 'NEWARK AIRPORT',
        r'NEXT LEVEL': 'NEXT LEVEL PARTNERS',
        r'NGP\b|NGP\s?VAN|EVERYACTION':'NGP EVERYACTION',
        r'NRCC\b|NATIONAL REPUBLICAN CONGR': 'NRCC',
        r'NRDC\b|NATIONAL RESOURCE DEFENSE COM': 'NRDC',
        r'NRSC\n|NATION REPUBLICAN SEN\w+ COM': 'NRSC',
        r'NYC (?:\s?w\+\s?w\+?\s+)?(?:TAXI|CAB)': 'NYC TAXI',
        r'OFFICE (?:MAX )?DEPOT': 'OFFICE DEPOT',
        r'OMNI\b':'OMNI HOTELS',
        r'PACTION':'PACTION DATA',
        r'PANERA':'PANERA BREAD',
        r'PAPA JOHN':'PAPA JOHNS',
        r'PARAGON':'PARAGON SOLUTIONS',
        r'PATHFINDER':'PATHFINDER COMMUNICATIONS',
        r'PAY\s?CHEX':'PAYCHEX',
        r'PAYMENTECH': 'PAYMENTECH',
        r'PAY\s?PAL':'PAYPAL',
        r'PEET\sS':'PEETS COFFEE',
        r'PENDRY\b':'PENDRY HOTEL',
        r'PHONE2ACTION':'PHONE2ACTION',
        r'PIZZA|PIZZ[E|A]RIA':'PIZZA',
        r'PLANET\s?DIRECT':'PLANET DIRECT MAILING',
        r'PLANNED PARENTHOOD':'PLANNED PARENTHOOD',
        r'PNC\b': 'PNC BANK',
        r'POLITICAL COMPLIANCE':'POLITICAL COMPLIANCE MANAGEMENT',
        r'POLITICO\b':'POLITICO',
        r'POPEYE\s?S?':'POPEYES',
        r'POTBELLY':'POTBELLY',
        r'PRICELINE|PRICELN': 'PRICELINE',
        r'PRICEWATERHOUSE|PWC\b':'PWC',
        r'PRODUCTION (?:MANAGEMENT )?ONE': 'PRODUCTION ONE',
        r'PROPAY':'PROPAY',
        r'PUNCH\s?BOWL':'PUNCHBOWL',
        r'QDOBA':'QDOBA',
        r'QUICKBOOKS?':'QUICKBOOKS',
        r'QUORUM ANALYTICS':'QUORUM ANALYTICS',
        r'RAISING CANE':'RAISING CANES',
        r'REPUBLIC BANK':'REPUBLIC BANK',
        r'REVV?\b':'REVV FUNDRAISING',
        r'RIVER\s?SIDE\s?FM':'RIVERSIDE FM',
        r'ROTI\b':'ROTI',
        r'SONESTA':'ROYAL SONESTA',
        r'SAFEGAURD':'SAFEGAURD SHREDDING',
        r'SAFE\s?WAY':'SAFEWAY',
        r'SALES?\s?FORCE': 'SALESFORCE',
        r'SANDLER REIFF':'SANDLER REIFF LAMB ROSENSTEIN BIRKENSTOCK',
        r'SAPPHIRE':'SAPPHIRE STRATEGIES',
        r'SBUX|STAR\sBUCKS?':'STARBUCKS',
        r'SCR\b':'SCR ASSOCIATES',
        r'SEIU\b|SERVICE EMPLOYEES':'SEIU',
        r'SEQUOIA':'SEQUOIA RESEARCH',
        r'SFO\b':"SAN FRANSISCO AIRPORT",
        r'SHELL\b':'SHELL OIL',
        r'SHOPIFY':'SHOPIFY',
        r'SHRED\b':'SHREDDING SERVICE',
        r'SHUTTER\s?STOCK':'SHUTTERSTOCK',
        r'SIERRA CLUB':'SIERRA CLUB',
        r'SINCLAIR BROAD':'SINCLAIR BROADCASTING',
        r'SITX\b':'SIXT CAR RENTAL',
        r'SKDK':'SKD KNICKERBOCKER',
        r'SLACK T': 'SLACK',
        r'SNOOZE':'SNOOZE AM EATERY',
        r'SODEXO':'SODEXO',
        r'SOUTHWEST AIR': 'SOUTHWEST',
        r'SPEECHIFAI':'SPEECHIFAI',
        r'SPIRIT AIR':'SPIRIT',
        r'SPOT\s?HERO':'SPOTHERO',
        r'SPOTIFY': 'SPOTIFY',
        r'SQUARE\s?(?:CAPITAL|FEES|GROUP|INC)?':'SQUARE',
        r'SQUARE\s?SPACE':'SQUARESPACE',
        r'STAPLES':'STAPLES',
        r'STAR\s?LINK':'STARLINK',
        r'STATE FARM':'STATE FARM',
        r'STRATEGIC ADVANCE':'STRATEGIC ADVANCE',
        r'STRATEGIC PARTNERS':'STRATEGIC PARTNERS',
        r'STRIPE\b':'STRIPE',
        r'SUBSTACK\b':'SUBSTACK',
        r'SUNOCO\b':'SUNOCO',
        r'SUSAN B ANTHONY':'SUSAN B ANTHONY LIST',
        r'SWEET\s?GREEN':'SWEETGREEN',
        r'SWITCHBOARD':'SWITCHBOARD',
        r'SYNOV':'SYNOVUS BANK',
        r'T\s?MOBILE': 'TMOBILE',
        r'TANGO\s?CARD':'TANGO CARD',
        r'TACOS\s|TAQUERIA':'TACOS',
        r'TARGET\s?SMART':'TARGETSMART',
        r'TARGE\s?POINT':'TARGETPOINT',
        r'TARGET\b': 'TARGET STORES',
        r'TATANGO':'TATANGO',
        r'TATTE\b': 'TATTE',
        r'TAXI\b':'TAXI',
        r'TD\s?(?:BANK|CARD|MERCHANT)':'TD BANK',
        r'TEAMSTERS?':'TEAMSTERS UNION',
        r'UNITED PARCEL|UPS':'UPS',
        r'THRIFTY CAR':'THRIFTY CAR RENTAL',
        r'TIDES ADVOCACY':'TIDES ADVOCACY',
        r'TOTAL\s?WINE':'TOTAL WINE',
        r'TPUSA|TURNING POINT':'TURNING POINT USA',
        r'TRAVELERS':'TRAVELERS INSURANCE',
        r'TRIUMPH':'TRIUMP COMMUNICATIONS',
        r'TRUIST|SUN\s?TRUST':'TRUIST BANK',
        r'TRUMP (?:HOTEL|INTERNATIONAL|NATIONAL|RESTAURANTS|TOWER)': 'TRUMP HOTELS',
        r'TRUMP SAVE':'TRUMP SAVE AMERICA',
        r'TV\s?EYES': 'TV EYES',
        r'TWILIO':'TWILIO',
        r'TWITTER':'TWITTER',
        r'U\sHAUL':'UHAUL',
        r'U\s?S\s?BANK':'US BANK',
        r'UAW?|UNITED AUTO':'UAW',
        r'UBER\b':'UBER',
        r'UFCW':'UFCW',
        r'ULINE':'ULINE',
        r'UNION LEAGUE':'UNION LEAGUE',
        r'UNITE HERE':'UNITE HERE',
        r'UNITED AIR':'UNITED AIRLINES',
        r'UNITED (?:BANK|BUSINESS)': 'UNITED BANK',
        r'UNITED\s?HEALTH':'UNITED HEALTH CARE',
        r'UNITED POSTAL|USPS|POST OFFICE|POSTAL SER|US POST':'USPS',
        r'UPLAND':'UPLAND SOFTWARE',
        r'UPSWING':'UPSWING RESEARCH',
        r'UPWAVE':'UPWAVE DIGITAL',
        r'UPWORK':'UPWORK',
        r'US\s?BANK':'US BANK',
        r'MARSHALL?S? SERVICE':'US MARSHALS SERVICE',
        r'US SENATE':'US SENATE',
        r'US HOUSE': 'US HOUSE',
        r'USA TODAY':'USA TODAY',
        r'USAA':'USAA',
        r'VAIL (?:SKI|RESORT)':'VAIL RESORT',
        r'VANGAURD':'VANGAURD',
        r'VANTIV|WORLD\s?PAY':'VANTIV WORLDPAY',
        r'VENTRA':'VENTRA',
        r'VERIZON':'VERIZON',
        r'VFW':'VFW',
        r'VIASAT':'VIASAT IN FLIGHT',
        r'VIRGIN (?:ATLANTIC|HOTEL)':'VIRGIN ATLANTIC',
        r'VISA\b':'VISA',
        r'VISTA\s?PRINT':'VISTAPRINT',
        r'VOTE\s?VETS?':'VOTEVETS',
        r'VRBO':'VRBO',
        r'WAL\s?MART':'WALMART',
        r'WALL?\s?GREEN':'WALGREENS',
        r'WALL ST\w+ JOURN|WSJ':'WALL STREET JOURNAL',
        r'WASHINGTON POST':'WASHINGTON POST',
        r'WASTE (?:MANAGEMENT|MGMT)':'WASTE MANAGEMENT',
        r'WAVE\s?LENGTH':'WAVELEANGTH STRATEGIES',
        r'WA\s?WA':'WA WA',
        r'WAY TO LEAD':'WAY TO LEAD',
        r'WELLS?\s?FARGO':'WALLES FARGO',
        r'WELLS?\s?PRINT':'WELLS PRINT AND DIGITAL SERVICES',
        r'WENDY\s?S':'WENDYS',
        r'WESTERN NATIVE':'WESTERN NATIVE VOICE',
        r'WHITE HOUSE':'THE WHITE HOUSE',
        r'WHOLE\s?FOOD':'WHOLE FOODS',
        r'WINE\b':'WINE',
        r'WINSTON\s?S':'WINSTONS FLOWERS',
        r'WIX':'WIX',
        r'WOLF\s?GANG':'WOLFGANG PUCKS',
        r'WYHDHAM':'WYNDHAM HOTELS',
        r'YOTEL':'YOTEL',
        r'YOU\s?TUBE':'YOUTUBE',
        r'ZAPIER':'ZAPIER',
        r'ZENDESK':'ZENDESK',
        r'ZOOM':'ZOOM',
        r'REPUBLICAN PARTY OF \w{2}$':'STATE REPUBLICAN PARTY',
        r'LIBERTARIAN PARTY OF \w{2}$':'STATE LIBERTARIAN PARTY',
        r'DEMOCRATIC PARTY OF \w{2}$':'STATE DEMOCRATIC PARTY',
        r'\w{2} SECRETARY OF STATE':'STATE SECRETARY OF STATE',
        r'FRIENDS OF THE \d{2}TH WAR':'FRIENDS OF THE WARD',
        r'REPUBLICAN HOUSE CAUCUS|HOUSE REPUBLICAN CAUCUS':'STATE REPUBLICAN HOUSE CAUCUS',
        r'\w{2} BANKERS ASSOCIATION': 'STATE BANKERS ASSOCIATION',
        r'\w{2} REPUBLICAN SENATE CAUCUS|\w{2} SENATE REPUBLICAN CAUCUS':'STATE REPUBLICAN SENATE CAUCUS',
        r'DEM\w+ HOUSE CAUCUS|HOUSE DEM\w+ CAUCUS':'STATE DEMOCRATIC HOUSE CAUCUS',
        r'\w{2} DEM\w+ SENATE CAUCUS|\w{2} SENATE DEM\w+ CAUCUS':'STATE DEMOCRATIC SENATE CAUCUS',
        r'REPUBLICAN STATE COMMITTEE|STATE REPUBLICAN COMMITTEE':'STATE REPUBLICAN COMMITTEE',
        r'DEMOCRATIC STATE COMMITTEE|STATE DEMOCRATIC COMMITTEE':'STATE DEMOCRATIC COMMITTEE',
        r'HOUSE REPUBLICAN CAMPAIGN CMTE|REPUBLICAN HOUSE CAMPAIGN CMTE':'STATE REPUBLICAN CAMPAIGN CMTE'
    }

    for pattern, vendor in vendor_name_dict.items():
        if re.search(pattern, input_str, re.IGNORECASE):
            return vendor  # return single mapped vendor name
    return None

In [20]:
# Create a vendor column based on the mappings above
spending_data['vendor'] = spending_data['payee_id'].apply(lambda x: parse(str(x)) if pd.notnull(x) else None)

In [21]:
spending_data.head()

,form_type,filer_committee_id_number,payee_organization_name,payee_last_name,payee_first_name,expenditure_date,expenditure_amount,expenditure_purpose_descrip,beneficiary_candidate_last_name,beneficiary_candidate_first_name,memo_code,memo_text_description,form_type_desc,payee_name,beneficiary_cand_name,payee_id,vendor
0,SB23,C00450965,MIKE BOST FOR CONGRESS COMMITTEE,NaN,NaN,,1000.0,CONTRIBUTION TO COMMITTEE,BOST,MIKE,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,MIKE BOST,MIKE BOST FOR CONGRESS COMMITTEE,None
1,SB23,C00450965,ANNIE,NaN,NaN,,2500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,ANNIE,None
2,SB23,C00450965,BRETTPAC,NaN,NaN,,1500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,BRETTPAC,BRETTPAC
3,SB23,C00450965,CASEY KEYSTONE VICTORY FUND,NaN,NaN,,1000.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,CASEY KEYSTONE VICTORY FUND,None
4,SB23,C00450965,OORAH,NaN,NaN,,2500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,OORAH,None

In [ ]:
# See remaining payee ids
payees = pd.DataFrame(spending_data[spending_data['vendor'].isna()].payee_id.unique())

payees.rename(columns={payees.columns[0]: "payee_id"}, inplace= True)

payees.sort_values(by ='payee_id')

In [23]:
# Calculate the dimensionality reduction so far
n_vendors = len(spending_data.vendor.unique()) + len(spending_data[spending_data['vendor'].isna()].payee_id.unique())

1-(n_vendors/n_original_payees)

0.08587745287474768

## Cleaning Contribution Expenditures 
To clean contribution expenditures I am going to use the committee master dataset from the FEC's Bulk Data site to try and fuzzy match committees to their official names.
To do this i need to do the same state name cleaning I did for the payee id so state names become state abbreviations

In [24]:
cmte = pd.read_csv('../data/raw/cmte_master_24.csv')
cmte.head()

,CMTE_ID,CMTE_NM,TRES_NM,CMTE_ST1,CMTE_ST2,CMTE_CITY,CMTE_ST,CMTE_ZIP,CMTE_DSGN,CMTE_TP,CMTE_PTY_AFFILIATION,CMTE_FILING_FREQ,ORG_TP,CONNECTED_ORG_NM,CAND_ID
0,C00000059,"HALLMARK CARDS, INC. PAC (HALLPAC)","KLEIN, CASSIE MS.","2501 MCGEE, MD853",NaN,KANSAS CITY,MO,64108,B,Q,UNK,M,C,"HALLMARK CARDS, INC.",NaN
1,C00000422,AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION ...,"JORDAN, JOHN ROBERT MR.","25 MASSACHUSETTS AVE, NW",SUITE 600,WASHINGTON,DC,200017400,B,Q,NaN,M,NaN,AMERICAN MEDICAL ASSOCIATION,NaN
2,C00000489,D R I V E POLITICAL FUND CHAPTER 886,JERRY SIMS JR,3528 W RENO,NaN,OKLAHOMA CITY,OK,73107,U,N,NaN,Q,L,NaN,NaN
3,C00000729,AMERICAN DENTAL ASSOCIATION POLITICAL ACTION C...,"TIPPETT-WHYTE, JUDEE DR.","400 C STREET, NE",NaN,WASHINGTON,DC,20002,B,Q,UNK,M,M,INDIANA DENTAL PAC,NaN
4,C00000885,INTERNATIONAL UNION OF PAINTERS AND ALLIED TRA...,"SMITH, GREGG",7234 PARKWAY DRIVE,NaN,HANOVER,MD,21076,B,Q,UNK,M,L,INTERNATIONAL UNION OF PAINTERS AND ALLIED TRADES,NaN

In [25]:
# Apply same string cleaning processes 
cmte = normalize_string_columns(cmte) 
cmte['CMTE_NM'] =  cmte['CMTE_NM'].fillna('').apply(replace_state_abbrev)
cmte['cmte_nm_len'] = cmte['CMTE_NM'].apply(lambda x: len(x))

In [26]:
cmte_vendors = spending_data[(spending_data['form_type'].isin(['SB22','SB23','SB29'])) & (spending_data['vendor'].isna()) & ((spending_data['payee_id'].str.len()>10) | (spending_data['payee_id'].str.contains(r'\w+PAC$', regex= True, case = False)))].payee_id.unique().tolist()

In [27]:
cmte_vendors = sorted(cmte_vendors, key=len)
cmte_vendors

['MPAC',
 'CPAC',
 'MCPAC',
 'PBPAC',
 'WEPAC',
 'HAPAC',
 'GOPAC',
 'BOPAC',
 'FFPAC',
 'BIPAC',
 'FEPAC',
 'ADPAC',
 'LIPAC',
 'IIPAC',
 'PIPAC',
 'SIPAC',
 'CEPAC',
 'RVFPAC',
 'BEEPAC',
 'ARKPAC',
 'BOWPAC',
 'KEYPAC',
 'ZENPAC',
 'WAXPAC',
 'BATPAC',
 'AEMPAC',
 'LEGPAC',
 'KEVPAC',
 'BECPAC',
 'PABPAC',
 'GASPAC',
 'MORPAC',
 '150PAC',
 'CARPAC',
 'CAMPAC',
 'PAWPAC',
 'FEDPAC',
 'RFWPAC',
 'OCCPAC',
 'MADPAC',
 'NVRPAC',
 'CBCPAC',
 'WINPAC',
 'ICBPAC',
 'JEBPAC',
 'BIZPAC',
 'NORPAC',
 'BACKPAC',
 'LANKPAC',
 'ALSOPAC',
 'THOMPAC',
 'JACKPAC',
 'AR RPAC',
 'DE RPAC',
 'FL RPAC',
 'GA RPAC',
 'KY RPAC',
 'MD RPAC',
 'MI RPAC',
 'MT RPAC',
 'NC RPAC',
 'NH RPAC',
 'NJ RPAC',
 'SD RPAC',
 'TN RPAC',
 'TX RPAC',
 'WA RPAC',
 'WV RPAC',
 'PHILPAC',
 'CITIPAC',
 'FOODPAC',
 'REITPAC',
 'MO RPAC',
 'UT RPAC',
 'FAIRPAC',
 'WPBTPAC',
 'CMCCPAC',
 'VIEWPAC',
 'DOUGPAC',
 'NC MPAC',
 'LA RPAC',
 'OR RPAC',
 'VINEPAC',
 'IL MPAC',
 'WOLFPAC',
 'MN RPAC',
 'AL RPAC',
 'COALPAC',
 'BANKPAC',
 'NACSPAC',
 'MINEPAC',
 'CHEMPAC',
 'PETEPAC',
 'CO RPAC',
 'DBTCPAC',
 'AMERIPAC',
 'ND REPAC',
 'FIRSTPAC',
 'HOULAPAC',
 'POWERPAC',
 'MURPHPAC',
 'SIGMAPAC',
 'MCANJPAC',
 'INSURPAC',
 'BRAVEPAC',
 'ANNIEPAC',
 'DREAMPAC',
 'NAMICPAC',
 'BLACKPAC',
 'TENNEPAC',
 'TERRIPAC',
 'STEELPAC',
 'SENDEMPAC',
 'FORESTPAC',
 'FUTUREPAC',
 'HEALTHPAC',
 'FL CARPAC',
 'CHAMBERPAC',
 'MIJENTEPAC',
 'WISBANKPAC',
 'WELCOMEPAC',
 'IL BANKPAC',
 'VA BANKPAC',
 'DOUGLASPAC',
 'IN BANKPAC',
 'GA BANKPAC',
 'GARRETTPAC',
 'EMPOWERPAC',
 'AGA GASPAC',
 'WA DC RPAC',
 'GBA FEDPAC',
 'TELECOMPAC',
 'OR BANKPAC',
 'CAMERONPAC',
 'OH BANKPAC',
 'MARC FOR US',
 'BURGESS  UT',
 'REAGAN FUND',
 'THOMAS DENT',
 'CONVENTIONS',
 'ALLEY LARRY',
 'BLASI CHASE',
 'HALEY DAVID',
 'HOLLAND TOM',
 'PECK VIRGIL',
 'RYCKMAN RON',
 'SYKES DINAH',
 'LOGE DENLEY',
 'FIRST IN TX',
 'US TREASURY',
 'FIRST STATE',
 'VICTORY NOW',
 'DAY KRISTEN',
 'GRASSHOPPER',
 'NEW LEADERS',
 'DREW FOR NV',
 'RUDY FOR IN',
 'BELL FOR MO',
 'WIN IT BACK',
 'BOYENS ALEC',
 'JONES BLAIR',
 'KRAMER NOAH',
 'LEVITT WILL',
 'THE MADISON',
 'TEAM GRAHAM',
 'JONI FOR IA',
 'HANK JOHSON',
 'ALFORD MARK',
 'STEUBE GREG',
 'DONORBUREAU',
 'A BOLDER FL',
 'MO ALLIANCE',
 'LARSEN RICK',
 'POWER OF US',
 'WI PROGRESS',
 'BELL PHILIP',
 'BOW TIE PRO',
 'ORGANIZE PA',
 'ERIN FOR KY',
 'GREAT CHAIN',
 'ARIAS MARIO',
 'ISPOLITICAL',
 'PROTEUS LAB',
 'JOHN CURTIS',
 'LOVE FOR TX',
 'PROGRESSPAC',
 'BLUE ACTION',
 'RIOS ADRIAN',
 'WARNER KYLE',
 'GARRIE ADAM',
 'CONTE LOUIS',
 'WATSON LEAH',
 'KOZIS BILLY',
 'ALLIED DATA',
 'ATHENA LABS',
 'FIOLA MIAMI',
 'AZ BILTMORE',
 'AK AIRLINES',
 'TERI FOR GA',
 'BRAY FOR KY',
 'GOMEZ JIMMY',
 'ONE APIA NV',
 'GREAT LAKES',
 'CALVERT KEN',
 'KIAM VICTOR',
 'FAST LIZARD',
 'DEBONA JOHN',
 'HALL STEVEN',
 'KELLY ROBIN',
 'SWING STATE',
 'SWEET JULIE',
 'ACTION FUND',
 'REBUILD USA',
 'BETH FOR TX',
 'BITRAN YOEL',
 'HASAN NAFIS',
 'BIRD FOR IA',
 'WILZ FOR IA',
 'WULF FOR IA',
 'YOUNG DAVID',
 'JACKY ROSEN',
 'JOYCE CRAIG',
 'LUCY MCBATH',
 'DANICA ROEM',
 'ANGIE CRAIG',
 'MOORE BLAKE',
 'DEVELOPWELL',
 'TEAM MORENO',
 'ERIC FOR GA',
 'PRESTIGE WW',
 'LINDSEY FOR',
 'CO BEVERAGE',
 'NM BEVERAGE',
 'MORALES  NM',
 'TEAM WICKER',
 'ONE TEAM LA',
 'BERLINROSEN',
 'HANSEN LIAM',
 'LEFT LEDGER',
 'NO NONSENSE',
 'TONY FOR WI',
 'MI S FUTURE',
 'PAGE FOR MO',
 'PETE CAMPOS',
 'MOUNTAINEER',
 'LARE FOR OH',
 'EASTERSEALS',
 'HOPE CHURCH',
 'JL RESEARCH',
 'THE MELLMAN',
 'WILANNE  KY',
 'WOOL NICOLE',
 'CAMMACK KAT',
 'WEGNER CPAS',
 'PALO LINELL',
 'COLEMAN FOR',
 'DARK CORNER',
 'WILLIAM FOR',
 'ELECT ETHAN',
 'BAIRD JAMES',
 'CARTER TROY',
 'COMER JAMES',
 'FRY RUSSELL',
 'KEAN THOMAS',
 'SOTO DARREN',
 'STEIL BRYAN',
 'SMART MEDIA',
 'ARNDT MEGAN',
 'BELL HAYLEY',
 'BOOTH PETER',
 'LEDDY PAIGE',
 'MIN KAITLYN',
 'RICE HALLIE',
 'COOK MAISIE',
 'CBT NUGGETS',
 'THE KC STAR',
 'FISCHER TEX',
 'HOLMES ADAM',
 'ROEMER BILL',
 'ALEX FOR AZ',
 'ALMA FOR AZ',
 'THE WA POST',
 'CORADO IRMA',
 'SNOW JULIAN',
 'FIEFIA DOUG',
 'ABA BANKPAC',
 'WOOD FOR IA',
 'JEFF WRIGHT',
 'THE MORNING',
 'HALLMARK MO',
 'PROFIT LINE',
 'GRAY ADAM C',
 'FAITH IN NY',
 'BLUE SENATE',
 'ROJAS DAVID',
 'BROWN EMILY',
 'DSPOLITICAL',
 'CUPAC OF NC',
 'CARLSON KEN',
 'HOPE FOR PA',
 'IA REALTORS',
 'PA REALTORS',
 'VT REALTORS',
 'MARKMESSMER',
 'COMMON GOOD',
 'PAUL FOR PA',
 'JACK FOR AG',
 'BENTZ CLIFF',
 'KIM SCHRIER',
 'CE4A ACTION',
 'CASTEN SEAN',
 'GARCIA CHUY',
 'SALERNO JOE',
 'GALL DANIEL',
 'ADDIS DAVID',
 'ALLEN JOANN',
 'ARVIG ALLEN',
 'BERGE NANCY',
 'BLACK MARTA',
 'BROWN ALLAN',
 'BRYAN DEBRA',
 'BUNN DANIEL',
 'BURGESS LEE',
 'BURKE ERWIN',
 'DAVIS MONTY',
 'DEATON BILL',
 'FRANCIS JAY',
 'HARMER JOHN',
 'HICKEY TROY',
 'LAPAN DAVID',
 'LUND GEORGE',
 'MCNIFF JOHN',
 'MORAN FRANK',
 'MORRIS ROSE',
 'NUPEN LARRY',
 'PINSON THEO',
 'POTTS CYRUS',
 'REDMAN RICK',
 'SMITH SCOTT',
 'SOLET JULIA',
 'STINE STEVE',
 'VAIL DELMAR',
 'WHITE KEITH',
 'WU SINGCHOU',
 'YATES LINDA',
 'SEATTLE CFO',
 'AHMAD REEMA',
 'HILL RACHEL',
 'LORD ZAKIYA',
 'LUCAS DARYL',
 'MELMAN ALEX',
 'OLSON TRACY',
 'STRONGER MO',
 'IWEN FOR NY',
 'STATE OF MI',
 'KBA PAC FOR',
 'ROTH FOR WI',
 'STATE OF IA',
 'CARR FOR GA',
 'KEEP KS RED',
 'ROSE FOR WV',
 'TEAM LAHOOD',
 'JOHN BOLTON',
 'CAPITAL ONE',
 'PHIL FOR VA',
 'GALT FOR SD',
 'JONES STEVE',
 'DOW REBECCA',
 'FREE INDEED',
 'HAYSTAQ DNA',
 'KECK FOR KY',
 'COST CURTIS',
 'TEICH ROGER',
 'BERGER PHIL',
 'HALL DESTIN',
 'PARTNERSHIP',
 'BABIN BRIAN',
 'DIRECT WINS',
 'LETT FOR OH',
 'TONE JE VON',
 'KING RACHEL',
 'DADE PHELAN',
 'TRENT ASHBY',
 'CODY HARRIS',
 'ERIN FOR MN',
 'WARE FOR KS',
 'TONY FOR NY',
 'SALTON ADAM',
 '4C PARTNERS',
 'SALAME RYAN',
 'JEFF FOR AZ',
 'JUDY FOR AZ',
 'VOTE BOLICK',
 'RILEY ANGEL',
 'AFT NM COPE',
 'PROJECT  WI',
 'BRAD FOR GA',
 'BRIANNA FOR',
 'BRIDGES FOR',
 'TOKYO JOE S',
 'ONE VA FUND',
 'ESTES ABBIE',
 'CHANG AARON',
 'ULRICH LISA',
 'STORYBLOCKS',
 'BACON KEVIN',
 'OTTO ROBERT',
 'MARCH ON MD',
 'HUFF ARISIA',
 'DARBY HOUSE',
 'HTTV DIRECT',
 'BUCY FOR TX',
 'WALL FOR WI',
 'NEW ECONOMY',
 'TEAM HUDSON',
 'AB DATA LTD',
 'COLE FOR VA',
 'CASE EDWARD',
 'HARDER JOSH',
 'LOFGREN ZOE',
 'RED CYPRESS',
 'JOHN FOR UT',
 'RINGCENTRAL',
 'BAKER SARAH',
 'PRESTA LISA',
 'HENG ALISHA',
 'MSBILL INFO',
 'MAXIT CESAR',
 'BOYSENBERRY',
 'ALG POLLING',
 'KENNEDY TIM',
 'FLS CONNECT',
 'O2M DIGITAL',
 'ALEK FOR OR',
 'GOODMAN  KS',
 'MOSES CREEK',
 'APPLE STORE',
 'CANYON DEMS',
 'AMERICA NOW',
 'PEACH STATE',
 'MARY FOR IL',
 'HONOR BOUND',
 'BEN FOR LOU',
 'PURI SANJAY',
 'SAMI FOR OR',
 'HOLST KEVIN',
 'ROCKETREACH',
 'MASTERCLASS',
 'SKAGGS PHIL',
 'COSTA MARIN',
 'IHEARTMEDIA',
 'KEN BENNETT',
 'EILON ETHAN',
 'SCEUSA CARL',
 'TARA FOR WI',
 'BEN JERRY S',
 'ANDY NELSON',
 'KIEN TRUONG',
 'DIANA LIMON',
 'DONALD FINN',
 'MOIR MONICA',
 'PRIME MEDIA',
 'COEFFICIENT',
 'COOKE CELIA',
 'TARGETPOINT',
 'WENDI OLSON',
 'PHELAN DADE',
 'STUCKY LYNN',
 'FREEMAN BOB',
 'HEY DIGITAL',
 'IL NV  FUND',
 'ROSEN JACKY',
 'TREASURE FL',
 'ROLLA GROUP',
 'BOND EVENTS',
 'MORGAN NICK',
 'STATES MADE',
 'DEHNE AMBER',
 'MEIER CHRIS',
 'HERRON LORI',
 'UROPARTNERS',
 'ORR ANGELIA',
 'GOMEZ DAISY',
 'SIMON TESSA',
 'WEPRIN SETH',
 'APH DIGITAL',
 'CIVIC SHOUT',
 'TUPLE LEGAL',
 'FIGHT RIGHT',
 'THE CITADEL',
 'RUSS FOR WI',
 'EIDEL JAMES',
 'MILLER ADAM',
 'MARK LEVINE',
 'HOWE FOR ND',
 'TRANS CARGO',
 'BREWER ERIN',
 'MAY STANLEY',
 'WRIGHT LORI',
 'RAMIREZ FOR',
 'GREG FOR MT',
 'BINNALL LAW',
 'KRAMER ALEX',
 'SCOTT ELENA',
 'STATE OF NY',
 'MOMS FED UP',
 'NV ALLIANCE',
 'MASON CHRIS',
 'KUTZ FOR PA',
 'SAGE AGENTS',
 'ON THE MOVE',
 'LISA DEELEY',
 'CAFE ROTHEM',
 'NGUYEN LINH',
 'THE WHITLEY',
 'WOMEN2WOMEN',
 'BECK KELSEY',
 'ZUCKER LILA',
 'PYLE MARISA',
 'FACUNDO EVA',
 'KNAPP JESSE',
 'KOZUCH MARK',
 'PIVOT GROUP',
 'CAPITOL ONE',
 'MATT FOR MT',
 'HOEFEN JOHN',
 'RISE UNITED',
 'KENT FOR WV',
 'FREEDOM PAC',
 'ZAIDI LAELA',
 'PROGRESSNOW',
 'SMITH CARLA',
 'AMIDON ERIC',
 'BEST BERNIE',
 'HUNT WESLEY',
 'LOUIS COREA',
 'DEM TURNOUT',
 'KINDER ELLA',
 'COES SAMUEL',
 'FULMER EVAN',
 'ZUZULA ZANE',
 'BANKER MIRA',
 'LEE JACKSON',
 'BELL RODNEY',
 'GEORGE RYAN',
 'HAMLIN LUKE',
 'BONAR ELLEN',
 'GWYN JAYLEN',
 'GARNER NIYA',
 'MERY CHIARA',
 'MATSON SETH',
 'GALE WESTON',
 'PEREZ ALEXA',
 'PRIGUN JOHN',
 'HOULE LACEY',
 'NADA MARIAM',
 'EGNER NANCY',
 'ARNOLD LEAH',
 'SMILEY SETH',
 'MUNOZ NANCY',
 'MORREN TARA',
 'BARBEE MARY',
 'HUNT SIERRA',
 'ADAMS SCOTT',
 'PETROS MARY',
 'PEREZ DANNY',
 'DROBA AIMEE',
 'GARDNER IAN',
 'BROWN SIMON',
 'KELLY CONOR',
 'HALL CAROLE',
 'MOSER JACOB',
 'RIOS DANIEL',
 'LETT BRENDA',
 'BUNDAY KARL',
 'LOURIE NOAH',
 'BYRD TYRESE',
 'RIVAS ALDEN',
 'KAST SAMUEL',
 'ALLEN TYLER',
 'WATERS NOAH',
 'CADY MONICA',
 'SYED ZARINA',
 'TAYLOR JOEL',
 'KELLY GRACE',
 'MARR HUDSON',
 'GRANT KELLI',
 'ROHRER LEAH',
 'MILLAR SARA',
 'RUNGTA RHEA',
 'DECKER ZOEY',
 'ZIOBRON ZOE',
 'UNITY FIRST',
 'MD S FUTURE',
 'ZUMBACH DAN',
 'SIGNAL HIRE',
 'RESTORATION',
 'BECK FOR MO',
 'ROUND WORLD',
 'MO HERITAGE',
 'JACK BACHUS',
 'JOHN DEBONA',
 'STEVEN HALL',
 'CARTER EARL',
 'GARCIA MIKE',
 'LUCAS FRANK',
 'PALMER GARY',
 'SMITH JASON',
 'WEBER RANDY',
 'STEWARDSHIP',
 'MEGAN BARRY',
 'GARY FOR WY',
 'DAVIS JOYCE',
 'PAC A PUNCH',
 'NETA COLLAB',
 'SYKES DEREK',
 'SHANK AIDAN',
 'OR BEVERAGE',
 'CORNYN JOHN',
 'CAMACHO FOR',
 'TISHA MAURO',
 'TAYLOR GAIR',
 'JACOBS SARA',
 'LOPEZ VICKI',
 'SIMON COREY',
 'MURT FOR DJ',
 'AR TRUCKING',
 'HESHAM NOUR',
 'TABLER JAKE',
 'LELA ALSTON',
 'BIRD BRENNA',
 'JOSH FOR PA',
 'HEARTDOCPAC',
 'GRANT CLIVE',
 'ORGANIZE AZ',
 'BERKE FARAH',
 'TONG SAMUEL',
 'BIRD FOR WI',
 'KENMORE AIR',
 'MCNEARY ANN',
 'ZULLO FRANK',
 'PARKER RYAN',
 'ZUDDU DARIO',
 'RICE ANDREW',
 'OWENS NANCY',
 'WEBER DYLAN',
 'BRASE BRIAN',
 'COADY CONOR',
 'LAVIN KATIE',
 'CROFT KAREN',
 'BEARD BECKY',
 'LER BRANDON',
 'NOVAK SARAH',
 'LEVIATE AIR',
 'ACTUM UK OP',
 'FIGHTIN 9TH',
 '1HOOD POWER',
 'NATE FOR FL',
 'WASHBANKPAC',
 'LERE FOR OH',
 'TEAM MOONEY',
 'GORDON LISA',
 'SEVEN LAMPS',
 'LOPEZ SONIA',
 'PA TOGETHER',
 'PROGRESS RI',
 'HAMEDAH ABE',
 'MURPHY GREG',
 'IRON LADIES',
 'BELMONT  UT',
 'OWEN FOR UT',
 'VOTE VIVIAN',
 'LEGENDZ BBQ',
 'TACO CABANA',
 'THE AZ CAFE',
 'WHATABURGER',
 'TEAM BUTLER',
 'EGEMEN METE',
 'BENTALL NIA',
 'OCHOA LAURA',
 'SCOTT LARRY',
 'PROGRESS MI',
 'MAYNE RILEY',
 'CLARE LOCKE',
 'CLOCKIFY ME',
 'LEE MATTHEW',
 'LIBERAL ART',
 'TESFU SOFIA',
 'TESS STRAND',
 'GARCIA RENE',
 'CHAVEZ ALMA',
 'DANG ANNE T',
 'DO PHUONG H',
 'HUYNH TRISH',
 'MORENO OMAR',
 'NGUYEN VU T',
 'TRINH KIM B',
 'VU VINH KIM',
 'MAXIMUM SPL',
 'JURGENS GAY',
 'ZEHR FOR VA',
 'MOOK ROBERT',
 'THE DEL BAR',
 'THE PALAZZO',
 'NEW SHERIFF',
 'BOWIE SUSAN',
 'STATE OF FL',
 'MOORE DAVID',
 'HUNT FOR NC',
 'MARTIN GREG',
 'KYLE FOSTER',
 'MELLEN JAKE',
 'PUGH FOR MI',
 'KEIR FOR AG',
 'TAYLOR DALE',
 'BACK AUSTIN',
 'CASSIL NOAH',
 'MUNIZ JESSE',
 'YADAV TISYA',
 'YANG AMARIS',
 'YANG CALVIN',
 'ZWEBTI RAMI',
 'GUPTA YAJAT',
 'KELLY ETHAN',
 'TABAIE MARY',
 'YOUNG CHRIS',
 'BRAUN KEITH',
 'TX MAJORITY',
 'RESIST THIS',
 'MURPHY JOHN',
 'OLIVIA ROSE',
 'TAPIA PETER',
 'KELLY PRESS',
 'AZ REPUBLIC',
 'NEWSLIBRARY',
 'WISPOLITICS',
 'HODO EVENTS',
 'PEREZ SONIA',
 'KERR JOSEPH',
 'PRESS PRINT',
 'PLATI ALICE',
 'FINK FOR PA',
 'AARON SQUEO',
 'JERRY YOUNG',
 'BERG FOR MN',
 'FAIRNESS PA',
 'BILL WESLEY',
 'PETERS GARY',
 'JACE FOR TX',
 'NINA FOR PA',
 'BERG FOR ND',
 'RE STRATEGY',
 'RURAL AM FM',
 'PROGRESSIVE',
 'BLUEOC LIVE',
 'ED GONZALES',
 'KIM YONG HO',
 'NORTH SHORE',
 'EKLUND JOHN',
 'KNAPP CHRIS',
 'OLSEN JARED',
 'REED JACK F',
 'WILSON ADAM',
 'BLACK ANNIE',
 'ELDA FOR AZ',
 'MAKO FOR PA',
 'TOGETHER PA',
 'BERRY GERRY',
 'CLARK BRIAN',
 'DELEO SHAWN',
 'GEE GREGORY',
 'LONG JOSEPH',
 'JUST REFORM',
 'WMA MINEPAC',
 '6TYSIXMEDIA',
 'STREET ZONE',
 'COX STANLEY',
 'FRAMEBRIDGE',
 'WAY TAHESHA',
 'FETAW MIELA',
 'NOMAD MEDIA',
 'PIZZO JASON',
 'JOBS GROWTH',
 'CNP SERVICE',
 'BERNAL CRUZ',
 'GRANGER KAY',
 'BAUM FOR MT',
 'SCHEXNAYDER',
 'JULION MACK',
 'KHOP SHOOTS',
 'SCHIFF ADAM',
 'SIMON STEVE',
 'TAJ EXPRESS',
 'FRAHM ILENE',
 'MACLIN RYAN',
 'HAWKINS LEE',
 'POWELL ALAN',
 'NH PEOPLE S',
 'QML FOR PHL',
 'LOPEZ ANITA',
 'WOMAN UP CA',
 'CHS BSO JFC',
 'DEBI SCAGGS',
 'BACARDI USA',
 'ID S FUTURE',
 'AL FIRSTPAC',
 'VBA BANKPAC',
 'MIKE FOR VT',
 'CURTIS JOHN',
 'BAY ARMOURY',
 'HART FOR WV',
 'TIFFANY TOM',
 'THOMAS KOPP',
 'SMITH KEMBA',
 'LAWLER MIKE',
 'CLIO AWARDS',
 'SMALL CHRIS',
 'NOVA BIZPAC',
 'REED JOHN F',
 'GOOCH STEVE',
 'KUCHAR BILL',
 'CLEO FIELDS',
 'AL FAMILIES',
 'DAN PAFIRST',
 'ONWARD FUND',
 'ALFOND JOAN',
 'BASS ROBERT',
 'MCIVER BILL',
 'DIETZ SUSAN',
 'ROTH STEVEN',
 'KIRBY DAVID',
 'ROSE LESLIE',
 'BRADY MARNE',
 'CITY STONES',
 'LEADER JESS',
 'REACH RIGHT',
 'FUNDRAISING',
 'LECOMPTE ED',
 'WARNER TODD',
 'GALDO MARIA',
 'MENDIVE  ID',
 'THE H HOTEL',
 'HASHEM MARK',
 'SAIKI SCOTT',
 'LANGER ANNA',
 'NUNN FOR IA',
 'EDWARDS JAY',
 'HUSTED JOHN',
 'HANSEN BETH',
 'HOGAN LARRY',
 'PUBLIC WISE',
 'CUSTOMER IO',
 'HANDWRYTTEN',
 'INFLUENCITY',
 'BEAM DENTAL',
 'SABIO MAGAT',
 'HAYNES SEAN',
 'IN BUILDERS',
 'SC BUILDERS',
 'RG2 TUESDAY',
 'ASHBY LAW P',
 'NO EASY DAY',
 'BLOUT ASTIN',
 'BROWN SCOTT',
 'BROWN SIERA',
 'CANTOS ABEL',
 'DOBY KHAYLA',
 'TENG CARTER',
 'KIGGANS JEN',
 'SUREPAYROLL',
 'TEAM  STATE',
 'TOKUDA JILL',
 'KILEY KEVIN',
 'TINA FOR OR',
 'REA OF HOPE',
 'WERNE MARLA',
 'KING FOR TX',
 'FOX WHITNEY',
 'STEWART RON',
 'ERNST LEGAL',
 'KAPWING PRO',
 'MARKMONITOR',
 'ENVISION NY',
 'FERN FOR SD',
 'SOLOMON FOR',
 'MURRILL LIZ',
 'BANKS LLOYD',
 'FOSTER ERIC',
 'MOORE RILEY',
 'HALL FOR MS',
 'AMO GABRIEL',
 'LARSON JOHN',
 'GETZUG COBY',
 'GALVIN BILL',
 'BREW GARDEN',
 'DIPALMA LOU',
 'SOUTH CREEK',
 'BARCA PETER',
 'TRAHAN LORI',
 'SABB RONNIE',
 'CONE EDWARD',
 'JULIE MENIN',
 'FOSS AUSTIN',
 'AMY VERLAIC',
 'MENDEZ JOSE',
 'COREAS EDIS',
 'JOYA HECTOR',
 'KADULI YVES',
 'MOXIE MEDIA',
 'LEON AMARIS',
 'SMITH LARRY',
 'THE JENKINS',
 'PRIMO WATER',
 'EXTRA SEVEN',
 'HULSE AMBER',
 'LEVIN TYLER',
 'RED COMPASS',
 'RESES JACOB',
 'ELISABETTAS',
 'PDQ CHICKEN',
 'LEVINE MARK',
 'BEAN FOR FL',
 'HUNT FOR TX',
 'KEAN FOR NJ',
 'LUNA FOR FL',
 'THE OORBEEK',
 'FREEDOMFEST',
 'DEE S HOUSE',
 'PERRY WENDY',
 'HAGAN SCOTT',
 'SERLIN NATE',
 'TURNER ABBY',
 'I BACK JACK',
 'HOSPITALITY',
 'MARY FOR VA',
 'SIEGEL MARK',
 'DRIVER COLE',
 'JIMMY JOHNS',
 'PEARCE TRUE',
 'ATLANTA DSA',
 'NEWMAN JOSH',
 'GABARRA AMY',
 'TOASTED OWL',
 'SCULLY NORA',
 'CARSON JOHN',
 'GRINER CLAY',
 'PARSONS DON',
 'REEVES MATT',
 'REED ASHLEY',
 'FLORES PETE',
 'BRIAN BLAKE',
 'LEFT RISING',
 'EPP MELISSA',
 'BANNER LIFE',
 'THE MARKHAM',
 'MARY FOR ID',
 'U S CHAMBER',
 'MEDINA JOSE',
 'MIKE FOR MT',
 'DARYL SMITH',
 'HOEVEN JOHN',
 'TX TOOLBELT',
 'MCMIKLE JOE',
 'MOTHER WOLF',
 'SEVEN HILLS',
 'VALDEZ LUPE',
 'MEDIA GROUP',
 'WALKER BOYD',
 'LOCKE DAVID',
 'REIGER LYNN',
 'FELAG WALLY',
 'GALLO HANNA',
 'MT BUSINESS',
 'KELLY DAVID',
 'SCOTT BOBBY',
 'TEAM  SLATE',
 'XAVIER YDSA',
 'ELECT VANEL',
 'TEAM SIMCHA',
 'WAXHAM REED',
 'FREEHAND NY',
 'HORN HAYDEN',
 'OUMA PHILIP',
 'THE HERSHEY',
 'ELECT JULIA',
 'JAYME DAVIS',
 'TEAM CRAMER',
 'ALLEN AVERY',
 'ANSARI ASNA',
 'BRAND ILONA',
 'BURKE JAIRA',
 'FAGAN JAYNE',
 'GELLER SETH',
 'GORDON CODY',
 'ISAAC EMILY',
 'KUGLER SARA',
 'PERCY CHRIS',
 'REDDY KEDAR',
 'SCULLY KATE',
 'SHAHID SANA',
 ...]

To clean the contributions to PACs and committees I attempt to use fuzzy matching to create groups that we can assign the same name to. To start I find the best match across all metric types and save them as a data frame. This helped me to see how matching could go. Importantly, I'm not comparing the payee_ids against each other, but the official committee names from the FEC committee master dataset.

In [28]:
# Fuzzy matching exploration 
cmte_names = cmte[((cmte['cmte_nm_len']>10) | (cmte['CMTE_NM'].str.contains(r'\w+PAC$'))) & (~cmte['CMTE_NM'].isin(['VICTORY FUND','ACTION FUND','POLITICAL ACTION COMMITTEE']))].CMTE_NM.unique().tolist()
to_cat = cmte_vendors


def get_best_matches(list_1,list_2):
    results = []
    for aa in list_1:
        results_dict = {"vendor": aa}

        for score_type, scorer in [
            ('ratio',fuzz.ratio),
            ('partial_ratio', fuzz.partial_ratio),
            ('token_sort_ratio', fuzz.token_sort_ratio),
            ('token_set_ratio', fuzz.token_set_ratio)
        ]:
            best_match = process.extractOne(aa, list_2, scorer = scorer)
            if best_match:
                results_dict[f"{score_type}_match"] = best_match[0]
                results_dict[f"{score_type}_score"] = best_match[1]
            else:
                results_dict[f"{score_type}_match"] = None
                results_dict[f"{score_type}_score"] = None
        
        levenshtein_best = min(list_2, key = lambda x: distance.Levenshtein.distance(aa, x))
        levenshtein_score = distance.Levenshtein.distance(aa, levenshtein_best)
        results_dict['levenshtein_match'] = levenshtein_best
        results_dict['levenshtein_score'] = levenshtein_score

        results.append(results_dict)
    
    return results

matches = get_best_matches(to_cat,cmte_names)
matches_df = pd.DataFrame(matches)

In [29]:
matches_df.head(25)

,vendor,ratio_match,ratio_score,partial_ratio_match,partial_ratio_score,token_sort_ratio_match,token_sort_ratio_score,token_set_ratio_match,token_set_ratio_score,levenshtein_match,levenshtein_score
0,MPAC,IMPAC,88.888889,UNITED STATES TELECOM ASSOCIATION POLITICAL AC...,100.000000,IMPAC,88.888889,MARATHON PETROLEUM CORPORATION EMPLOYEES POLIT...,100.000000,KPAC,1
1,CPAC,CPAC,100.000000,ACPAC ACA INTERNATIONAL POLITICAL ACTION COMMI...,100.000000,CPAC,100.000000,CPAC ACTION,100.000000,CPAC,0
2,MCPAC,MSCPAC,90.909091,REDWINGMCPAC,100.000000,MSCPAC,90.909091,MSCPAC,90.909091,MSCPAC,1
3,PBPAC,BOPAC,80.000000,NATIONAL ASSOCIATION OF BROADCASTERS POLITICAL...,88.888889,BOPAC,80.000000,BOPAC,80.000000,LBPAC,1
4,WEPAC,EDPAC,80.000000,WOMEN FOR EQUALITY PAC WEPAC,100.000000,EDPAC,80.000000,WOMEN FOR EQUALITY PAC WEPAC,100.000000,ARPAC,2
5,HAPAC,HPAC,88.888889,THE HOSPITAL AND HEALTHSYSTEM ASSOCIATION OF P...,100.000000,HPAC,88.888889,THE HOSPITAL AND HEALTHSYSTEM ASSOCIATION OF P...,100.000000,HPAC,1
6,GOPAC,GIPAC,80.000000,GOPAC ELECTION FUND,100.000000,GIPAC,80.000000,GOPAC ELECTION FUND,100.000000,GIPAC,1
7,BOPAC,BOPAC,100.000000,BOPAC,100.000000,BOPAC,100.000000,BOPAC,100.000000,BOPAC,0
8,FFPAC,RVFPAC,72.727273,CHURCHILL DOWNS INCORPORATED FPAC,88.888889,RVFPAC,72.727273,RVFPAC,72.727273,ARPAC,2
9,BIPAC,GIPAC,80.000000,BIPARTISAN POLITICAL ACTION COMMITTEE THE BANK...,100.000000,GIPAC,80.000000,BIPARTISAN POLITICAL ACTION COMMITTEE THE BANK...,100.000000,GIPAC,1
10,FEPAC,EDPAC,80.000000,BRACEPAC,88.888889,EDPAC,80.000000,EDPAC,80.000000,ARPAC,2
11,ADPAC,ARPAC,80.000000,ADPAC INDEPENDENT EXPENDITURES COMMITTEE,100.000000,ARPAC,80.000000,ADPAC INDEPENDENT EXPENDITURES COMMITTEE,100.000000,ARPAC,1
12,LIPAC,GIPAC,80.000000,ULLICO INC POLITICAL ACTION COMMITTEE ULLIPAC,100.000000,GIPAC,80.000000,GIPAC,80.000000,GIPAC,1
13,IIPAC,GIPAC,80.000000,HUNTINGTON INGALLS INDUSTRIES INC EMPLOYEES PO...,100.000000,GIPAC,80.000000,GIPAC,80.000000,GIPAC,1
14,PIPAC,GIPAC,80.000000,AMERICAN LAND TITLE ASSOCIATION TITLE INDUSTRY...,88.888889,GIPAC,80.000000,GIPAC,80.000000,GIPAC,1
15,SIPAC,SKIPAC,90.909091,AMERICAN BUS ASSOCIATION POLITICAL ACTION COMM...,88.888889,SKIPAC,90.909091,SKIPAC,90.909091,GIPAC,1
16,CEPAC,CPAC,88.888889,BRACEPAC,100.000000,CPAC,88.888889,CONSTELLATION ENERGY CORPORATION EMPLOYEE POLI...,100.000000,CPAC,1
17,RVFPAC,RVFPAC,100.000000,RVFPAC,100.000000,RVFPAC,100.000000,RVFPAC,100.000000,RVFPAC,0
18,BEEPAC,ELEPAC,83.333333,BEEPAC BUILDING ECONOMIC EMPOWERMENT PAC,100.000000,ELEPAC,83.333333,BEEPAC BUILDING ECONOMIC EMPOWERMENT PAC,100.000000,LEGPAC,2
19,ARKPAC,ARPAC,90.909091,KPAC,100.000000,ARPAC,90.909091,AR FOR LEADERSHIP POLITICAL ACTION COMMITTEE A...,100.000000,ARPAC,1
20,BOWPAC,BOPAC,90.909091,DOW INC PAC DOWPAC,90.909091,BOPAC,90.909091,BOPAC,90.909091,BOPAC,1
21,KEYPAC,KPAC,80.000000,SPANKTHEDONKEYPAC,100.000000,KPAC,80.000000,KPAC,80.000000,KITPAC,2
22,ZENPAC,EDPAC,72.727273,GENENTECH INC POLITICAL ACTION COMMITTEE GENENPAC,90.909091,EDPAC,72.727273,EDPAC,72.727273,LEGPAC,2
23,WAXPAC,TAXPAC,83.333333,SOUTHWEST AIRLINES CO POLITICAL ACTION COMMITT...,90.909091,TAXPAC,83.333333,TAXPAC,83.333333,TAXPAC,1
24,BATPAC,LATPAC,83.333333,TPAC,100.000000,LATPAC,83.333333,LATPAC,83.333333,LATPAC,1

In [30]:
# the state party and district wards are often only off by a letter or two, but the differences are significant and I don't want to misattribute an expenditure. So i want to look more closely at these groups
state_party_patterns = r'\b(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY) (?:DEM\w+|REPU\w+|HOUSE DEM\w+|SENATE DEMw\+|HOUSE REPU\w+|SENATE REPUw\+|COUNTY|DFL)'
district_ward_patterns = r'\d{2}TH|1ST'

state_party_vendors = sorted(matches_df[(matches_df['vendor'].str.contains(state_party_patterns, regex=True))].vendor.unique().tolist())
district_ward_vendors = sorted(matches_df[(matches_df['vendor'].str.contains(district_ward_patterns, regex=True))].vendor.unique().tolist())

/var/folders/cl/bdrh3m8j0fdfj6zm7zhhc2ch0000gn/T/ipykernel_76724/515219276.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  state_party_vendors = sorted(matches_df[(matches_df['vendor'].str.contains(state_party_patterns, regex=True))].vendor.unique().tolist())

In [31]:
# Create a boolean column when all match values are the same
matches_df['same_match'] = (
    (matches_df['ratio_match'] == matches_df['partial_ratio_match']) &
    (matches_df['partial_ratio_match'] == matches_df['token_sort_ratio_match']) &
    (matches_df['token_sort_ratio_match'] == matches_df['token_set_ratio_match']) &
    (matches_df['token_set_ratio_match'] == matches_df['levenshtein_match'])
)

cols = [
    'ratio_score',
    'partial_ratio_score',
    'token_sort_ratio_score',
    'token_set_ratio_score'
]

# Average the match scores across all metrics
matches_df['avg_score'] = matches_df[cols].mean(axis = 1)

In [ ]:
# Attempting to find a rule that could help assign matches
matches_df[
    (matches_df['same_match']==True) 
    & (matches_df['levenshtein_score']>0) 
    & ~(matches_df['vendor'].str.contains(state_party_patterns, regex = True)) 
    & ~(matches_df['vendor'].str.contains(district_ward_patterns, regex = True))
    & ~(matches_df['ratio_match'].str.contains(state_party_patterns, regex = True)) 
    & ~(matches_df['ratio_match'].str.contains(district_ward_patterns, regex = True))
    ].sort_values('avg_score',ascending = False)

### Methodology 2 

Select a single metric from rapidfuzz to try and assign matches. I chose token_sort_ratio because I don't want the order of tokens in a string to matter, but the more tokens that match the better. 

I use a high match threshold (95) because I am very averse to misattributing spending.

In [33]:
unique_names = cmte_vendors
threshold = 95
groups = []

while unique_names:
    name = unique_names.pop(0)
    # Find all similar names
    matches = process.extract(name, unique_names, scorer=fuzz.token_sort_ratio, score_cutoff=threshold)
    # Add name itself
    group = [name] + [m[0] for m in matches]
    groups.append(group)
    # Remove matched names
    unique_names = [x for x in unique_names if x not in [m[0] for m in matches]]

groups

[['MPAC'],
 ['CPAC'],
 ['MCPAC'],
 ['PBPAC'],
 ['WEPAC'],
 ['HAPAC'],
 ['GOPAC'],
 ['BOPAC'],
 ['FFPAC'],
 ['BIPAC'],
 ['FEPAC'],
 ['ADPAC'],
 ['LIPAC'],
 ['IIPAC'],
 ['PIPAC'],
 ['SIPAC'],
 ['CEPAC'],
 ['RVFPAC'],
 ['BEEPAC'],
 ['ARKPAC'],
 ['BOWPAC'],
 ['KEYPAC'],
 ['ZENPAC'],
 ['WAXPAC'],
 ['BATPAC'],
 ['AEMPAC'],
 ['LEGPAC'],
 ['KEVPAC'],
 ['BECPAC'],
 ['PABPAC'],
 ['GASPAC'],
 ['MORPAC'],
 ['150PAC'],
 ['CARPAC'],
 ['CAMPAC'],
 ['PAWPAC'],
 ['FEDPAC'],
 ['RFWPAC'],
 ['OCCPAC'],
 ['MADPAC'],
 ['NVRPAC'],
 ['CBCPAC'],
 ['WINPAC'],
 ['ICBPAC'],
 ['JEBPAC'],
 ['BIZPAC'],
 ['NORPAC'],
 ['BACKPAC'],
 ['LANKPAC'],
 ['ALSOPAC'],
 ['THOMPAC'],
 ['JACKPAC'],
 ['AR RPAC'],
 ['DE RPAC'],
 ['FL RPAC'],
 ['GA RPAC'],
 ['KY RPAC'],
 ['MD RPAC'],
 ['MI RPAC'],
 ['MT RPAC'],
 ['NC RPAC'],
 ['NH RPAC'],
 ['NJ RPAC'],
 ['SD RPAC'],
 ['TN RPAC'],
 ['TX RPAC'],
 ['WA RPAC'],
 ['WV RPAC'],
 ['PHILPAC'],
 ['CITIPAC'],
 ['FOODPAC'],
 ['REITPAC'],
 ['MO RPAC'],
 ['UT RPAC'],
 ['FAIRPAC'],
 ['WPBTPAC'],
 ['CMCCPAC'],
 ['VIEWPAC'],
 ['DOUGPAC'],
 ['NC MPAC'],
 ['LA RPAC'],
 ['OR RPAC'],
 ['VINEPAC'],
 ['IL MPAC'],
 ['WOLFPAC'],
 ['MN RPAC'],
 ['AL RPAC'],
 ['COALPAC'],
 ['BANKPAC'],
 ['NACSPAC'],
 ['MINEPAC'],
 ['CHEMPAC'],
 ['PETEPAC'],
 ['CO RPAC'],
 ['DBTCPAC'],
 ['AMERIPAC'],
 ['ND REPAC'],
 ['FIRSTPAC'],
 ['HOULAPAC'],
 ['POWERPAC'],
 ['MURPHPAC'],
 ['SIGMAPAC'],
 ['MCANJPAC'],
 ['INSURPAC'],
 ['BRAVEPAC'],
 ['ANNIEPAC'],
 ['DREAMPAC'],
 ['NAMICPAC'],
 ['BLACKPAC'],
 ['TENNEPAC'],
 ['TERRIPAC'],
 ['STEELPAC'],
 ['SENDEMPAC'],
 ['FORESTPAC'],
 ['FUTUREPAC'],
 ['HEALTHPAC'],
 ['FL CARPAC'],
 ['CHAMBERPAC'],
 ['MIJENTEPAC'],
 ['WISBANKPAC'],
 ['WELCOMEPAC'],
 ['IL BANKPAC'],
 ['VA BANKPAC', 'VBA BANKPAC'],
 ['DOUGLASPAC'],
 ['IN BANKPAC'],
 ['GA BANKPAC'],
 ['GARRETTPAC'],
 ['EMPOWERPAC'],
 ['AGA GASPAC'],
 ['WA DC RPAC'],
 ['GBA FEDPAC'],
 ['TELECOMPAC'],
 ['OR BANKPAC'],
 ['CAMERONPAC'],
 ['OH BANKPAC'],
 ['MARC FOR US'],
 ['BURGESS  UT'],
 ['REAGAN FUND'],
 ['THOMAS DENT'],
 ['CONVENTIONS'],
 ['ALLEY LARRY'],
 ['BLASI CHASE'],
 ['HALEY DAVID'],
 ['HOLLAND TOM'],
 ['PECK VIRGIL'],
 ['RYCKMAN RON'],
 ['SYKES DINAH'],
 ['LOGE DENLEY'],
 ['FIRST IN TX'],
 ['US TREASURY'],
 ['FIRST STATE'],
 ['VICTORY NOW'],
 ['DAY KRISTEN'],
 ['GRASSHOPPER'],
 ['NEW LEADERS'],
 ['DREW FOR NV'],
 ['RUDY FOR IN'],
 ['BELL FOR MO'],
 ['WIN IT BACK'],
 ['BOYENS ALEC'],
 ['JONES BLAIR'],
 ['KRAMER NOAH'],
 ['LEVITT WILL'],
 ['THE MADISON'],
 ['TEAM GRAHAM'],
 ['JONI FOR IA'],
 ['HANK JOHSON'],
 ['ALFORD MARK'],
 ['STEUBE GREG'],
 ['DONORBUREAU'],
 ['A BOLDER FL', 'A BOULDER FL'],
 ['MO ALLIANCE'],
 ['LARSEN RICK'],
 ['POWER OF US'],
 ['WI PROGRESS'],
 ['BELL PHILIP'],
 ['BOW TIE PRO'],
 ['ORGANIZE PA'],
 ['ERIN FOR KY'],
 ['GREAT CHAIN'],
 ['ARIAS MARIO'],
 ['ISPOLITICAL'],
 ['PROTEUS LAB'],
 ['JOHN CURTIS', 'CURTIS JOHN'],
 ['LOVE FOR TX'],
 ['PROGRESSPAC'],
 ['BLUE ACTION'],
 ['RIOS ADRIAN'],
 ['WARNER KYLE'],
 ['GARRIE ADAM'],
 ['CONTE LOUIS'],
 ['WATSON LEAH'],
 ['KOZIS BILLY'],
 ['ALLIED DATA'],
 ['ATHENA LABS'],
 ['FIOLA MIAMI'],
 ['AZ BILTMORE'],
 ['AK AIRLINES'],
 ['TERI FOR GA'],
 ['BRAY FOR KY'],
 ['GOMEZ JIMMY'],
 ['ONE APIA NV'],
 ['GREAT LAKES'],
 ['CALVERT KEN'],
 ['KIAM VICTOR'],
 ['FAST LIZARD'],
 ['DEBONA JOHN', 'JOHN DEBONA'],
 ['HALL STEVEN', 'STEVEN HALL'],
 ['KELLY ROBIN'],
 ['SWING STATE'],
 ['SWEET JULIE'],
 ['ACTION FUND'],
 ['REBUILD USA'],
 ['BETH FOR TX'],
 ['BITRAN YOEL'],
 ['HASAN NAFIS'],
 ['BIRD FOR IA'],
 ['WILZ FOR IA'],
 ['WULF FOR IA'],
 ['YOUNG DAVID'],
 ['JACKY ROSEN', 'ROSEN JACKY'],
 ['JOYCE CRAIG'],
 ['LUCY MCBATH'],
 ['DANICA ROEM'],
 ['ANGIE CRAIG', 'CRAIG ANGIE'],
 ['MOORE BLAKE', 'MOORRE BLAKE'],
 ['DEVELOPWELL'],
 ['TEAM MORENO'],
 ['ERIC FOR GA'],
 ['PRESTIGE WW'],
 ['LINDSEY FOR'],
 ['CO BEVERAGE'],
 ['NM BEVERAGE'],
 ['MORALES  NM'],
 ['TEAM WICKER'],
 ['ONE TEAM LA'],
 ['BERLINROSEN', 'BERLIN ROSEN'],
 ['HANSEN LIAM'],
 ['LEFT LEDGER'],
 ['NO NONSENSE'],
 ['TONY FOR WI'],
 ['MI S FUTURE'],
 ['PAGE FOR MO'],
 ['PETE CAMPOS'],
 ['MOUNTAINEER'],
 ['LARE FOR OH'],
 ['EASTERSEALS'],
 ['HOPE CHURCH'],
 ['JL RESEARCH'],
 ['THE MELLMAN'],
 ['WILANNE  KY'],
 ['WOOL NICOLE'],
 ['CAMMACK KAT'],
 ['WEGNER CPAS'],
 ['PALO LINELL'],
 ['COLEMAN FOR'],
 ['DARK CORNER'],
 ['WILLIAM FOR'],
 ['ELECT ETHAN'],
 ['BAIRD JAMES'],
 ['CARTER TROY'],
 ['COMER JAMES'],
 ['FRY RUSSELL'],
 ['KEAN THOMAS'],
 ['SOTO DARREN'],
 ['STEIL BRYAN'],
 ['SMART MEDIA'],
 ['ARNDT MEGAN'],
 ['BELL HAYLEY'],
 ['BOOTH PETER'],
 ['LEDDY PAIGE'],
 ['MIN KAITLYN'],
 ['RICE HALLIE'],
 ['COOK MAISIE'],
 ['CBT NUGGETS'],
 ['THE KC STAR'],
 ['FISCHER TEX'],
 ['HOLMES ADAM'],
 ['ROEMER BILL'],
 ['ALEX FOR AZ'],
 ['ALMA FOR AZ'],
 ['THE WA POST'],
 ['CORADO IRMA'],
 ['SNOW JULIAN'],
 ['FIEFIA DOUG'],
 ['ABA BANKPAC'],
 ['WOOD FOR IA'],
 ['JEFF WRIGHT'],
 ['THE MORNING'],
 ['HALLMARK MO'],
 ['PROFIT LINE'],
 ['GRAY ADAM C'],
 ['FAITH IN NY'],
 ['BLUE SENATE'],
 ['ROJAS DAVID'],
 ['BROWN EMILY'],
 ['DSPOLITICAL'],
 ['CUPAC OF NC'],
 ['CARLSON KEN'],
 ['HOPE FOR PA'],
 ['IA REALTORS'],
 ['PA REALTORS'],
 ['VT REALTORS'],
 ['MARKMESSMER'],
 ['COMMON GOOD'],
 ['PAUL FOR PA'],
 ['JACK FOR AG'],
 ['BENTZ CLIFF'],
 ['KIM SCHRIER', 'SCHRIER KIM'],
 ['CE4A ACTION'],
 ['CASTEN SEAN'],
 ['GARCIA CHUY'],
 ['SALERNO JOE'],
 ['GALL DANIEL'],
 ['ADDIS DAVID'],
 ['ALLEN JOANN'],
 ['ARVIG ALLEN'],
 ['BERGE NANCY'],
 ['BLACK MARTA'],
 ['BROWN ALLAN'],
 ['BRYAN DEBRA'],
 ['BUNN DANIEL'],
 ['BURGESS LEE'],
 ['BURKE ERWIN'],
 ['DAVIS MONTY'],
 ['DEATON BILL'],
 ['FRANCIS JAY'],
 ['HARMER JOHN'],
 ['HICKEY TROY'],
 ['LAPAN DAVID'],
 ['LUND GEORGE'],
 ['MCNIFF JOHN'],
 ['MORAN FRANK'],
 ['MORRIS ROSE'],
 ['NUPEN LARRY'],
 ['PINSON THEO'],
 ['POTTS CYRUS'],
 ['REDMAN RICK'],
 ['SMITH SCOTT'],
 ['SOLET JULIA'],
 ['STINE STEVE'],
 ['VAIL DELMAR'],
 ['WHITE KEITH'],
 ['WU SINGCHOU'],
 ['YATES LINDA'],
 ['SEATTLE CFO'],
 ['AHMAD REEMA'],
 ['HILL RACHEL'],
 ['LORD ZAKIYA'],
 ['LUCAS DARYL'],
 ['MELMAN ALEX'],
 ['OLSON TRACY'],
 ['STRONGER MO'],
 ['IWEN FOR NY'],
 ['STATE OF MI'],
 ['KBA PAC FOR'],
 ['ROTH FOR WI'],
 ['STATE OF IA'],
 ['CARR FOR GA'],
 ['KEEP KS RED'],
 ['ROSE FOR WV'],
 ['TEAM LAHOOD'],
 ['JOHN BOLTON'],
 ['CAPITAL ONE'],
 ['PHIL FOR VA'],
 ['GALT FOR SD'],
 ['JONES STEVE'],
 ['DOW REBECCA'],
 ['FREE INDEED'],
 ['HAYSTAQ DNA'],
 ['KECK FOR KY'],
 ['COST CURTIS'],
 ['TEICH ROGER'],
 ['BERGER PHIL'],
 ['HALL DESTIN'],
 ['PARTNERSHIP'],
 ['BABIN BRIAN'],
 ['DIRECT WINS'],
 ['LETT FOR OH'],
 ['TONE JE VON'],
 ['KING RACHEL'],
 ['DADE PHELAN', 'PHELAN DADE'],
 ['TRENT ASHBY'],
 ['CODY HARRIS'],
 ['ERIN FOR MN'],
 ['WARE FOR KS'],
 ['TONY FOR NY'],
 ['SALTON ADAM'],
 ['4C PARTNERS'],
 ['SALAME RYAN'],
 ['JEFF FOR AZ'],
 ['JUDY FOR AZ'],
 ['VOTE BOLICK', 'VOTE BOLLICK'],
 ['RILEY ANGEL'],
 ['AFT NM COPE'],
 ['PROJECT  WI'],
 ['BRAD FOR GA'],
 ['BRIANNA FOR'],
 ['BRIDGES FOR'],
 ['TOKYO JOE S'],
 ['ONE VA FUND'],
 ['ESTES ABBIE'],
 ['CHANG AARON'],
 ['ULRICH LISA'],
 ['STORYBLOCKS'],
 ['BACON KEVIN'],
 ['OTTO ROBERT'],
 ['MARCH ON MD'],
 ['HUFF ARISIA'],
 ['DARBY HOUSE'],
 ['HTTV DIRECT'],
 ['BUCY FOR TX'],
 ['WALL FOR WI'],
 ['NEW ECONOMY'],
 ['TEAM HUDSON'],
 ['AB DATA LTD'],
 ['COLE FOR VA'],
 ['CASE EDWARD'],
 ['HARDER JOSH'],
 ['LOFGREN ZOE'],
 ['RED CYPRESS'],
 ['JOHN FOR UT'],
 ['RINGCENTRAL'],
 ['BAKER SARAH'],
 ['PRESTA LISA', 'LISA PRESTA'],
 ['HENG ALISHA'],
 ['MSBILL INFO'],
 ['MAXIT CESAR'],
 ['BOYSENBERRY'],
 ['ALG POLLING'],
 ['KENNEDY TIM'],
 ['FLS CONNECT'],
 ['O2M DIGITAL'],
 ['ALEK FOR OR'],
 ['GOODMAN  KS'],
 ['MOSES CREEK'],
 ['APPLE STORE'],
 ['CANYON DEMS'],
 ['AMERICA NOW'],
 ['PEACH STATE'],
 ['MARY FOR IL'],
 ['HONOR BOUND'],
 ['BEN FOR LOU'],
 ['PURI SANJAY'],
 ['SAMI FOR OR'],
 ['HOLST KEVIN'],
 ['ROCKETREACH'],
 ['MASTERCLASS'],
 ['SKAGGS PHIL'],
 ['COSTA MARIN'],
 ['IHEARTMEDIA'],
 ['KEN BENNETT'],
 ['EILON ETHAN'],
 ['SCEUSA CARL'],
 ['TARA FOR WI'],
 ['BEN JERRY S'],
 ['ANDY NELSON'],
 ['KIEN TRUONG'],
 ['DIANA LIMON'],
 ['DONALD FINN'],
 ['MOIR MONICA'],
 ['PRIME MEDIA'],
 ['COEFFICIENT'],
 ['COOKE CELIA'],
 ['TARGETPOINT'],
 ['WENDI OLSON'],
 ['STUCKY LYNN'],
 ['FREEMAN BOB'],
 ['HEY DIGITAL'],
 ['IL NV  FUND'],
 ['TREASURE FL', 'TREASURER FL'],
 ['ROLLA GROUP'],
 ['BOND EVENTS'],
 ['MORGAN NICK'],
 ['STATES MADE'],
 ['DEHNE AMBER'],
 ['MEIER CHRIS'],
 ['HERRON LORI'],
 ['UROPARTNERS'],
 ['ORR ANGELIA'],
 ['GOMEZ DAISY'],
 ['SIMON TESSA'],
 ['WEPRIN SETH'],
 ['APH DIGITAL'],
 ['CIVIC SHOUT'],
 ['TUPLE LEGAL'],
 ['FIGHT RIGHT'],
 ['THE CITADEL'],
 ['RUSS FOR WI'],
 ['EIDEL JAMES'],
 ['MILLER ADAM'],
 ['MARK LEVINE', 'LEVINE MARK'],
 ['HOWE FOR ND'],
 ['TRANS CARGO'],
 ['BREWER ERIN'],
 ['MAY STANLEY'],
 ['WRIGHT LORI'],
 ['RAMIREZ FOR'],
 ['GREG FOR MT'],
 ['BINNALL LAW'],
 ['KRAMER ALEX'],
 ['SCOTT ELENA'],
 ['STATE OF NY'],
 ['MOMS FED UP'],
 ['NV ALLIANCE'],
 ['MASON CHRIS'],
 ['KUTZ FOR PA'],
 ['SAGE AGENTS'],
 ['ON THE MOVE'],
 ['LISA DEELEY'],
 ['CAFE ROTHEM'],
 ['NGUYEN LINH'],
 ['THE WHITLEY'],
 ['WOMEN2WOMEN'],
 ['BECK KELSEY'],
 ['ZUCKER LILA'],
 ['PYLE MARISA'],
 ['FACUNDO EVA'],
 ['KNAPP JESSE'],
 ['KOZUCH MARK'],
 ['PIVOT GROUP'],
 ['CAPITOL ONE'],
 ['MATT FOR MT'],
 ['HOEFEN JOHN'],
 ['RISE UNITED'],
 ['KENT FOR WV'],
 ['FREEDOM PAC'],
 ['ZAIDI LAELA'],
 ['PROGRESSNOW'],
 ['SMITH CARLA'],
 ['AMIDON ERIC'],
 ['BEST BERNIE'],
 ['HUNT WESLEY'],
 ['LOUIS COREA'],
 ['DEM TURNOUT'],
 ['KINDER ELLA'],
 ['COES SAMUEL'],
 ['FULMER EVAN'],
 ['ZUZULA ZANE'],
 ['BANKER MIRA'],
 ['LEE JACKSON'],
 ['BELL RODNEY'],
 ['GEORGE RYAN'],
 ['HAMLIN LUKE'],
 ['BONAR ELLEN'],
 ['GWYN JAYLEN'],
 ['GARNER NIYA'],
 ['MERY CHIARA'],
 ['MATSON SETH'],
 ['GALE WESTON'],
 ['PEREZ ALEXA'],
 ['PRIGUN JOHN'],
 ['HOULE LACEY'],
 ['NADA MARIAM'],
 ['EGNER NANCY'],
 ['ARNOLD LEAH'],
 ['SMILEY SETH'],
 ['MUNOZ NANCY'],
 ['MORREN TARA'],
 ['BARBEE MARY'],
 ['HUNT SIERRA'],
 ['ADAMS SCOTT'],
 ['PETROS MARY'],
 ['PEREZ DANNY'],
 ['DROBA AIMEE'],
 ['GARDNER IAN'],
 ['BROWN SIMON'],
 ['KELLY CONOR'],
 ['HALL CAROLE'],
 ['MOSER JACOB'],
 ['RIOS DANIEL'],
 ['LETT BRENDA'],
 ['BUNDAY KARL'],
 ['LOURIE NOAH'],
 ['BYRD TYRESE'],
 ['RIVAS ALDEN'],
 ['KAST SAMUEL'],
 ['ALLEN TYLER'],
 ['WATERS NOAH'],
 ['CADY MONICA'],
 ['SYED ZARINA'],
 ['TAYLOR JOEL'],
 ['KELLY GRACE'],
 ['MARR HUDSON'],
 ['GRANT KELLI'],
 ['ROHRER LEAH'],
 ['MILLAR SARA'],
 ['RUNGTA RHEA'],
 ['DECKER ZOEY'],
 ['ZIOBRON ZOE'],
 ['UNITY FIRST'],
 ['MD S FUTURE'],
 ['ZUMBACH DAN'],
 ['SIGNAL HIRE'],
 ['RESTORATION'],
 ['BECK FOR MO'],
 ['ROUND WORLD'],
 ['MO HERITAGE'],
 ['JACK BACHUS'],
 ['CARTER EARL'],
 ['GARCIA MIKE'],
 ['LUCAS FRANK'],
 ['PALMER GARY'],
 ['SMITH JASON'],
 ['WEBER RANDY'],
 ['STEWARDSHIP'],
 ['MEGAN BARRY'],
 ['GARY FOR WY'],
 ['DAVIS JOYCE'],
 ['PAC A PUNCH'],
 ['NETA COLLAB'],
 ['SYKES DEREK'],
 ['SHANK AIDAN'],
 ['OR BEVERAGE'],
 ['CORNYN JOHN'],
 ['CAMACHO FOR'],
 ['TISHA MAURO'],
 ['TAYLOR GAIR'],
 ['JACOBS SARA'],
 ['LOPEZ VICKI', 'LOPEZ VICKIE'],
 ['SIMON COREY'],
 ['MURT FOR DJ'],
 ['AR TRUCKING'],
 ['HESHAM NOUR'],
 ['TABLER JAKE'],
 ['LELA ALSTON'],
 ['BIRD BRENNA'],
 ['JOSH FOR PA'],
 ['HEARTDOCPAC'],
 ['GRANT CLIVE'],
 ['ORGANIZE AZ'],
 ['BERKE FARAH'],
 ['TONG SAMUEL'],
 ['BIRD FOR WI'],
 ['KENMORE AIR'],
 ['MCNEARY ANN'],
 ['ZULLO FRANK'],
 ['PARKER RYAN'],
 ['ZUDDU DARIO'],
 ['RICE ANDREW'],
 ['OWENS NANCY'],
 ['WEBER DYLAN'],
 ['BRASE BRIAN'],
 ['COADY CONOR'],
 ['LAVIN KATIE'],
 ['CROFT KAREN'],
 ['BEARD BECKY'],
 ['LER BRANDON', 'LEHR BRANDON'],
 ['NOVAK SARAH'],
 ['LEVIATE AIR'],
 ['ACTUM UK OP'],
 ['FIGHTIN 9TH'],
 ['1HOOD POWER'],
 ['NATE FOR FL'],
 ['WASHBANKPAC'],
 ['LERE FOR OH'],
 ['TEAM MOONEY'],
 ['GORDON LISA'],
 ['SEVEN LAMPS'],
 ['LOPEZ SONIA'],
 ['PA TOGETHER', 'TOGETHER PA'],
 ['PROGRESS RI'],
 ['HAMEDAH ABE'],
 ['MURPHY GREG'],
 ['IRON LADIES'],
 ['BELMONT  UT'],
 ['OWEN FOR UT', 'OWENS FOR UT'],
 ['VOTE VIVIAN'],
 ['LEGENDZ BBQ'],
 ['TACO CABANA'],
 ['THE AZ CAFE'],
 ['WHATABURGER'],
 ['TEAM BUTLER'],
 ['EGEMEN METE'],
 ['BENTALL NIA'],
 ['OCHOA LAURA'],
 ['SCOTT LARRY'],
 ['PROGRESS MI'],
 ['MAYNE RILEY'],
 ['CLARE LOCKE'],
 ['CLOCKIFY ME'],
 ['LEE MATTHEW'],
 ['LIBERAL ART'],
 ['TESFU SOFIA'],
 ['TESS STRAND'],
 ['GARCIA RENE'],
 ['CHAVEZ ALMA'],
 ['DANG ANNE T'],
 ['DO PHUONG H'],
 ['HUYNH TRISH'],
 ['MORENO OMAR'],
 ['NGUYEN VU T'],
 ['TRINH KIM B'],
 ['VU VINH KIM'],
 ['MAXIMUM SPL'],
 ['JURGENS GAY'],
 ['ZEHR FOR VA'],
 ['MOOK ROBERT'],
 ['THE DEL BAR'],
 ['THE PALAZZO'],
 ['NEW SHERIFF'],
 ['BOWIE SUSAN'],
 ['STATE OF FL'],
 ['MOORE DAVID'],
 ['HUNT FOR NC'],
 ['MARTIN GREG'],
 ['KYLE FOSTER'],
 ['MELLEN JAKE'],
 ['PUGH FOR MI'],
 ['KEIR FOR AG'],
 ['TAYLOR DALE'],
 ['BACK AUSTIN'],
 ['CASSIL NOAH'],
 ['MUNIZ JESSE'],
 ['YADAV TISYA'],
 ['YANG AMARIS'],
 ['YANG CALVIN'],
 ['ZWEBTI RAMI'],
 ['GUPTA YAJAT'],
 ['KELLY ETHAN'],
 ['TABAIE MARY'],
 ['YOUNG CHRIS'],
 ['BRAUN KEITH'],
 ['TX MAJORITY'],
 ['RESIST THIS'],
 ['MURPHY JOHN'],
 ['OLIVIA ROSE'],
 ['TAPIA PETER'],
 ['KELLY PRESS'],
 ['AZ REPUBLIC'],
 ['NEWSLIBRARY'],
 ['WISPOLITICS'],
 ['HODO EVENTS'],
 ['PEREZ SONIA'],
 ['KERR JOSEPH'],
 ['PRESS PRINT'],
 ['PLATI ALICE'],
 ['FINK FOR PA'],
 ['AARON SQUEO'],
 ['JERRY YOUNG'],
 ['BERG FOR MN'],
 ['FAIRNESS PA'],
 ['BILL WESLEY'],
 ['PETERS GARY'],
 ['JACE FOR TX'],
 ['NINA FOR PA'],
 ['BERG FOR ND'],
 ['RE STRATEGY'],
 ['RURAL AM FM'],
 ['PROGRESSIVE'],
 ['BLUEOC LIVE'],
 ['ED GONZALES'],
 ['KIM YONG HO'],
 ['NORTH SHORE'],
 ['EKLUND JOHN'],
 ['KNAPP CHRIS'],
 ['OLSEN JARED'],
 ['REED JACK F'],
 ['WILSON ADAM'],
 ['BLACK ANNIE'],
 ['ELDA FOR AZ'],
 ['MAKO FOR PA'],
 ['BERRY GERRY'],
 ['CLARK BRIAN'],
 ['DELEO SHAWN'],
 ['GEE GREGORY'],
 ['LONG JOSEPH'],
 ['JUST REFORM'],
 ['WMA MINEPAC'],
 ['6TYSIXMEDIA'],
 ['STREET ZONE'],
 ['COX STANLEY'],
 ['FRAMEBRIDGE'],
 ['WAY TAHESHA'],
 ['FETAW MIELA'],
 ['NOMAD MEDIA'],
 ['PIZZO JASON'],
 ['JOBS GROWTH'],
 ['CNP SERVICE'],
 ['BERNAL CRUZ'],
 ['GRANGER KAY'],
 ['BAUM FOR MT'],
 ['SCHEXNAYDER'],
 ['JULION MACK'],
 ['KHOP SHOOTS'],
 ['SCHIFF ADAM'],
 ['SIMON STEVE'],
 ['TAJ EXPRESS'],
 ['FRAHM ILENE'],
 ['MACLIN RYAN'],
 ['HAWKINS LEE'],
 ['POWELL ALAN'],
 ['NH PEOPLE S'],
 ['QML FOR PHL'],
 ['LOPEZ ANITA'],
 ['WOMAN UP CA'],
 ['CHS BSO JFC'],
 ['DEBI SCAGGS'],
 ['BACARDI USA'],
 ['ID S FUTURE'],
 ['AL FIRSTPAC'],
 ['MIKE FOR VT'],
 ['BAY ARMOURY'],
 ['HART FOR WV'],
 ['TIFFANY TOM'],
 ['THOMAS KOPP'],
 ['SMITH KEMBA'],
 ['LAWLER MIKE'],
 ['CLIO AWARDS'],
 ['SMALL CHRIS'],
 ['NOVA BIZPAC'],
 ['REED JOHN F'],
 ['GOOCH STEVE'],
 ['KUCHAR BILL'],
 ['CLEO FIELDS'],
 ['AL FAMILIES'],
 ['DAN PAFIRST'],
 ['ONWARD FUND'],
 ['ALFOND JOAN'],
 ['BASS ROBERT'],
 ['MCIVER BILL'],
 ['DIETZ SUSAN'],
 ['ROTH STEVEN'],
 ['KIRBY DAVID'],
 ['ROSE LESLIE'],
 ['BRADY MARNE'],
 ['CITY STONES'],
 ['LEADER JESS'],
 ['REACH RIGHT'],
 ['FUNDRAISING'],
 ['LECOMPTE ED'],
 ['WARNER TODD'],
 ['GALDO MARIA'],
 ['MENDIVE  ID'],
 ['THE H HOTEL'],
 ['HASHEM MARK'],
 ['SAIKI SCOTT'],
 ['LANGER ANNA'],
 ['NUNN FOR IA'],
 ['EDWARDS JAY'],
 ['HUSTED JOHN'],
 ['HANSEN BETH'],
 ['HOGAN LARRY'],
 ['PUBLIC WISE'],
 ['CUSTOMER IO'],
 ['HANDWRYTTEN'],
 ['INFLUENCITY'],
 ['BEAM DENTAL'],
 ['SABIO MAGAT'],
 ['HAYNES SEAN'],
 ['IN BUILDERS'],
 ['SC BUILDERS'],
 ['RG2 TUESDAY'],
 ['ASHBY LAW P'],
 ['NO EASY DAY'],
 ['BLOUT ASTIN'],
 ['BROWN SCOTT'],
 ['BROWN SIERA'],
 ['CANTOS ABEL'],
 ['DOBY KHAYLA'],
 ['TENG CARTER'],
 ['KIGGANS JEN'],
 ['SUREPAYROLL'],
 ['TEAM  STATE'],
 ['TOKUDA JILL'],
 ['KILEY KEVIN'],
 ['TINA FOR OR'],
 ['REA OF HOPE'],
 ['WERNE MARLA'],
 ['KING FOR TX'],
 ['FOX WHITNEY', 'WHITNEY FOX'],
 ['STEWART RON'],
 ['ERNST LEGAL'],
 ['KAPWING PRO'],
 ['MARKMONITOR'],
 ['ENVISION NY'],
 ['FERN FOR SD'],
 ['SOLOMON FOR'],
 ['MURRILL LIZ'],
 ['BANKS LLOYD'],
 ['FOSTER ERIC'],
 ['MOORE RILEY'],
 ['HALL FOR MS'],
 ['AMO GABRIEL'],
 ['LARSON JOHN'],
 ['GETZUG COBY'],
 ['GALVIN BILL'],
 ['BREW GARDEN'],
 ['DIPALMA LOU'],
 ['SOUTH CREEK'],
 ['BARCA PETER'],
 ['TRAHAN LORI'],
 ['SABB RONNIE'],
 ['CONE EDWARD'],
 ['JULIE MENIN'],
 ['FOSS AUSTIN'],
 ['AMY VERLAIC'],
 ['MENDEZ JOSE'],
 ['COREAS EDIS'],
 ['JOYA HECTOR'],
 ['KADULI YVES'],
 ['MOXIE MEDIA'],
 ['LEON AMARIS'],
 ['SMITH LARRY'],
 ['THE JENKINS'],
 ['PRIMO WATER'],
 ['EXTRA SEVEN'],
 ['HULSE AMBER'],
 ['LEVIN TYLER'],
 ['RED COMPASS'],
 ['RESES JACOB'],
 ['ELISABETTAS'],
 ['PDQ CHICKEN'],
 ['BEAN FOR FL'],
 ['HUNT FOR TX'],
 ['KEAN FOR NJ'],
 ['LUNA FOR FL'],
 ['THE OORBEEK'],
 ['FREEDOMFEST'],
 ['DEE S HOUSE'],
 ['PERRY WENDY'],
 ['HAGAN SCOTT'],
 ['SERLIN NATE'],
 ['TURNER ABBY'],
 ['I BACK JACK'],
 ['HOSPITALITY'],
 ['MARY FOR VA'],
 ['SIEGEL MARK'],
 ['DRIVER COLE'],
 ['JIMMY JOHNS', 'JIMMY JOHN S'],
 ['PEARCE TRUE'],
 ['ATLANTA DSA'],
 ['NEWMAN JOSH'],
 ['GABARRA AMY'],
 ['TOASTED OWL'],
 ['SCULLY NORA'],
 ['CARSON JOHN'],
 ['GRINER CLAY'],
 ['PARSONS DON'],
 ['REEVES MATT'],
 ['REED ASHLEY'],
 ['FLORES PETE'],
 ['BRIAN BLAKE'],
 ['LEFT RISING'],
 ['EPP MELISSA'],
 ['BANNER LIFE'],
 ['THE MARKHAM'],
 ['MARY FOR ID'],
 ['U S CHAMBER'],
 ['MEDINA JOSE'],
 ['MIKE FOR MT'],
 ['DARYL SMITH'],
 ['HOEVEN JOHN'],
 ['TX TOOLBELT'],
 ['MCMIKLE JOE'],
 ['MOTHER WOLF'],
 ['SEVEN HILLS'],
 ['VALDEZ LUPE'],
 ['MEDIA GROUP'],
 ['WALKER BOYD'],
 ['LOCKE DAVID'],
 ['REIGER LYNN'],
 ['FELAG WALLY'],
 ['GALLO HANNA'],
 ['MT BUSINESS'],
 ['KELLY DAVID'],
 ['SCOTT BOBBY'],
 ['TEAM  SLATE'],
 ['XAVIER YDSA'],
 ['ELECT VANEL'],
 ['TEAM SIMCHA'],
 ['WAXHAM REED'],
 ['FREEHAND NY'],
 ['HORN HAYDEN'],
 ['OUMA PHILIP'],
 ['THE HERSHEY'],
 ['ELECT JULIA'],
 ['JAYME DAVIS'],
 ['TEAM CRAMER'],
 ['ALLEN AVERY'],
 ['ANSARI ASNA'],
 ['BRAND ILONA'],
 ['BURKE JAIRA'],
 ['FAGAN JAYNE'],
 ['GELLER SETH'],
 ['GORDON CODY'],
 ['ISAAC EMILY'],
 ['KUGLER SARA'],
 ['PERCY CHRIS'],
 ['REDDY KEDAR'],
 ['SCULLY KATE'],
 ['SHAHID SANA'],
 ['DJANG JASON'],
 ['HARPER JOHN'],
 ['HOLMES MIMI'],
 ['NASH TERESA'],
 ['WALIS MANDY'],
 ['YEE KA PING'],
 ['BALLOTREADY'],
 ['WALI BASHAR'],
 ...]

In [34]:
# Isolate groups with more than one value
groups_n_2 = [group for group in groups if len(group)>1]
len(groups_n_2)

1619

In [35]:
# Isolate names that did not have any matches given the threshold 
groups_n_1 = [group for group in groups if len(group)==1]
len(groups_n_1)

32750

In [36]:
# For groups >=2, assign a group name that is equal to the shortest string in the group. This group name will be used to map payees to a vendor 
mapping = {}

# Assign a group name to the groups to use in vendor definition 
for ii in groups_n_2:
    df = pd.DataFrame({'item': ii})
    df['st_len'] = df['item'].apply(lambda s: len(s))
    df = df.sort_values('st_len')
    name = df.iloc[0,0]
    mapping[name] = ii

mapping

{'VA BANKPAC': ['VA BANKPAC', 'VBA BANKPAC'],
 'A BOLDER FL': ['A BOLDER FL', 'A BOULDER FL'],
 'JOHN CURTIS': ['JOHN CURTIS', 'CURTIS JOHN'],
 'DEBONA JOHN': ['DEBONA JOHN', 'JOHN DEBONA'],
 'HALL STEVEN': ['HALL STEVEN', 'STEVEN HALL'],
 'JACKY ROSEN': ['JACKY ROSEN', 'ROSEN JACKY'],
 'ANGIE CRAIG': ['ANGIE CRAIG', 'CRAIG ANGIE'],
 'MOORE BLAKE': ['MOORE BLAKE', 'MOORRE BLAKE'],
 'BERLINROSEN': ['BERLINROSEN', 'BERLIN ROSEN'],
 'KIM SCHRIER': ['KIM SCHRIER', 'SCHRIER KIM'],
 'DADE PHELAN': ['DADE PHELAN', 'PHELAN DADE'],
 'VOTE BOLICK': ['VOTE BOLICK', 'VOTE BOLLICK'],
 'PRESTA LISA': ['PRESTA LISA', 'LISA PRESTA'],
 'TREASURE FL': ['TREASURE FL', 'TREASURER FL'],
 'MARK LEVINE': ['MARK LEVINE', 'LEVINE MARK'],
 'LOPEZ VICKI': ['LOPEZ VICKI', 'LOPEZ VICKIE'],
 'LER BRANDON': ['LER BRANDON', 'LEHR BRANDON'],
 'PA TOGETHER': ['PA TOGETHER', 'TOGETHER PA'],
 'OWEN FOR UT': ['OWEN FOR UT', 'OWENS FOR UT'],
 'FOX WHITNEY': ['FOX WHITNEY', 'WHITNEY FOX'],
 'JIMMY JOHNS': ['JIMMY JOHNS', 'JIMMY JOHN S'],
 'NOBLET TONY': ['NOBLET TONY', 'NOBLETT TONY'],
 'LALOTA NICK': ['LALOTA NICK', 'NICK LALOTA'],
 'DONNIE BELL': ['DONNIE BELL', 'BELL DONNIE'],
 'DAVID SMITH': ['DAVID SMITH', 'SMITH DAVID'],
 'OKAL ELAINE': ['OKAL ELAINE', 'OKAL ELALINE'],
 'NEWHOUSE DAN': ['NEWHOUSE DAN', 'DAN NEWHOUSE'],
 'WILLS FOR IA': ['WILLS FOR IA', 'FOR IA WILLS'],
 'EMILIA SYKES': ['EMILIA SYKES', 'SYKES EMILIA'],
 'LAURA GILLEN': ['LAURA GILLEN', 'GILLEN LAURA'],
 'MARY PELTOLA': ['MARY PELTOLA', 'PELTOLA MARY'],
 'JAHANA HAYES': ['JAHANA HAYES', 'HAYES JAHANA'],
 'SUSAN ALTMAN': ['SUSAN ALTMAN', 'ALTMAN SUSAN'],
 'LAHOOD DARIN': ['LAHOOD DARIN', 'LAHOOD DARRIN'],
 'PATTY MURRAY': ['PATTY MURRAY', 'MURRAY PATTY'],
 'LUTTRELL KEN': ['LUTTRELL KEN', 'KEN LUTTRELL'],
 'KELLY FOR HD': ['KELLY FOR HD', 'KELLEY FOR HD'],
 'MARK HEINITZ': ['MARK HEINITZ', 'HEINITZ MARK'],
 'KUEMPEL JOHN': ['KUEMPEL JOHN', 'JOHN KUEMPEL'],
 'GRAHAM DAVID': ['GRAHAM DAVID', 'DAVID GRAHAM'],
 'ROSS DEBORAH': ['ROSS DEBORAH', 'DEBORAH ROSS'],
 'MFUME KWEISI': ['MFUME KWEISI', 'KWEISI MFUME'],
 'AGUILAR PETE': ['AGUILAR PETE', 'PETE AGUILAR'],
 'AUSTN FOR MT': ['AUSTN FOR MT', 'AUSTIN FOR MT'],
 'BARRASSO JOH': ['BARRASSO JOH', 'BARRASSO JOHN'],
 'HUGHES BRYAN': ['HUGHES BRYAN', 'BRYAN HUGHES'],
 'G STRATEGIES': ['G STRATEGIES', 'RG STRATEGIES'],
 'JARED HAGERT': ['JARED HAGERT', 'HAGERT JARED'],
 'SOMMER MARTI': ['SOMMER MARTI', 'SOMMER MARTIN'],
 'IM FOR WATRO': ['IM FOR WATRO', 'I M FOR WATRO'],
 'MAGGIES LIST': ['MAGGIES LIST', 'MAGGIE S LIST'],
 'RANDAL EMILY': ['RANDAL EMILY', 'EMILY RANDALL', 'RANDALL EMILY'],
 'POWELL STEVEN': ['POWELL STEVEN', 'STEVEN POWELL'],
 'DC HEALTHLINK': ['DC HEALTHLINK', 'DC HEALTH LINK'],
 'TAMMY BALDWIN': ['TAMMY BALDWIN', 'BALDWIN TAMMY'],
 'KIRSTEN ENGEL': ['KIRSTEN ENGEL', 'ENGEL KIRSTEN'],
 'AMY KLOBUCHAR': ['AMY KLOBUCHAR', 'KLOBUCHAR AMY'],
 'MONICA TRANEL': ['MONICA TRANEL', 'TRANEL MONICA'],
 'REBECCA COOKE': ['REBECCA COOKE', 'COOKE REBECCA'],
 'JULIE JOHNSON': ['JULIE JOHNSON', 'JOHNSON JULIE'],
 'COMMERCE BANK': ['COMMERCE BANK', 'BANK COMMERCE'],
 'TEAM MORRISEY': ['TEAM MORRISEY', 'TEAM MORRISSEY'],
 'MCNEIL FOR PA': ['MCNEIL FOR PA', 'MCNEILL FOR PA'],
 'CENTER UNITED': ['CENTER UNITED', 'UNITED CENTER'],
 'MCNEIL ROBERT': ['MCNEIL ROBERT', 'MCNEILY ROBERT'],
 'ERNEST BAILES': ['ERNEST BAILES', 'BAILES ERNEST'],
 'DEWAYNE BURNS': ['DEWAYNE BURNS', 'BURNS DEWAYNE'],
 'OJEDA RICHARD': ['OJEDA RICHARD', 'RICHARD OJEDA'],
 'DUSTY JOHNSON': ['DUSTY JOHNSON', 'JOHNSON DUSTY'],
 'DYESS GABRIEL': ['DYESS GABRIEL', 'DYESSS GABRIEL'],
 'CTE PETE LAND': ['CTE PETE LAND', 'CTE PETER LAND'],
 'HARLAND CLARK': ['HARLAND CLARK', 'HARLAND CLARKE'],
 'PEOPLES VOICE': ['PEOPLES VOICE', 'PEOPLE S VOICE'],
 'OZINGA FOR IL': ['OZINGA FOR IL', 'ORZINGA FOR IL'],
 'MCGARVEY TONY': ['MCGARVEY TONY', 'TONY MCGARVEY'],
 'SPRAGE FOR OH': ['SPRAGE FOR OH', 'SPRAGUE FOR OH'],
 'THOMPSON GLEN': ['THOMPSON GLEN', 'THOMPSON GLENN', 'GLENN THOMPSON'],
 'MALCOM FOR PA': ['MALCOM FOR PA', 'MALCOLM FOR PA'],
 'BEN KOPPELMAN': ['BEN KOPPELMAN', 'KOPPELMAN BEN'],
 'FISHER FOR OH': ['FISHER FOR OH', 'FISCHER FOR OH'],
 'EARLS RICHARD': ['EARLS RICHARD', 'EARLES RICHARD'],
 'JASMIN FOR US': ['JASMIN FOR US', 'JASMINE FOR US'],
 'ONEPA VICTORY': ['ONEPA VICTORY', 'ONE PA VICTORY'],
 'TREASURE STATE': ['TREASURE STATE', 'TREASURER STATE'],
 'EVENTS PERELLA': ['EVENTS PERELLA', 'PERELLA EVENTS'],
 'LATEEFAH SIMON': ['LATEEFAH SIMON', 'SIMON LATEEFAH'],
 'YADIRA CARAVEO': ['YADIRA CARAVEO', 'CARAVEO YADIRA'],
 'ANDREA SALINAS': ['ANDREA SALINAS', 'SALINAS ANDREA'],
 'LAURA FRIEDMAN': ['LAURA FRIEDMAN', 'FRIEDMAN LAURA'],
 'SHARICE DAVIDS': ['SHARICE DAVIDS', 'DAVIDS SHARICE'],
 'MARIA CANTWELL': ['MARIA CANTWELL', 'CANTWELL MARIA'],
 'KELLY MORRISON': ['KELLY MORRISON', 'MORRISON KELLY'],
 'CONNOLLY GERRY': ['CONNOLLY GERRY', 'GERRY CONNOLLY'],
 'JOHNSON GLORIA': ['JOHNSON GLORIA', 'GLORIA JOHNSON'],
 'GARY VANDEAVER': ['GARY VANDEAVER', 'VANDEAVER GARY'],
 'STEPHANIE BICE': ['STEPHANIE BICE', 'BICE STEPHANIE'],
 'HOTT FOR HOUSE': ['HOTT FOR HOUSE', 'HIOTT FOR HOUSE'],
 'SULLIVAN JARED': ['SULLIVAN JARED', 'JARED SULLIVAN'],
 'SLOTKIN ELISSA': ['SLOTKIN ELISSA', 'ELISSA SLOTKIN'],
 'JERRY R TURNER': ['JERRY R TURNER', 'TURNER JERRY R'],
 'SINCLAIR FOR IA': ['SINCLAIR FOR IA', 'FOR IA SINCLAIR'],
 'RECLAIM AMERICA': ['RECLAIM AMERICA', 'RECLAIM AMERICAN'],
 'HARRIET HAGEMAN': ['HARRIET HAGEMAN', 'HAGEMAN HARRIET'],
 'CAMPAIGNMONITOR': ['CAMPAIGNMONITOR', 'CAMPAIGN MONITOR'],
 'JAY DEAN FOR TX': ['JAY DEAN FOR TX', 'DEAN FOR TX JAY'],
 'DE BECKER GAVIN': ['DE BECKER GAVIN', 'GAVIN DE BECKER'],
 'STEVENS LINDSAY': ['STEVENS LINDSAY', 'LINDSAY STEVENS'],
 'JUNCEAU MARTIAL': ['JUNCEAU MARTIAL', 'MARTIAL JUNCEAU'],
 'UNDERWOOD LAURE': ['UNDERWOOD LAURE',
  'LAUREN UNDERWOOD',
  'UNDERWOOD LAUREN'],
 'JANELLE STELSON': ['JANELLE STELSON', 'STELSON JANELLE'],
 'NIKKI BUDZINSKI': ['NIKKI BUDZINSKI', 'BUDZINSKI NIKKI'],
 'TOXCLAIR FOR TX': ['TOXCLAIR FOR TX', 'TROXCLAIR FOR TX'],
 'CORY FOR SENATE': ['CORY FOR SENATE', 'COREY FOR SENATE'],
 'HUMPHREY FOR OH': ['HUMPHREY FOR OH', 'HUMPHREY FOR OHI'],
 'ADRIENNE FOR NY': ['ADRIENNE FOR NY', 'ADRIENNE FOR NYC'],
 'STONE FOR HOUSE': ['STONE FOR HOUSE', 'FOR HOUSE STONE'],
 'JD FOR ARLIGTON': ['JD FOR ARLIGTON', 'JD FOR ARLINGTON'],
 'KANE FOR SENATE': ['KANE FOR SENATE', 'KAINE FOR SENATE'],
 'PLUMLEY MELISSA': ['PLUMLEY MELISSA', 'MELISSA PLUMLEY'],
 'JUBELIER DANIEL': ['JUBELIER DANIEL', 'JUBELIRER DANIEL'],
 'HAGER FOR HOUSE': ['HAGER FOR HOUSE', 'HAGERT FOR HOUSE'],
 'FOWLER COMITTEE': ['FOWLER COMITTEE', 'FOWLER COMMITTEE'],
 'KELLY FOR HOUSE': ['KELLY FOR HOUSE', 'KELLEY FOR HOUSE'],
 'COMMITTEE TRUMP': ['COMMITTEE TRUMP', 'TRUMP  COMMITTEE'],
 'BROWN SHONTEL M': ['BROWN SHONTEL M', 'BROWN M SHONTEL'],
 'JONATHAN WARREY': ['JONATHAN WARREY', 'WARREY JONATHAN'],
 'AMERICA REVIVAL': ['AMERICA REVIVAL', 'AMERICAN REVIVAL'],
 'BOOKS A MILLION': ['BOOKS A MILLION', 'BOOKS A MILLIONS'],
 'KAT FOR CONGRESS': ['KAT FOR CONGRESS', 'KATE FOR CONGRESS'],
 'LETS GET TO WORK': ['LETS GET TO WORK', 'LET S GET TO WORK'],
 'KLOBUCHAR FOR MN': ['KLOBUCHAR FOR MN',
  'FOR MN KLOBUCHAR',
  'KLOBUCHARD FOR MN'],
 'DESPOSITO FOR NY': ['DESPOSITO FOR NY', 'D ESPOSITO FOR NY'],
 'WATERS FOR HOUSE': ['WATERS FOR HOUSE', 'WALTERS FOR HOUSE'],
 'KEYSTONE AMERICA': ['KEYSTONE AMERICA', 'KEYSTONE AMERICAN'],
 'HILLARY SCHOLTEN': ['HILLARY SCHOLTEN', 'SCHOLTEN HILLARY'],
 'HATATHLIE FOR AZ': ['HATATHLIE FOR AZ', 'HATATHALIE FOR AZ'],
 'CROCKETT JASMINE': ['CROCKETT JASMINE', 'JASMINE CROCKETT'],
 'BAKER FOR SENATE': ['BAKER FOR SENATE', 'BARKER FOR SENATE'],
 'GENE WU CAMPAIGN': ['GENE WU CAMPAIGN', 'WU CAMPAIGN GENE'],
 'JEFF LARE FOR OH': ['JEFF LARE FOR OH', 'LARE FOR OH JEFF'],
 'GONZALEZ VICENTE': ['GONZALEZ VICENTE', 'GONZALEZ VINCENTE'],
 'DAVE FERN FOR SD': ['DAVE FERN FOR SD', 'DAVE FERN FOR SD2'],
 'GRACE LEE FOR NY': ['GRACE LEE FOR NY', 'GRACE LEE FOR NYC'],
 'SAMUEL CREEKMORE': ['SAMUEL CREEKMORE', 'CREEKMORE SAMUEL'],
 'CITIZEN FOR ALEC': ['CITIZEN FOR ALEC', 'CITIZENS FOR ALEC'],
 'TOWNPLACE SUITES': ['TOWNPLACE SUITES', 'TOWNEPLACE SUITES'],
 'WHITESIDE GEORGE': ['WHITESIDE GEORGE', 'WHITESIDES GEORGE'],
 'LACY HULL FOR TX': ['LACY HULL FOR TX',
  'LACEY HULL FOR TX',
  'HULL FOR TX LACEY'],
 'ANDREW MARSCHALL': ['ANDREW MARSCHALL', 'MARSCHALL ANDREW'],
 'BARNES AND NOBLE': ['BARNES AND NOBLE', 'BARNES AND NOBLES'],
 'FRIENDS OF ZURAY': ['FRIENDS OF ZURAY', 'FRIENDS OF ZURAYA'],
 'WICKER FOR SENATE': ['WICKER FOR SENATE', 'ZWICKER FOR SENATE'],
 'CASE FOR CONGRESS': ['CASE FOR CONGRESS', 'CASEY FOR CONGRESS'],
 'AMERICAN SECURITY': ['AMERICAN SECURITY', 'AMERICANS  SECURITY'],
 'COLBRI COLLECTIVE': ['COLBRI COLLECTIVE', 'COLIBRI COLLECTIVE'],
 'OSBORN FOR SENATE': ['OSBORN FOR SENATE', 'OSBORNE FOR SENATE'],
 'ANGELA ALSOBROOKS': ['ANGELA ALSOBROOKS', 'ALSOBROOKS ANGELA'],
 'VOTE FOR KATHLEEN': ['VOTE FOR KATHLEEN', 'VOTE FOR KATHELEEN'],
 'HARSHBARGER DIANA': ['HARSHBARGER DIANA', 'DIANA HARSHBARGER'],
 'PEOPLE FOR PARKER': ['PEOPLE FOR PARKER', 'PEOPLLE FOR PARKER'],
 'KRIS MAYES FOR AZ': ['KRIS MAYES FOR AZ', 'MAYES FOR AZ KRIS'],
 'HERELL FOR SENATE': ['HERELL FOR SENATE', 'HERRELL FOR SENATE'],
 'DILLON FOR SENATE': ['DILLON FOR SENATE', 'DILLION FOR SENATE'],
 'MAGGIE GOODLANDER': ['MAGGIE GOODLANDER', 'GOODLANDER MAGGIE'],
 'JON HUSTED FOR OH': ['JON HUSTED FOR OH', 'JOHN HUSTED FOR OH'],
 'DFL SENATE CAUCUS': ['DFL SENATE CAUCUS', 'SENATE DFL CAUCUS'],
 'GARY GATES FOR TX': ['GARY GATES FOR TX', 'GATES FOR TX GARY'],
 'TOM LEEK CAMPAIGN': ['TOM LEEK CAMPAIGN', 'TOM LEEK  CAMPAIGN'],
 'SANDER FOR SENATE': ['SANDER FOR SENATE', 'SANDERS FOR SENATE'],
 'LUNGREN FOR HOUSE': ['LUNGREN FOR HOUSE', 'LUNDGREN FOR HOUSE'],
 'FRAZIER FREDERICK': ['FRAZIER FREDERICK', 'FREDERICK FRAZIER'],
 'DIAZ BALART MARIO': ['DIAZ BALART MARIO', 'DIAZ BARLART MARIO'],
 'PRESTIGE PRINTING': ['PRESTIGE PRINTING', 'PRESSTIGE PRINTING'],
 'BENNET FOR SENATE': ['BENNET FOR SENATE', 'BENNETT FOR SENATE'],
 'CARL FOR CONGRESS': ['CARL FOR CONGRESS', 'CAROL FOR CONGRESS'],
 'ANN MCLANE KUSTER': ['ANN MCLANE KUSTER', 'KUSTER ANN MCLANE'],
 'MI PEOPLES CHOICE': ['MI PEOPLES CHOICE', 'MI PEOPLE S CHOICE'],
 'ALLYSON DAMIKOLAS': ['ALLYSON DAMIKOLAS', 'DAMIKOLAS ALLYSON'],
 'RISCH FOR BISMARK': ['RISCH FOR BISMARK', 'RISCH FOR BISMARCK'],
 'PAUL DYSON FOR TX': ['PAUL DYSON FOR TX', 'DYSON FOR TX PAUL'],
 'LABAT FOR SHERIFF': ['LABAT FOR SHERIFF', 'LABAT FOR SHERRIFF'],
 'HALEY BUNN FOR WV': ['HALEY BUNN FOR WV', 'HALEY BUNNE FOR WV'],
 'DELIVER STRATEGIE': ['DELIVER STRATEGIE', 'DELIVER STRATEGIES'],
 'MODERATE DEMOCRAT': ['MODERATE DEMOCRAT', 'MODERATE DEMOCRATS'],
 'JOHN ILL CAMPAIGN': ['JOHN ILL CAMPAIGN', 'JOHN ILLG CAMPAIGN'],
 'FRIENDS OF WHITVER': ['FRIENDS OF WHITVER', 'WHITVER FRIENDS OF'],
 'BETH MIZELL FOR LA': ['BETH MIZELL FOR LA', 'BETH MITZELL FOR LA'],
 'PHIL KING CAMPAIGN': ['PHIL KING CAMPAIGN', 'KING CAMPAIGN PHIL'],
 'BOULTON FOR SENATE': ['BOULTON FOR SENATE', 'FOR SENATE BOULTON'],
 'THE REED COMMITTEE': ['THE REED COMMITTEE', 'REED COMMITTEE THE'],
 'CHRISTINA BOHANNAN': ['CHRISTINA BOHANNAN', 'BOHANNAN CHRISTINA'],
 'KIRSTEN GILLIBRAND': ['KIRSTEN GILLIBRAND', 'GILLIBRAND KIRSTEN'],
 'BRITTANY PETTERSEN': ['BRITTANY PETTERSEN', 'PETTERSEN BRITTANY'],
 'JIMMY DIXON FOR HD': ['JIMMY DIXON FOR HD', 'JIMMY DIXON FOR HD4'],
 'TYSON FOR NC HOUSE': ['TYSON FOR NC HOUSE', 'TYSON FOR NC HOUSE2'],
 'VOTE FRANK CARROLL': ['VOTE FRANK CARROLL', 'FRANK CARROLL VOTE'],
 'CARPENTERS SHELTER': ['CARPENTERS SHELTER', 'CARPENTER S SHELTER'],
 'ABIGAIL SPANBERGER': ['ABIGAIL SPANBERGER', 'SPANBERGER ABIGAIL'],
 'VOTERS OF TOMORROW': ['VOTERS OF TOMORROW', 'VOTERS OF TOMORRROW'],
 'FRIENDS OF GINTHER': ['FRIENDS OF GINTHER', 'FRIENDS OF GUINTHER'],
 'PAT CURRY CAMPAIGN': ['PAT CURRY CAMPAIGN', 'CURRY CAMPAIGN PAT'],
 'MIKE NORTON FOR AZ': ['MIKE NORTON FOR AZ', 'NORTON FOR AZ MIKE'],
 'ELECT JUSTIN OLSON': ['ELECT JUSTIN OLSON', 'JUSTIN OLSON ELECT'],
 'HUBERT VO CAMPAIGN': ['HUBERT VO CAMPAIGN', 'HUBERTO VO CAMPAIGN'],
 'ELECT JACK SELLERS': ['ELECT JACK SELLERS', 'JACK SELLERS ELECT'],
 'JOHN BELL COMMITEE': ['JOHN BELL COMMITEE', 'JOHN BELL COMMITTEE'],
 'RIGHT COUNTY LISTS': ['RIGHT COUNTY LISTS', 'RIGHT COUNTRY LISTS'],
 'COLONIAL DEMOCRATS': ['COLONIAL DEMOCRATS', 'CONLONIAL DEMOCRATS'],
 'BRENT MONEY FOR TX': ['BRENT MONEY FOR TX', 'BRENT MOONEY FOR TX'],
 'MCCANN FOR ID LORI': ['MCCANN FOR ID LORI', 'LORI MCCANN FOR ID'],
 'WEXTON FR CONGRESS': ['WEXTON FR CONGRESS', 'WEXTON FOR CONGRESS'],
 'KRIS WARNER FOR WV': ['KRIS WARNER FOR WV', 'KRIS WARNER FOR WVA'],
 'TIM BAHORST FOR OH': ['TIM BAHORST FOR OH', 'TIM BARHORST FOR OH'],
 'TODOS CON JENNIFER': ['TODOS CON JENNIFER', 'TODOS CON JENNIFFER'],
 'BRISCO CAIN FOR TX': ['BRISCO CAIN FOR TX',
  'BRISCOE CAIN FOR TX',
  'CAIN FOR TX BRISCOE'],
 'NEW DIRECTION FUND': ['NEW DIRECTION FUND', 'NEW DIRECTIONS FUND'],
 'TED BUDD FOR SENATE': ['TED BUDD FOR SENATE', 'TEDD BUDD FOR SENATE'],
 'MARY PELTOLA FOR AK': ['MARY PELTOLA FOR AK', 'PELTOLA FOR AK MARY'],
 'ALTMAN FOR CONGRESS': ['ALTMAN FOR CONGRESS', 'ALTMAN FOR CONGRESSS'],
 'FRIENDS OF TOM COOK': ['FRIENDS OF TOM COOK', 'FRIENDS OF TOM COOKE'],
 'SUN COUNTRY AIRLINE': ['SUN COUNTRY AIRLINE', 'SUN COUNTRY AIRLINES'],
 'DREW DARBY CAMPAIGN': ['DREW DARBY CAMPAIGN', 'DARBY CAMPAIGN DREW'],
 'JEFF LEACH CAMPAIGN': ['JEFF LEACH CAMPAIGN',
  'LEACH CAMPAIGN JEFF',
  'JEFF C LEACH CAMPAIGN'],
 'MORGAN MEYER FOR TX': ['MORGAN MEYER FOR TX', 'MEYER FOR TX MORGAN'],
 'MT DEMOCRATIC PARTY': ['MT DEMOCRATIC PARTY',
  'MT DEMOCRATICY PARTY',
  'MT DEMOCRACTIC PARTY'],
 'CITIZENS FOR SEXTON': ['CITIZENS FOR SEXTON', 'SEXTON CITIZENS FOR'],
 'JIM PERRY COMMITTEE': ['JIM PERRY COMMITTEE', 'JIM PERRY COMMITTTEE'],
 'CARRIE ISAAC FOR TX': ['CARRIE ISAAC FOR TX', 'ISAAC FOR TX CARRIE'],
 'TAN PARKER CAMPAIGN': ['TAN PARKER CAMPAIGN', 'PARKER CAMPAIGN TAN'],
 'DAVID WILLIS FOR NC': ['DAVID WILLIS FOR NC', 'DAVID WILLIAS FOR NC'],
 'KRISHNAMOORTHI RAJA': ['KRISHNAMOORTHI RAJA', 'KRISHNAMOORTHI S RAJA'],
 'BOOZMAN FOR AR JOHN': ['BOOZMAN FOR AR JOHN', 'JOHN BOOZMAN FOR AR'],
 'GENESEE FUTURE FUND': ['GENESEE FUTURE FUND', 'GENESSEE FUTURE FUND'],
 'MN DFL HOUSE CAUCUS': ['MN DFL HOUSE CAUCUS', 'MN HOUSE DFL CAUCUS'],
 'CROSSPARTISAN PAC I': ['CROSSPARTISAN PAC I', 'CROSSPARTISAN PAC II'],
 'LACEY HULL CAMPAIGN': ['LACEY HULL CAMPAIGN', 'LACEY M HULL CAMPAIGN'],
 'VICTORY VALUES FUND': ['VICTORY VALUES FUND', 'VICTORY VALLUES FUND'],
 'KEITH BELL CAMPAIGN': ['KEITH BELL CAMPAIGN', 'BELL CAMPAIGN KEITH'],
 'MILLER FOR OH KEVIN': ['MILLER FOR OH KEVIN', 'KEVIN MILLER FOR OH'],
 'FRIENDS FOR KLIMESH': ['FRIENDS FOR KLIMESH', 'KLIMESH FRIENDS FOR'],
 'J M LOZANO CAMPAIGN': ['J M LOZANO CAMPAIGN', 'LOZANO CAMPAIGN J M'],
 'KS SENATE DEMOCRATS': ['KS SENATE DEMOCRATS', 'KS SENATE DEMOCRATES'],
 'CODY VASUT CAMPAIGN': ['CODY VASUT CAMPAIGN', 'CODY T VASUT CAMPAIGN'],
 'HUGH SHINE CAMPAIGN': ['HUGH SHINE CAMPAIGN', 'HUGH D SHINE CAMPAIGN'],
 'KYLE MULLICA FOR SD': ['KYLE MULLICA FOR SD', 'KYLE MULLICA FOR SD24'],
 'MI PEOPLES CAMPAIGN': ['MI PEOPLES CAMPAIGN', 'MI PEOPLE S CAMPAIGN'],
 'GARCIA FOR CONGRESS': ['GARCIA FOR CONGRESS', 'S GARCIA FOR CONGRESS'],
 'SHAPIRO JOSH FOR PA': ['SHAPIRO JOSH FOR PA', 'JOSH SHAPIRO FOR PA'],
 'MANION VICTORY FUND': ['MANION VICTORY FUND', 'MANNION VICTORY FUND'],
 'BOSN FOR LEGISLATUE': ['BOSN FOR LEGISLATUE', 'BOSN FOR LEGISLATURE'],
 'GLEN HEGAR CAMPAIGN': ['GLEN HEGAR CAMPAIGN',
  'GLENN HEGAR CAMPAIGN',
  'HEGAR CAMPAIGN GLENN'],
 'ANA WITH THE PEOPLE': ['ANA WITH THE PEOPLE', 'ANNA WITH THE PEOPLE'],
 'THE FREEDOM PROJECT': ['THE FREEDOM PROJECT', 'FREEDOM PROJECT THE'],
 'MARY CAFERRO FOR HD': ['MARY CAFERRO FOR HD', 'MARY CAFERRO FOR HD81'],
 'HOYER MAJORITY FUND': ['HOYER MAJORITY FUND',
  'HOYERS MAJORITY FUND',
  'HOYER S MAJORITY FUND'],
 'SALAZAR FO CONGRESS': ['SALAZAR FO CONGRESS', 'SALAZAR FOR CONGRESS'],
 'DANIEL FOR CONGRESS': ['DANIEL FOR CONGRESS', 'DANIELS FOR CONGRESS'],
 'EMILY TSEFFO FOR WI': ['EMILY TSEFFO FOR WI', 'EMILY TSEFFOS FOR WI'],
 'UU HODGINS NOHELANI': ['UU HODGINS NOHELANI', 'U U HODGINS NOHELANI'],
 'DEMOCRATIC GOVENORS': ['DEMOCRATIC GOVENORS',
  'DEMOCRATIC GOVERNORS',
  'DEMOCRATIC GOVERNOR S'],
 'MONTANANS FOR TESTER': ['MONTANANS FOR TESTER', 'MONTANANANS FOR TESTER'],
 'BUCSHON FOR CONGRESS': ['BUCSHON FOR CONGRESS', 'BUSCHON FOR CONGRESS'],
 'IOWANS FOR ZACH NUNN': ['IOWANS FOR ZACH NUNN', 'ZACH NUNN IOWANS FOR'],
 'WALBERG FOR CONGRESS': ['WALBERG FOR CONGRESS', 'WALLBERG FOR CONGRESS'],
 'HOUCHIN FOR CONGRESS': ['HOUCHIN FOR CONGRESS', 'FOR CONGRESS HOUCHIN'],
 'MN DFL SENATE CAUCUS': ['MN DFL SENATE CAUCUS',
  'MN SENATE DFL CAUCUS',
  'MN DFL SENATE CAUCUS I'],
 'ERIC SORENSEN FOR IL': ['ERIC SORENSEN FOR IL', 'ERIC SORENSON FOR IL'],
 'THE MARKEY COMMITTEE': ['THE MARKEY COMMITTEE', 'MARKEY COMMITTEE THE'],
 'ANN JOHNSON CAMPAIGN': ['ANN JOHNSON CAMPAIGN', 'JOHNSON CAMPAIGN ANN'],
 'SLOTKIN VICTORY FUND': ['SLOTKIN VICTORY FUND', 'SOLTKIN VICTORY FUND'],
 'LYNN STUCKY CAMPAIGN': ['LYNN STUCKY CAMPAIGN', 'STUCKY CAMPAIGN LYNN'],
 'GREG BONNEN CAMPAIGN': ['GREG BONNEN CAMPAIGN', 'BONNEN CAMPAIGN GREG'],
 'JOHN BRYANT CAMPAIGN': ['JOHN BRYANT CAMPAIGN', 'BRYANT CAMPAIGN JOHN'],
 'PETE FLORES CAMPAIGN': ['PETE FLORES CAMPAIGN', 'PETER FLORES CAMPAIGN'],
 'TODD HUNTER CAMPAIGN': ['TODD HUNTER CAMPAIGN', 'HUNTER CAMPAIGN TODD'],
 'SECURING MI S FUTURE': ['SECURING MI S FUTURE', 'SECURING MO S FUTURE'],
 'FRIENDS OF ED HOOPER': ['FRIENDS OF ED HOOPER', 'FRIEDNS OF ED HOOPER'],
 'CANDY NOBLE CAMPAIGN': ['CANDY NOBLE CAMPAIGN', 'NOBLE CAMPAIGN CANDY'],
 'RUBEN GALLEGO FOR AZ': ['RUBEN GALLEGO FOR AZ', 'GALLEGO FOR AZ REUBEN'],
 'SETH BLATTMAN FOR AZ': ['SETH BLATTMAN FOR AZ', 'BLATTMAN FOR AZ SETH'],
 'LISA BLUNT ROCHESTER': ['LISA BLUNT ROCHESTER',
  'ROCHESTER LISA BLUNT',
  'BLUNT ROCHESTER LISA'],
 'ANALISE ORTIZ FOR AZ': ['ANALISE ORTIZ FOR AZ', 'ORTIZ FOR AZ ANALISE'],
 'CA YOUNG REPUBLICANS': ['CA YOUNG REPUBLICANS', 'AZ YOUNG REPUBLICANS'],
 'ED GONZALEZ CAMPAIGN': ['ED GONZALEZ CAMPAIGN', 'ED GONZALES CAMPAIGN'],
 'GRANT MOODY CAMPAIGN': ['GRANT MOODY CAMPAIGN', 'GRANT A MOODY CAMPAIGN'],
 'JEFF YARBO FOR MAYOR': ['JEFF YARBO FOR MAYOR', 'JEFF YARBRO FOR MAYOR'],
 'SCOTT SMITH FOR MESA': ['SCOTT SMITH FOR MESA', 'SMITH SCOTT FOR MESA'],
 'JON ROSENTHAL FOR TX': ['JON ROSENTHAL FOR TX', 'ROSENTHAL FOR TX JON'],
 'GLEN ROGERS CAMPAIGN': ['GLEN ROGERS CAMPAIGN',
  'GLENN ROGERS CAMPAIGN',
  'ROGERS CAMPAIGN GLENN'],
 'STAN GERDES CAMPAIGN': ['STAN GERDES CAMPAIGN', 'STAND GERDES CAMPAIGN'],
 'LANDSMAN FOR CONGRES': ['LANDSMAN FOR CONGRES', 'LANDSMAN FOR CONGRESS'],
 'GLOBAL STRATEGY GOUP': ['GLOBAL STRATEGY GOUP', 'GLOBAL STRATEGY GROUP'],
 'COREY SIMON CAMPAIGN': ['COREY SIMON CAMPAIGN', 'COREY J SIMON CAMPAIGN'],
 'JACY JETTON CAMPAIGN': ['JACY JETTON CAMPAIGN',
  'JACEY JETTON CAMPAIGN',
  'JETTON CAMPAIGN JACEY'],
 'JAMES FRANK CAMPAIGN': ['JAMES FRANK CAMPAIGN', 'FRANK CAMPAIGN JAMES'],
 'ERNEST BAILES FOR TX': ['ERNEST BAILES FOR TX', 'BAILES FOR TX ERNEST'],
 'ND YOUNG REPUBLICANS': ['ND YOUNG REPUBLICANS', 'IN YOUNG REPUBLICANS'],
 'THOMAS LEEK CAMPAIGN': ['THOMAS LEEK CAMPAIGN', 'THOMAS J LEEK CAMPAIGN'],
 'BROOK LIERMAN FOR MD': ['BROOK LIERMAN FOR MD', 'BROOKE LIERMAN FOR MD'],
 'CORY WOODS FOR MAYOR': ['CORY WOODS FOR MAYOR', 'COREY WOODS FOR MAYOR'],
 'IN VICTORY COMMITTEE': ['IN VICTORY COMMITTEE', 'NV VICTORY COMMITTEE'],
 'TN YOUNG REPUBLICANS': ['TN YOUNG REPUBLICANS', 'TX YOUNG REPUBLICANS'],
 'FRIENDS OF BEN LINDY': ['FRIENDS OF BEN LINDY', 'BEN LINDY FRIENDS OF'],
 'JULIE DOOLING FOR HD': ['JULIE DOOLING FOR HD', 'JULIE DOOLING FOR HD84'],
 'FRIENDS OF NIC KIPKE': ['FRIENDS OF NIC KIPKE',
  'FRIENDS OF NICK KIPKE',
  'FRIENDS OF NIK KIPKE'],
 'FRIENDS OF JOE GIRAL': ['FRIENDS OF JOE GIRAL', 'FRIENDS OF JOSE GIRAL'],

In [37]:

# reconfigure mapping to be pattern: group instead of group: pattern 

def convert_to_regex_map(original_dict):
    regex_map = {}

    for name, variants in original_dict.items():
        # Escape each variant for regex safety
        escaped_variants = [v for v in variants]

        # Join into one regex pattern
        regex_pattern = r"|".join(escaped_variants)

        # Map pattern → canonical key
        regex_map[regex_pattern] = name

    return regex_map


mapping_2 = convert_to_regex_map(mapping)

In [38]:
# Compile regex map so that we can use it to assign payees to vendors 
def compile_regex_map(regex_map):
    compiled = []
    for pattern, replacement in regex_map.items():
        compiled.append((re.compile(pattern, re.IGNORECASE), replacement))
    return compiled


mapping_2_sorted = dict(
    sorted(mapping_2.items(), key=lambda x: -len(x[0]))
)

In [39]:
# apply group names as vendors to matching payee ids 
compiled_map = compile_regex_map(mapping_2)

def apply_regex_mapping(text, regex_map):
    if pd.isna(text):
        return None
    for regex, replacement in compiled_map:
        if regex.search(text):
            return replacement
    return None

# identify indexes of na vendor rows 
mask = spending_data['vendor'].isna()

# Apply mapping to null vendors 
spending_data.loc[mask, 'vendor'] = spending_data.loc[mask, 'payee_id'].apply(
    lambda x: apply_regex_mapping(x, mapping_2)
)

In [40]:
spending_data.head()

,form_type,filer_committee_id_number,payee_organization_name,payee_last_name,payee_first_name,expenditure_date,expenditure_amount,expenditure_purpose_descrip,beneficiary_candidate_last_name,beneficiary_candidate_first_name,memo_code,memo_text_description,form_type_desc,payee_name,beneficiary_cand_name,payee_id,vendor
0,SB23,C00450965,MIKE BOST FOR CONGRESS COMMITTEE,NaN,NaN,,1000.0,CONTRIBUTION TO COMMITTEE,BOST,MIKE,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,MIKE BOST,MIKE BOST FOR CONGRESS COMMITTEE,MIKE BOST FOR CONGRESS COMMITT
1,SB23,C00450965,ANNIE,NaN,NaN,,2500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,ANNIE,None
2,SB23,C00450965,BRETTPAC,NaN,NaN,,1500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,BRETTPAC,BRETTPAC
3,SB23,C00450965,CASEY KEYSTONE VICTORY FUND,NaN,NaN,,1000.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,CASEY KEYSTONE VICTORY FUND,None
4,SB23,C00450965,OORAH,NaN,NaN,,2500.0,CONTRIBUTION TO COMMITTEE,NaN,NaN,NaN,NaN,CONTRIBUTIONS TO CANDIDATES AND COMMITTEES,,,OORAH,None

In [41]:
# recalculate dimentionality reduction
n_vendors = len(spending_data.vendor.unique()) + len(spending_data[spending_data['vendor'].isna()].payee_id.unique())

1-(n_vendors/n_original_payees)

0.11991355003077275

In [42]:
# I looked up the largest uncoded payees by number of lineitems and coded them manually 
mapping_3 = {
    # just Ted Cruz because he has multiple committees, pres, senate, etct
    r'TED CRUZ': 'TED CRUZ',
    r'ANEDOT': 'ANEDOT',
    r'BERNIE MORENO': 'BERNIE MORENO FOR SENATE',
    r'RICK SCOTT FOR':'RICK SCOTT FOR FL',
    r'JOSH HAWLEY':'JOSH HAWLEY FOR SENATE',
    r'KARI LAKE':'KARI LAKE FOR SENATE',
    r'ELISSA SLOTKIN': 'ELISSA SLOTKIN FOR SENATE',
    r'ANGELA ALSOBROOKS':'ANGELA ALSOBROOKS FOR SENATE',
    r'TAMMY BALDWIN': 'TAMMY BALDWIN FOR SENATE',
    r'MARY PELTOLA': 'MARY PELTOLA FOR SENATE',
    r'ROSEN FOR NV| JACKIE ROSEN': 'ROSEN FOR NV'
}
compiled_map = compile_regex_map(mapping_3)

mask = spending_data['vendor'].isna()

spending_data.loc[mask, 'vendor'] = spending_data.loc[mask, 'payee_id'].apply(
    lambda x: apply_regex_mapping(x, mapping_3)
)

In [43]:
# Recalculate dimensionality reduction
n_vendors = len(spending_data.vendor.unique()) + len(spending_data[spending_data['vendor'].isna()].payee_id.unique())

1-(n_vendors/n_original_payees)

0.12008530493652225

In [44]:
# I need to move on. Creating vendor_full as the concatenation of vendor and payee id 
spending_data['vendor_full'] = (
    spending_data[['vendor', 'payee_id']]
    .replace('', pd.NA)         
    .bfill(axis=1)              
    .iloc[:, 0]                 
)

In [45]:
# final dimensionality reduction assessment
n_test = len(spending_data['payee_id'].unique())
n_vendors = len(spending_data['vendor_full'].unique())

print('I have reduced dimensionality by',1-(n_vendors/n_test))

I have reduced dimensionality by 0.10710342823939567

In [46]:
# Reading in the PACs dataset
pacs = pd.read_csv('../data/processed/pac_financials.csv', usecols= ['committee_id', 
'committee_name',
'committee_designation',
'committee_designation_full', 
'committee_type', 
'committee_type_full',
'filing_frequency', 
'organization_type',
'organization_type_full', 
'treasurer_name',
'committee_state', 
'coverage_end_date', 
'coverage_start_date', 
'first_file_date', 
'cycle',
'receipts',
'individual_contributions', 
'individual_itemized_contributions',
'individual_unitemized_contributions',
'disbursements'
])

pacs.head()

,committee_designation,committee_designation_full,committee_id,committee_name,committee_state,committee_type,committee_type_full,coverage_end_date,coverage_start_date,cycle,disbursements,filing_frequency,first_file_date,individual_contributions,individual_itemized_contributions,individual_unitemized_contributions,organization_type,organization_type_full,receipts,treasurer_name
0,U,Unauthorized,C00000489,D R I V E POLITICAL FUND CHAPTER 886,OK,N,PAC - Nonqualified,2024-12-31T00:00:00,2023-01-01T00:00:00,2024,27426.58,Q,1976-07-13,0.00,0.00,0.00,L,Labor Organization,93817.80,JERRY SIMS JR
1,B,Lobbyist/Registrant PAC,C00000729,AMERICAN DENTAL ASSOCIATION POLITICAL ACTION C...,DC,Q,PAC - Qualified,2024-12-31T00:00:00,2023-01-01T00:00:00,2024,2617456.75,M,1975-02-09,2118774.56,1304725.93,814048.63,M,Membership Organization,2228046.98,"TIPPETT-WHYTE, JUDEE DR."
2,B,Lobbyist/Registrant PAC,C00000885,INTERNATIONAL UNION OF PAINTERS AND ALLIED TRA...,MD,Q,PAC - Qualified,2024-12-31T00:00:00,2023-01-01T00:00:00,2024,3244535.22,M,1975-03-20,5306388.90,405469.89,4900919.01,L,Labor Organization,5525285.55,"SMITH, GREGG"
3,B,Lobbyist/Registrant PAC,C00000059,"HALLMARK CARDS, INC. PAC (HALLPAC)",MO,Q,PAC - Qualified,2024-12-31T00:00:00,2023-01-01T00:00:00,2024,117500.00,M,1976-04-22,91727.18,62548.68,29178.50,C,Corporation,95727.18,"KLEIN, CASSIE MS."
4,B,Lobbyist/Registrant PAC,C00000422,AMERICAN MEDICAL ASSOCIATION POLITICAL ACTION ...,DC,Q,PAC - Qualified,2024-12-31T00:00:00,2023-01-01T00:00:00,2024,2621577.12,M,1975-03-06,1666298.01,1300778.67,365519.34,NaN,NaN,2096337.89,"JORDAN, JOHN ROBERT MR."

In [47]:
pacs.columns

Index(['committee_designation', 'committee_designation_full', 'committee_id',
       'committee_name', 'committee_state', 'committee_type',
       'committee_type_full', 'coverage_end_date', 'coverage_start_date',
       'cycle', 'disbursements', 'filing_frequency', 'first_file_date',
       'individual_contributions', 'individual_itemized_contributions',
       'individual_unitemized_contributions', 'organization_type',
       'organization_type_full', 'receipts', 'treasurer_name'],
      dtype='object')

### Code Expenditure types

Here I try to repeat the work done above on the expenditure types. Ultimately, in the interest of time I decided to keep the expense coding simple: contributions or transfers to candidates or committees or not.

In [48]:
# To start, I am coding expenditure data based on their form_types, either contributions or transfers, or not. 

spending_data['exp_cat'] = np.where(spending_data['form_type']=='SB23', 'Contribution to Candidate or Committee',
                           np.where(spending_data['form_type']=='SB22', 'Transfer to affiliated committee',
                           'Other'
      )
)

When experimenting with expenditure purpose cleaning, I use a lower threshold becuase the concerns about mis coding are less acute. Ultimately I chose not to focus resources on cleaning expenditure purpose descriptions for this project, but in the future, this work will be relevant when trying to classify the other expenditures.

In [49]:
unique_purposes = spending_data['expenditure_purpose_descrip'].unique().tolist()
threshold = 85
purpose_groups = []

while unique_purposes:
    purpose = unique_purposes.pop(0)
    # Find all similar purposes
    matches = process.extract(purpose, unique_purposes, scorer=fuzz.token_sort_ratio, score_cutoff=threshold)
    # Add purpose itself
    group = [purpose] + [m[0] for m in matches]
    purpose_groups.append(group)
    # Remove matched purposes
    unique_purposes = [x for x in unique_purposes if x not in [m[0] for m in matches]]

purpose_groups

[['CONTRIBUTION TO COMMITTEE',
  'CONTRIBUTION TO COMMMITTEE',
  'CONTRIBUTON TO COMMITTEE',
  'CONTRIBUTION T COMMITTEE',
  'CONTIBUTION TO COMMITTEE',
  'CONTRIBUTION TO COMMITEE'],
 [nan],
 ['IN KIND LEGAL'],
 ['PAC POLITICAL CONTRIBUTION',
  'PAC POLTICAL CONTRIBUTION',
  'PAC POLITCAL CONTRIBUTION',
  'PAC POLITICAL CONTRIBTION',
  'PAC POLITICAL CONTRIBUTIN',
  'PAC POLITICAL CONRIBUTION'],
 ['PAC COMPLIANCE', 'PAC COMPLAINCE', 'JFC COMPLIANCE', 'FEC COMPLIANCE'],
 ['PAC FUNDRAISING',
  'PAC FUNDRASING',
  'PAC SMS FUNDRAISING',
  'MARCH  FUNDRAISING',
  'JFC FUNDRAISING',
  'MAY  FUNDRAISING'],
 ['CONTRIBUTION',
  'CPONTRIBUTION',
  'CONTRIBUTIUON',
  'CONTRIBUTIONB',
  'CONTRIBUTIOIN',
  'CONTRIBUTRION'],
 ['PRIMARY', 'PIMARY'],
 ['MERCHANT FEES',
  'MERCHANT FEE',
  'MECHANT FEES',
  'MERCHANT FES',
  'E MERCHANT FEES',
  'MERCAHNT FEES'],
 ['BANK FEE', 'BANK FEES', 'BANK FREE', 'BANKFEE', 'BANK FE', 'BANKT FEES'],
 ['CONTRIBUTION TO A STATE COMMITTEE',
  'CONTRIBUTION TO STATE COMMITTEE',
  'CONTRIBUTION TO STATE BALLOT COMMITTEE',
  'CONTRIBUTION TO  COMMITTEE SENATE',
  'STATE COMMITTEE CONTRIBUTION',
  'CONTRIBUTION STATE COMMITTEE'],
 ['EARMARKED FROM WILLIAM CHAPMAN',
  'EARMARKED FROM WILLIAM BOWMAN',
  'EARMARKED FROM ALAN WILL'],
 ['NON CONTRIBUTION ACCT DATABASE',
  'NON CONTRIBUTION ACCOUNT DATABASE',
  'NON CONTRIBUTION ACCT DATA',
  'NON CONTRIBUTION ACCOUNT DATA'],
 ['WEBSITE'],
 ['CC PROCESSING FEES',
  'CC PROCCESSING FEES',
  'CC PROCESSING FEE',
  'PROCESSING FEES DEC',
  'PROCESSING FEES',
  'MAY CC PROCESSING FEES'],
 ['ADVERTISING EXPENSE FOR PLEDGE CAMPAIGN'],
 ['LIST ACQUISITION',
  'LIST AQUISITION',
  'PAC LIST ACQUISITION',
  'TEXT LIST ACQUISITION'],
 ['AD PURCHASE'],
 ['PAC MANAGEMENT',
  'PAC MANAGMENT',
  'PAC MANAGEMENT AND',
  'PAC MANAGEMENT FEE'],
 ['PAC EXPENSE REIMBURSEMENT',
  'EXPENSE REIMBURSEMENT',
  'REIMBURSEMENT EXPENSES',
  'REIMBURSEMENT PARKING EXPENSE',
  'PAC TRAVEL EXPENSE REIMBURSEMENT',
  'OFFCIE EXPENSE REIMBURSEMENT'],
 ['GENERAL'],
 ['EARMARK BY KENNETH PECHMAN PAC LIMITS UNAFFECTED'],
 ['EARMARK BY ANDREW CALVIN PAC LIMITS UNAFFECTED',
  'EARMARK BY ANDREW CAMPBELL PAC LIMITS UNAFFECTED'],
 ['EARMARKED BY SEE MEMO ENTRIES PAC LIMITS UNAFFECTED',
  'EARMARK BY SEE MEMO ENTRIES PAC LIMITS UNAFFECTED',
  'EARMARK BY SEE MEMO ENTRIES PAC LIMITS UNEFFECTED'],
 ['EARMARK BY TOSHA WETTERNECK PAC LIMITS UNAFFECTED'],
 ['EARMARK BY DANIEL BENNETT PAC LIMITS UNAFFECTED'],
 ['EARMARK BY BARBARA HUMMEL PAC LIMITS UNAFFECTED'],
 ['EARMARK BY DONN DEXTER PAC LIMITS UNAFFECTED',
  'EARMARK BY KRISTEN DEXTER PAC LIMITS UNAFFECTED',
  'EARMARK BY DON LEE PAC LIMITS UNAFFECTED'],
 ['EARMARK BY KENNETH MERKITCH PAC LIMITS UNAFFECTED'],
 ['EARMARK BY WENDY MOLASKA PAC LIMITS UNAFFECTED'],
 ['EARMARK BY MELISSA LUCARELLI PAC LIMITS UNAFFECTED'],
 ['TRANSFER', 'TRANFSFER', 'TRANFER'],
 ['PROCESSING FEE',
  'PROCCESSING FEE',
  'PROCESING FEE',
  'PROESSING FEE',
  'PROCESSNG FEES',
  'PROCESSING FEES ON'],
 ['BANK SERVICE CHARGE',
  'BANK SERVICE CHARGES',
  'BANK ERVICE CHARGE',
  'BANK SERICE CHARGE',
  'BANKING SERVICE CHARGE',
  'PAC BANK SERVICE CHARGE'],
 ['CATERING EVENTS',
  'EVENT CATERING',
  'CATERING    EVENT',
  'EVENT CATERING SITE',
  'EVENT SPACE CATERING'],
 ['CREDIT CARD PAYMENT',
  'CREDIT CARD PAYMENTS',
  'CREIDT CARD PAYMENT',
  'PAC CREDIT CARD PAYMENT',
  'CREDIT CARD PAYMENT TBD',
  'CREDIT CARD PMT'],
 ['TRANSPORTATION',
  'TRANSPORTAITION',
  'TRANSPORATION',
  'TRANSPOTATION',
  'TRANSPIRATION',
  'PAC TRANSPORTATION'],
 ['LODGING', 'LODING', 'LOGDING'],
 ['PROMOTIONAL MATERIALS',
  'PROMOTIIONAL MATERIALS',
  'PROMOTIONAL MATERIAL',
  'PAC PROMOTIONAL MATERIALS'],
 ['AIRFARE', 'AIR FARE', 'AIREFARE', 'AIRFAIRE'],
 ['TRAVEL LODGING REIMBURSEMENT',
  'REIMBURSEMENT TRAVEL LODGING',
  'REIMBURSEMENTS LODGING TRAVEL',
  'LOGAN TRAVEL REIMBURSEMENT',
  'TRAVEL REIMBURSEMENT LODGING HOTEL',
  'REIMBURSEMENT SB21B  TRAVEL LODGING'],
 ['RAIL TRANSPORTATION',
  'TRAIN TRANSPORTATION',
  'AIR TRANSPORTATION',
  'TRANSPORTATION RENTAL',
  'TRANSPORTATION MEALS',
  'CAR TRANSPORTATION'],
 ['DATABASE SUPPORT', 'DATA SUPPORT'],
 ['RAIL TRAVEL',
  'TRAVEL RAIL',
  'TRAIN TRAVEL',
  'TRAVEL TRAIN',
  'TRAVEL AIR',
  'AIR TRAVEL'],
 ['COMPLIANCE',
  'COMPILIANCE',
  'COMPLLIANCE',
  'CONMPLIANCE',
  'COOMPLIANCE',
  'COMPIANCE'],
 ['CREDIT CARD MERCHANT FEE',
  'CREDIT CARD MERCHANT FEES',
  'MERCHANT CREDIT CARD FEES',
  'CREDIR CARD MERCHANT FEES',
  'CREDIT CARD MERCHANT FEE DIT',
  'PAC CREDIT CARD MERCHANT FEES'],
 ['REIMBURSEMENT FOR JANUARY  RENT EXPENSE',
  'REIMBURSEMENT FOR JULY  RENT EXPENSE',
  'REIMBURSEMENT FOR MAY  RENT EXPENSE',
  'REIMBURSEMENT FOR JUNE  RENT EXPENSE',
  'REIMBURSEMENT FOR JANUARY  SALARIES EXPENSE',
  'REIMBURSEMENT FOR MARCH  RENT EXPENSE'],
 ['REIMBURSEMENT FOR JANUARY  BANK CHARGES EXPENSE',
  'REIMBURSEMENT FOR MAY  BANK CHARGES EXPENSE',
  'REIMBURSEMENT FOR JUNE  BANK CHARGES EXPENSE',
  'REIMBURSEMENT FOR MARCH  BANK CHARGES EXPENSE',
  'REIMBURSEMENT FOR FEBRUARY  BANK CHARGES EXPENSE',
  'REIMBURSEMENT FOR NOVEMBER  BANK CHARGES EXPENSE'],
 ['REIMBURSEMENT FOR JANUARY  ADMINISTRATIVE EXPENSE',
  'REIMBURSEMENT FOR JULY  ADMINISTRATIVE EXPENSE',
  'REIMBURSEMENT FOR MAY  ADMINISTRATIVE EXPENSE',
  'REIMBURSEMENT FOR JUNE  ADMINISTRATIVE EXPENSE',
  'REIMBURSEMENT FOR MARCH  ADMINISTRATIVE EXPENSE',
  'REIMBURSEMENT FOR FEBRUARY  ADMINISTRATIVE EXPENSE'],
 ['TRANSFER TO STATE', 'TRANSFER TO LOCAL  STATE'],
 ['TREASURY'],
 ['NON CONTRIBUTION ACCOUNT DONATION',
  'DONATION NON CONTRIBUTION ACCOUNT',
  'DONATION NON CONTRIBUITION ACCOUNT',
  'DONATION TO NON CONTRIBUTION ACCOUNT',
  'NON CONTRIBUTION ACCT DONATION',
  'CIVIC DONATION NON CONTRIBUTION ACCOUNT'],
 ['NONFEDERAL CONTRIBUTION',
  'CONTRIBUTION NONFEDERAL',
  'NONFEDERALL CONTRIBUTION',
  'NONFEDERAL CONTRIBUTIOON',
  'CONTRIBUTIONB NONFEDERAL',
  'NONFEDERAL CONTRIBTION'],
 ['CONTRIBUTION TO OTHER SUPER',
  'CONTRIBUTION TO OTHER',
  'CONTRIBUTION TO SUPER'],
 ['FUNDRAISING AND POLITICAL STRATEGIC',
  'POLITICAL STRATEGY AND FUNDRAISING',
  'PAC STRATEGIC AND FUNDRAISING'],
 ['BANKING FEE', 'BANKING FEES'],
 ['CONTRIBUTION TO CANDIDATE',
  'CONTRIBUTION TO CANDIDATES',
  'CONTRIBUTION TO CANDIDATER',
  'CONTRIBUTION TO A CANDIDATE',
  'CANDIDATE CONTRIBUTION',
  'PAC CONTRIBUTION TO CANDIDATE'],
 ['SOFTWARE'],
 ['CANVASSING', 'CANVASSING AZ', 'IE CANVASSING'],
 ['GRAPHIC DESIGN',
  'DESIGN GRAPHICS',
  'GRAPHICS DESIGN',
  'GRAPHIC DESIGNS',
  'GRAPHIC DESIGNER',
  'GRAPHICS DEIGN'],
 ['BANK CHARGE',
  'BANK CHARGES',
  'BANCK CHARGES',
  'BANK CHARGESB',
  'CHARGE BACK'],
 ['DONATION', 'DONATIONS', 'DONTATION', 'DOANTION', 'DONAITON', 'DONATOIN'],
 ['CREDIT CARD PROCESSING FEE',
  'CREDIT CARD PROCESSING FEES',
  'CREDIT CARD PROCESSING FEE\\',
  'CREDIT CARD PROCESSSING FEE',
  'CREDIT CARD PROCESSING FEEA',
  'CRDIT CARD PROCESSING FEE'],
 ['CONSULTANT COMPLIANCE',
  'COMPLIANCE CONSULTANT',
  'COMPLIANCE CONSULTIN',
  'PAC COMPLIANCE CONSULTANT',
  'CONSULTING COMPLIANCE',
  'COMPLIANCE CONSULTING'],
 ['DESIGN'],
 ['CONSULTANT FUNDRAISING',
  'FUNDRAISING CONSULTANT',
  'FUNDRAISING CONSULTANTS',
  'FUNDRIAISING CONSULTANT',
  'FUNDRAISING CONULTANT',
  'PAC FUNDRAISING CONSULTANT'],
 ['EARMARK OF POLLY LEVINE'],
 ['EARMARK OF NORMAN BROWNSTEIN',
  'EARMARK OF NORM BROWNSTEIN',
  'VOID EARMARK OF NORMAN BROWNSTEIN',
  'EARMARK OF NANCY BERNSTEIN'],
 ['EARMARK OF KENNETH SCHWARTZ',
  'EARMARK OF LEE SCHWARTZ',
  'EARMARK OF ELISABETH SCHWARTZ'],
 ['EARMARK OF STUART MEYERS',
  'EARMARK OF SARA MEYERS',
  'EARMARK OF STUART SARA MEYERS',
  'EARMARK OF SARA STUART MEYERS',
  'EARMARK OF TARO MEYER',
  'EARMARK OF STUART KRAMER'],
 ['EARMARK OF JUDAH LEVINE',
  'EARMARK OF JAMES LEVINE',
  'EARMARK OF JACK LEVIN',
  'EARMARK OF JONATHAN LEVINE',
  'EARMARK OF JANICE LEVINE'],
 ['EARMARK OF ADAM BERKOWITZ', 'EARMARK OF ADAM BOBROW'],
 ['EARMARK OF MICHAEL HACKMAN',
  'EARMARK OF MICHAEL HAAS',
  'EARMARK OF MICHAEL HAHN',
  'EARMARK OF MICHAEL KAHN',
  'EARMARK OF MICHAEL KANN',
  'EARMARK OF MICHAEL KALICHMAN'],
 ['EARMARK OF BRUCE ETTELSON',
  'EARMARK OF BRUCE LEON',
  'EARMARK OF BRUCE ETKIN'],
 ['EARMARK OF NEVILLE ISAACSON', 'EARMARK OF ISAACSON NEVILLE'],
 ['EARMARK OF SCOTT BENDER',
  'EARMARK OF SCOTT BRENNER',
  'EARMARK OF SCOTT BECKER',
  'EARMARK OF SCOTT BERRY',
  'EARMARK OF SCOTT DONNER',
  'EARMARK OF SCOTT BOHRER'],
 ['EARMARK OF MICHAEL DAVIS',
  'EARMARK OF MICHAEL DAVIDSON',
  'EARMARK OF MITCHELL DAVIS',
  'EARMARK OF MITCH DAVIS',
  'EARMARK OF DAVID MICHAN',
  'EARMARK OF MICHAEL DALY'],
 ['EARMARK OF ROSELLE MIRONER'],
 ['EARMARK OF MARK ENGEL',
  'EARMARK OF MATT ENGEL',
  'EARMARK OF MARK ELY',
  'EARMARK OF MARK FINE',
  'EARMARK OF MARK KING',
  'EARMARK OF MARK MANDELL'],
 ['EARMARK OF LARRY GENET',
  'EARMARK OF LARRY GERBER',
  'EARMARK OF LARRY GREENBERG',
  'EARMARK OF LAWRENCE GENET'],
 ['EARMARK OF IRVING WEINTRAUB'],
 ['EARMARK OF MARK COHEN',
  'EARMARK OF MARC COHEN',
  'EARMARK OF MARGO COHEN',
  'EARMARK OF MARINA COHEN',
  'VOID EARMARK OF MARK COHEN',
  'EARMARK OF MARK CHAZIN'],
 ['EARMARK OF EVAN SCHLESSINGER'],
 ['EARMARK OF ALAN FRANCO',
  'EARMARK OF DIANE FRANCO',
  'EARMARK OF ALAN FRIEDMAN',
  'EARMARK OF ALLAN JACOB',
  'EARMARK OF ALAN KAHN'],
 ['EARMARK OF NATHAN KORNFELD'],
 ['EARMARK OF MANUEL RAJUNOV', 'VOID EARMARK OF MANUEL RAJUNOV'],
 ['EARMARK OF LOREN DAITCH'],
 ['EARMARK OF STEVE STONE',
  'EARMARK OF STEVEN STONE',
  'EARMARK OF STEVE UNGER',
  'EARMARK OF STEVEN TODD'],
 ['EARMARK OF TIM WILLIAMS',
  'EARMARK OF TIM WILLLIAMS',
  'EARMARK OF WILLIAM TAMLYN',
  'EARMARK OF E WILLIAMS',
  'EARMARK OF WILLIAM WEISS',
  'EARMARK OF WILLIAM SMITH'],
 ['EARMARK OF SCOTT SIFF',
  'VOID EARMARK OF SCOTT SIFF',
  'EARMARK OF SCOTT SOLKOFF',
  'EARMARK OF SCOTT SIEGEL',
  'EARMARK OF SCOTT TAFFET'],
 ['EARMARK OF YEHUDA NEUBERGER'],
 ['EARMARK OF KINNEY ZALESNE'],
 ['EARMARK OF MARC COOPER',
  'EARMARK OF MARSHALL COOPER',
  'EARMARK OF ERIK COOPER',
  'EARMARK OF JANE COOPER',
  'EARMARK OF ERIN COOPER',
  'EARMARK OF MIKE COOPER'],
 ['EARMARK OF DIANA ANDERSON',
  'EARMARK OF DANA BEESON',
  'EARMARK OF DANA BARRON'],
 ['EARMARK OF ELIZABETH DAVIS',
  'EARMARK OF ELIZABETH BISH',
  'EARMARK OF ELIZABETH BLAU',
  'EARMARK OF ELIZABETH BRUS',
  'EARMARK OF ELIZABETH DEMPSEY',
  'EARMARK OF ELIZABETH CONLISK'],
 ['EARMARK OF PAUL ROSENBERG',
  'EARMARK OF PAUL ROTTENBERG',
  'EARMARK OF PAUL SCHEINBERG',
  'EARMARK OF PAUL REINER',
  'EARMARK OF RACHEL ROSENBERG',
  'EARMARK OF PETER ROSENBERG'],
 ['EARMARK OF BRIAN SCHALL',
  'EARMARK OF BRIAN SHAW',
  'EARMARK OF BRIAN SHACK',
  'EARMARK OF SAUL BURIAN',
  'EARMARK OF BRIAN SCHWARTZ',
  'EARMARK OF BRIAN SHUMAN'],
 ['EARMARK OF YAKOUB SAADIA'],
 ['EARMARK OF SCOTT JAFFEE',
  'EARMARK OF SCOTT JAFFE',
  'EARMARK OF SCOTT FANE'],
 ['EARMARK OF DAVID KERDELL',
  'EARMARK OF DAVID NEWELL',
  'EARMARK OF DAVID KEIL',
  'EARMARK OF DAVID MINDELL',
  'EARMARK OF DAVID KAGEL',
  'EARMARK OF DAVID KURZWEIL'],
 ['EARMARK OF DANA PACHULSKI'],
 ['EARMARK OF VICTOR KOHN',
  'EARMARK OF VICTOR MELLON',
  'EARMARK OF VICTORIA JOHNSON'],
 ['EARMARK OF DOUGLAS GESSNER',
  'EARMARK OF DOUG GESSNER',
  'EARMARK OF DOUGLAS FEINBERG',
  'EARMARK OF GEORGE DOUGLAS'],
 ['EARMARK OF HELEN BROWNSTEIN', 'EARMARK OF EVE BERNSTEIN'],
 ['EARMARK OF BRADFORD SANDLER'],
 ['EARMARK OF RONALD BAKALARZ', 'EARMARK OF RONALD BARRY'],
 ['EARMARK OF SARIT CATZ'],
 ['EARMARK OF ROBERT EFROYMSON',
  'EARMARK OF ROBERT FROMER',
  'EARMARK OF ROBERT GERN'],
 ['EARMARK OF SAMANTHA GARELICK'],
 ['EARMARK OF NANCY TEBELE'],
 ['EARMARK OF ETAN COHEN',
  'EARMARK OF JEAN COHEN',
  'EARMARK OF KEN COHEN',
  'EARMARK OF JEAN S COHEN',
  'EARMARK OF ELAINE COHEN',
  'EARMARK OF NATHAN COHEN'],
 ['EARMARK OF BRYAN BIER',
  'EARMARK OF BRYAN BOMBERG',
  'EARMARK OF BRYAN BRUNS',
  'EARMARK OF BEN BRAUN',
  'EARMARK OF BRIAN BERMAN',
  'EARMARK OF BEN BAER'],
 ['EARMARK OF RICHARD PACHULSKI', 'VOID EARMARK OF RICHARD PACHULSKI'],
 ['EARMARK OF ALAN LEVOW',
  'EARMARK OF ALLAN LOWE',
  'EARMARK OF ALLAN LEVY',
  'EARMARK OF ALAN LEVAN',
  'EARMARK OF ALAN LEVIN',
  'EARMARK OF CARY LEVOW'],
 ['EARMARK OF ANN NACHBAR'],
 ['EARMARK OF RAPHAEL ADES',
  'EARMARK OF RAPHAEK ADES',
  'EARMARK OF BRADLEY RAPHAEL',
  'EARMARK OF RACHAEL ADAMS',
  'EARMARK OF DEBORAH RAPHAEL',
  'EARMARK OF BRIAN RAPHAEL'],
 ['EARMARK OF ROBERT MARGOLIS',
  'EARMARK OF ROBERT MARKS',
  'EARMARK OF ROBERT HARRIS',
  'EARMARK OF ROBERT GLASS',
  'EARMARK OF ROBERT NAGLE'],
 ['EARMARK OF MAIA MAGDER'],
 ['EARMARK OF MICHAEL TUCHIN',
  'EARMARK OF MICHAEL SCHEIN',
  'EARMARK OF MICHAEL TOBIN',
  'EARMARK OF MICHAEL TOTH',
  'EARMARK OF MICHAEL RACHLIS',
  'EARMARK OF MICHAEL ROCHMAN'],
 ['EARMARK OF DONNA STERNBERG', 'EARMARK OF DONNY ROSENBERG'],
 ['EARMARK OF MURRAY HUPPIN', 'EARMARK OF ERIN MURRAY'],
 ['EARMARK OF SAMUEL REITBERGER',
  'VOID EARMARK OF SAMUEL REITBERGER',
  'EARMARK OF SAMUEL REIDER',
  'EARMARK OF SAMUEL RIEDER'],
 ['EARMARK OF JAKE ARONOV'],
 ['EARMARK OF ADAM ARENS', 'EARMARK OF ADAM AGRON', 'EARMARK OF ADAM COHEN'],
 ['EARMARK OF DANIEL TENENBLATT', 'EARMARK OF ANNA TENENBLATT'],
 ['EARMARK OF SANDOR E SAMUELS',
  'EARMARK OF SANDOR SAMUELS',
  'EARMARK OF SAMUEL SANDLER'],
 ['EARMARK OF SARI AGATSTON'],
 ['EARMARK OF JILL GRANADER'],
 ['EARMARK OF AHRON HERSH',
  'EARMARK OF CAROLYN HERSCH',
  'EARMARK OF AHRON HUEBNER',
  'EARMARK OF AHRON HERRING',
  'EARMARK OF AARON HAMER'],
 ['EARMARK OF RICHARD KRESCH',
  'EARMARK OF RICHARD KIRSCH',
  'VOID EARMARK OF RICHARD KRESCH',
  'EARMARK OF RICHARD KREMEN',
  'EARMARK OF RICHARD KAHN',
  'EARMARK OF RICHARD KASHNOW'],
 ['EARMARK OF DANIEL HEYMAN',
  'EARMARK OF DANIEL HYMAN',
  'EARMARK OF DANIEL FIERMAN',
  'EARMARK OF DANIEL EDELMAN',
  'EARMARK OF DEANNE HEYMANN',
  'EARMARK OF DANIEL KAHAN'],
 ['EARMARK OF JOANNA SILVER',
  'EARMARK OF NORMAN SILVERS',
  'EARMARK OF JOANNE SPIGNER',
  'EARMARK OF JOY SILVERIO',
  'EARMARK OF JOANNE SUDER'],
 ['EARMARK OF JAMES ASHER',
  'EARMARK OF JAMES CHASE',
  'EARMARK OF JAMES BERG',
  'EARMARK OF JAMES COHEN',
  'EARMARK OF JAIME BIRMAHER'],
 ['EARMARK OF HILARY KAPNER', 'EARMARK OF HILARY SMITH KAPNER'],
 ['EARMARK OF MILTON COOPER',
  'EARMARK OF EMILY COOPER',
  'EARMARK OF NEIL COOPER',
  'EARMARK OF MICHAEL COOPER',
  'EARMARK OF ETHAN COOPER'],
 ['EARMARK OF DANIEL STONE',
  'EARMARK OF ANNE STONE',
  'EARMARK OF DANIEL WASSON',
  'EARMARK OF DANIEL POSNER',
  'EARMARK OF DANIEL TURNER',
  'EARMARK OF DANIEL ROSE'],
 ['EARMARK OF ROBERT GOODMAN',
  'EARMARK OF ROBERT GROSSMAN',
  'EARMARK OF ROBERT GORDON',
  'EARMARK OF ROBERT JORDAN',
  'EARMARK OF ROBERT KARGMAN',
  'EARMARK OF ROBERTA LOOMAR'],
 ['EARMARK OF ZOE KIMMELMAN', 'EARMARK OF STEVE KIMMELMAN'],
 ['EARMARK OF KEVIN M JOHNSON M D'],
 ['EARMARK OF ALICIA KUBERSKY'],
 ['EARMARK OF MORT FRIDMAN',
  'EARMARK OF MORTON FRIDMAN',
  'EARMARK OF MORT FRIEDKIN',
  'EARMARK OF MORRIS FRIEDMANN',
  'EARMARK OF MITCH FRIEDMAN',
  'EARMARK OF MOSHE FRIEDMAN'],
 ['EARMARK OF GARY BERMAN',
  'EARMARK OF MARC BERMAN',
  'EARMARK OF GREG BERMAN',
  'VOID EARMARK OF GARY BERMAN',
  'EARMARK OF HARRIS BERMAN',
  'EARMARK OF BERMAN HARRIS'],
 ['EARMARK OF IRA PALGON', 'EARMARK OF IRA WAGNER'],
 ['EARMARK OF JON PINKUS', 'EARMARK OF JONATHAN PINKUS'],
 ['EARMARK OF DAVID RICANATI',
  'EARMARK OF DAVID REIN',
  'EARMARK OF DAVID RAIM',
  'EARMARK OF RYAN DAVID',
  'EARMARK OF DAVID SIMAI',
  'EARMARK OF DAVID RENTZ'],
 ['EARMARK OF ALEX HORN',
  'EARMARK OF ASHLEY HORNE',
  'EARMARK OF ALLAN HORN',
  'EARMARK OF ALEX KOGAN',
  'EARMARK OF DAN HORN',
  'EARMARK OF ALEX GOGGIN'],
 ['EARMARK OF DOUGLAS WEILAND', 'EARMARK OF DOUGLAS WOLL'],
 ['EARMARK OF BARBARA BERGER',
  'EARMARK OF BARRY BERG',
  'EARMARK OF BARBARA BORTNIKER'],
 ['EARMARK OF PAULA ETRA',
  'VOID EARMARK OF PAULA ETRA',
  'EARMARK OF PAULA NORMAN',
  'EARMARK OF PAUL MEISTER',
  'EARMARK OF PAUL LEVITAN',
  'EARMARK OF PAUL MEYER'],
 ['EARMARK OF TERRY BERNARD',
  'EARMARK OF TERRI BORGARD',
  'EARMARK OF BERNARDO STEIN'],
 ['EARMARK OF ROBIN HETTLEMAN'],
 ['EARMARK OF HOWARD WELINSKY', 'EARMARK OF HOWARD PEIN'],
 ['EARMARK OF ANDREW OBIN',
  'EARMARK OF ANDREW EISEN',
  'EARMARK OF ANDREW JACOBSON',
  'EARMARK OF ANDREW LAPPIN',
  'EARMARK OF ANDREW LIPTON',
  'EARMARK OF ANDREW LEVINE'],
 ['EARMARK OF RICK WORNER'],
 ['EARMARK OF RICHARD SCHEINER',
  'EARMARK OF RICHARD SCHIFTER',
  'EARMARK OF RICHARD STEINBERG',
  'EARMARK OF RICHARD SCHIFFRIN',
  'EARMARK OF RICHARD SANDLER',
  'EARMARK OF RICHARD SHARLIN'],
 ['EARMARK OF BENJAMIN GENET',
  'EARMARK OF BENJAMIN GERBER',
  'EARMARK OF BEN GENET',
  'EARMARK OF BENJAMIN KLEIN',
  'EARMARK OF BENJAMIN FRIEND',
  'EARMARK OF BENJAMIN GORDON'],
 ['EARMARK OF BURT LEVINE', 'EARMARK OF BARRY LEVIN'],
 ['EARMARK OF JOHANNA CHANIN',
  'VOID EARMARK OF JOHANNA CHANIN',
  'EARMARK OF JOHN CHAVIS'],
 ['EARMARK OF SAM JACOB',
  'EARMARK OF SHIRA JACOBS',
  'EARMARK OF ZALMIE JACOBS',
  'EARMARK OF JACOB SHAPIRO',
  'EARMARK OF JACOB SLONE'],
 ['EARMARK OF GEORGE ROHR', 'EARMARK OF GEORGE SOLICH'],
 ['EARMARK OF BRAD MINDLIN'],
 ['EARMARK OF NEIL COHEN',
  'EARMARK OF JOEL COHEN',
  'EARMARK OF KEITH COHEN',
  'EARMARK OF ERIKA COHEN',
  'EARMARK OF LEE COHEN',
  'EARMARK OF HILLEL COHEN'],
 ['EARMARK OF JOHN ISENBERG', 'EARMARK OF JAY EISENBERG'],
 ['EARMARK OF KARIN FREEDMAN',
  'EARMARK OF KATHERINE FREEDMAN',
  'EARMARK OF MARCINE FRIEDMAN',
  'EARMARK OF MYRNA FREEDMAN',
  'EARMARK OF KRISTI FREEMAN',
  'EARMARK OF LAURIE FRIEDMAN'],
 ['EARMARK OF SUSAN SAMRICK', 'EARMARK OF SUSAN SACKS'],
 ['EARMARK OF JOSHUA NEWMAN',
  'EARMARK OF JOSHUA NEUMAN',
  'EARMARK OF JOSH NEUMAN',
  'EARMARK OF JON NEWMAN',
  'EARMARK OF J NEWMAN',
  'EARMARK OF JOSHUA MALKIN'],
 ['EARMARK OF MICHAEL KASSEN',
  'EARMARK OF MICHAEL KOSS',
  'EARMARK OF KALEN MICHEL',
  'EARMARK OF MICHAEL KRASNER',
  'EARMARK OF MICHAEL KUEHN',
  'EARMARK OF MICHAEL KANEF'],
 ['EARMARK OF STEPHEN OPPENHEIMER'],
 ['EARMARK OF GREGORY SHRON',
  'EARMARK OF GREGORY SCHULSON',
  'EARMARK OF GREGORY RUTH',
  'EARMARK OF GREGORY WOLF'],
 ['EARMARK OF HERB SHEAR',
  'EARMARK OF HERBERT SHEAR',
  'EARMARK OF SEAN MAHER',
  'EARMARK OF HENRY SERY'],
 ['EARMARK OF ANDREW SUSSMAN',
  'EARMARK OF ANDREW SOSSIN',
  'EARMARK OF ANDREW SMALL',
  'EARMARK OF ANDREW SULLIVAN',
  'EARMARK OF ANDREW YOUNGMAN',
  'EARMARK OF ANDREW PESSIN'],
 ['EARMARK OF MANNY PANAR',
  'VOID EARMARK OF MANNY PANAR',
  'EARMARK OF MANUEL PANAR'],
 ['EARMARK OF MARVIN DAVIS',
  'EARMARK OF DAVID MARTIN',
  'EARMARK OF MAIA DAVIS',
  'EARMARK OF MARK DAVIS',
  'EARMARK OF MARVIN DENNIS',
  'EARMARK OF KAREN DAVIS'],
 ['EARMARK OF ARI RYAN',
  'EARMARK OF CARRIE RYAN',
  'EARMARK OF CHRIS RYAN',
  'EARMARK OF CARA RANO',
  'EARMARK OF RYAN BERK',
  'EARMARK OF ARI RESNIK'],
 ['EARMARK OF RICK ZITELMAN', 'EARMARK OF P R ZITELMAN'],
 ['EARMARK OF PHILIP COHEN',
  'EARMARK OF PHILLIP COHEN',
  'EARMARK OF PHILIP H COHEN',
  'EARMARK OF PHIL COHEN',
  'EARMARK OF PHYLLIS COHEN'],
 ['EARMARK OF JONE DALEZMAN',
  'EARMARK OF JOEL ALTMAN',
  'EARMARK OF JOE ACKERMAN',
  'EARMARK OF AMANDA JONES',
  'EARMARK OF JOYCE DEMAIN'],
 ['VOID REFUNDED EARMARK OF SHIRLEY COOPER'],
 ['EARMARK OF REBECCA NISSEL', 'EARMARK OF REBECCA NIES'],
 ['EARMARK OF FERNANDO SZEW',
  'EARMARK OF FER SZEW',
  'EARMARK OF FERNANDO VELA',
  'EARMARK OF FERNANDO VASQUEZ'],
 ['EARMARK OF SUSAN L BENDER',
  'EARMARK OF SUSAN BENDER',
  'EARMARK OF SUSIE BENDER',
  'EARMARK OF SUSAN ALEXANDER'],
 ['EARMARK OF MORRIS TUCHMAN',
  'VOID EARMARK OF MORRIS TUCHMAN',
  'EARMARK OF MORRIS WERTHAN',
  'EARMARK OF ERIC TUCHMAN',
  'EARMARK OF MORRIS TABUSH'],
 ['EARMARK OF FRANCINE COLES', 'EARMARK OF FRANCINE CASE'],
 ['EARMARK OF JACQUELINE MUSS', 'EARMARK OF JACQUELINE OCHS'],
 ['EARMARK OF LISA ENGEL',
  'VOID EARMARK OF LISA ENGEL',
  'EARMARK OF LISA FIELD',

In [ ]:
# Fill all remaining unclassified categories as other
spending_data['exp_cat']=spending_data['exp_cat'].fillna('other').str.upper()

## Aggregate the spending data for use in the Network visualization

In [ ]:
spending_data_agg = (
    spending_data
    .groupby(['filer_committee_id_number', 'vendor_full','exp_cat'])
    # calculate the total amount spent by a PAC on a vendor and the # of payments
    .agg(
        ttl_spend=('expenditure_amount', 'sum'),
        n_transactions=('vendor', 'size')
    )
    .reset_index()
)

# merge with pac qualitative data to get info like cmte_type and cmte_designation
spending_data_agg = spending_data_agg.merge(pacs, left_on ='filer_committee_id_number',right_on = 'committee_id', how = 'left')

spending_data_agg.head()

### Add Independent expenditure data to spending_data_add

In [ ]:
# load SE data
se = pd.read_csv('../data/raw/SE_dataset.csv')

#se.head()

# Apply same string cleaning as above
se = normalize_string_columns(se) 

#se.isna().sum()

#se[(se['candidate_id_number'].isna())].filter(['candidate_last_name','candidate_first_name']).drop_duplicates().sort_values('candidate_last_name')

# aggregate SE data 
se_data_agg = (
    se
    .groupby(['filer_committee_id_number'])
    .agg(
        ttl_spend=('expenditure_amount', 'sum'),
        n_transactions = ('filer_committee_id_number','size')
    )
    .reset_index()
)

# merge in pac information to have similar columns
se_data_agg = se_data_agg.merge(pacs, left_on ='filer_committee_id_number',right_on = 'committee_id', how = 'left')
se_data_agg['vendor_full'] = 'INDEPENDENT EXPENDITURE'
se_data_agg['exp_cat'] = 'Independent Expenditure'

se_data_agg.head()

In [ ]:
# make sure columns are the same for binding the data together
print(len(spending_data_agg.columns))
print(len(se_data_agg.columns))

In [ ]:
# Bind SE data with SB data 
spending_data_agg = pd.concat([spending_data_agg,se_data_agg], ignore_index= True)

spending_data_agg.exp_cat.unique()

### Define calculated columns to use in filters

In [ ]:
#Define calculated columns 

# pct_indiv: the percent of a PACs receipts that come from individuals
spending_data_agg['pct_indiv'] = spending_data_agg['individual_contributions']/spending_data_agg['receipts']

# pct_unitem: the percent of a PACs receipts that come from unitemized individuals
spending_data_agg['pct_unitem'] = spending_data_agg['individual_unitemized_contributions']/spending_data_agg['receipts']

# n_unique_filers: the number of filers that paid a given vendor
spending_data_agg['n_unique_filers'] = (
    spending_data_agg.groupby('vendor_full')['filer_committee_id_number']
    .transform('nunique')
)

# n_unique_vendors: the number of vendors that a given filer used 
spending_data_agg['n_unique_vendors'] = (
    spending_data_agg.groupby('filer_committee_id_number')['vendor_full']
    .transform('nunique')
)

union_pattern = r'FEDERATION|UNION|LOCAL (?:#|NO\.)?\s?\d+|ASSOC.?\w+? OF|SEIU|IBEW|UAW|TEAMSTERS|BROTHERHOOD OF|UNITED \w+ WORKERS OF|AFSCME|VOLUNTARY POLITICAL COMMITTEE'

spending_data_agg['is_union_pac'] = np.where( spending_data_agg.organization_type_full.isin(['Labor Organization','Trade Association','Membership Organization','Cooperative']), True, 
                              np.where( (spending_data_agg.organization_type_full.isna() & spending_data_agg.committee_name.str.contains(union_pattern,regex=True)),True, False))

spending_data_agg['pct_ttl_spend'] = np.where(
    spending_data_agg['ttl_spend'] > 0,
    100*(spending_data_agg['ttl_spend']/spending_data_agg['disbursements']),
    0.01        
)

### Export final dataset

In [ ]:

spending_data_agg.to_csv("../data/processed/pac_vendor_agg.csv", index=False)

## Earlier Work

All of the work below represents attempts at other text mining / clustering methods. Ultimately, given my high aversion to mis attributing expenditures, I decided to not use more common text clustering methods in favor of the rapidfuzz and regex text cleaning.

To start, I decided to try HDBSCAN because I didn't want to set the number of clusters, and the max_cluster_size parameter was a helpful tool for this work. I would not expect many clusters should have more than 5 values, because we are mostly looking to do text cleaning. 

Ultimately, some of the clusters look great, some are complicated by candidates with similar names running in different states or candidate names and staff or consultant names being similar, others are way off. Also, an issue I ran into with more simple text mining for text cleaning, since naming conventions for campaigns and committee names are so ubiquitous, like Citizens For, Committee to Elect, Friends of, many unrelated campaigns get added together.

For future iterations I could try calculating the average silouhette score for each cluster, and see if clusters with scores above a certain threshold could be used for string cleaning.

In [50]:

from sklearn.cluster import HDBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import silhouette_score

to_cat = spending_data[(spending_data['form_type'].isin(['SB22','SB23','SB29'])) & (spending_data['vendor'].isna())].payee_id.unique().tolist()

tfidf_vect = TfidfVectorizer(max_df=5000, stop_words='english')
tfidf = tfidf_vect.fit_transform(to_cat)
tfidf.shape

(35235, 19232)

In [51]:

hdb = HDBSCAN(max_cluster_size = 5)

labels = hdb.fit_predict(tfidf)

In [52]:
# create df to examine clusters
data_res = pd.DataFrame({'text': to_cat, 'cluster':labels})

# exclude unclustered data 
data_res[data_res['cluster']!=-1].sort_values(by = 'cluster')

                                                    text  cluster
12477                                        HOULE LACEY        0
12476                                    TRUJILLO ALISSA        0
12475                                    BOURGEOIS CHLOE        0
12474                                    ABUHAIKAL BARAA        0
12480                                       HERDER SUSAN        0
12527                                    HIXSON JENNIFER        1
12528                                    HAEUSSLER DEREK        1
12529                             JOHNSTON GUZMAN ALYSSA        1
12530                                     BEUKER KAITLYN        1
12537                                   SHEPPARD DESTINY        1
12571                                      VENTURA ISAAC        2
12570                                     BELFONT JAZNIE        2
12573                                     HUBLER KELSTON        2
12582                                        KELLY CONOR        2
12572                                      KERSHAW JARED        2
20347                                      RIO LAS VEGAS        3
10016                      THE COSMOPOLITAN OF LAS VEGAS        3
21562                                 PARK MGM LAS VEGAS        3
10015                             COSMOPOLITAN LAS VEGAS        3
22279                                  PROTECT LAS VEGAS        3
129                   ANGUS KING FOR U S SENATE CAMPAIGN        4
13536                          ANGUS KING FOR U S SENATE        4
8098                      ANGUS KING FOR SENATE CAMPAIGN        4
15654                              ANGUS KING FOR SENATE        4
5980                       ANGUS KING FOR U S SENATE CAM        4
25571                                   THE BONNER GROUP        5
34695                             BONNER FOR STATE HOUSE        5
2124                                          THE BONNER        5
3995                                              BONNER        5
17727                                       BONNER JAMES        5
12159                     TERESA PROANO FOR CITY COUNCIL        6
12164                    SAN GABRIEL VALLEY VICTORY FUND        6
12182                  CAMPAIGN TO ELECT ROCHELLE NGUYEN        6
12170  COMMFORSTRONGERSAFER NEIGHBORHOODS SUP JANICE ...        6
12177            SAVE OUR POMONA PUBLIC LIBRARY ADVOCACY        6
14128                   ELECTION FUND OF JOSEPH F VITALE        7
13037                             EFO OF JOSEPH F VITALE        7
11030             ELECTION FUND OF SENATOR JOSEPH VITALE        7
24539                                  EFO JOSEPH VITALE        7
17020                          EFO SENATOR JOSEPH VITALE        7
10039                              CHANGE BEGINS WITH ME        8
10035                                  ROCA FOR CONGRESS        8
10051                                   TOLSON CLAUDETTE        8
10046                                  SIGNS BY TOMORROW        8
10043                                       LATHAM NANCY        8
3162                                 SABI KUMAR CAMPAIGN        9
29744                    COMMITTEE TO REELECT SABI KUMAR        9
4395                             SABI KUMAR FOR TN HOUSE        9
29059                  FRIENDS TO RE ELECT DR SABI KUMAR        9
7944                 SABI KUMAR FOR STATE REPRESENTATIVE        9
8393                                   GANNON FOR SENATE       10
27747                    GANNON FOR STATE REPRESENTATIVE       10
31166                       BILL GANNON FOR STATE SENATE       10
16465                CAMPAIGN COMMITTEE FOR LAURA GANNON       10
24591                                 GANNON FOR SHERIFF       10
24254                           JUSTIN GERHARDT CAMPAIGN       11
31235                                    GERHARDT JUSTIN       11
17215                                GERHARDT FOR SENATE       11
9846                                     GERHARDT FOR ND       11
16979                      JUSTIN GERHARDT FOR ND SENATE       11
11211  RE ELECT JENNA GUZMAN LOWERY FOR REDLANDS CITY...       12
11360                                 DC TAX AND REVENUE       12
11282                       MIKE NAIG FOR IA AGRICULTURE       12
10719                                 CNS EVENT PARTNERS       12
9955                         COMITE AMIGOS JOHNNY MENDEZ       12
359                                        BREAUX FOR IN       13
18648                HARLAN BREAUX FOR AR HOUSE DISTRICT       13
30895                   HARLAN BREAUX CAMPAIGN COMMITTEE       13
26176                        HARLAN BREAUX FOR STATE REP       13
34211             HARLAN BREAUX FOR STATE REPRESENTATIVE       13
27347              BARNALI GHOSH FOR BART BOARD DISTRICT       14
27058                      FRIENDS OF KATHIE HESS CROUSE       14
26704  NY ST CONF OF THE INT L UNION OF OPERATING ENG...       14
26944                                   BLUE LOTUS FILMS       14
27742                                    ELECT RICK JUST       14
28087                                         LEE EUN JU       15
28387              ELECT FRANK BURNS CHANGE FOR THE 21ST       15
28381                          MCKESSON MEDICAL SURGICAL       15
28496  WALTER BJ DEMPSEY FOR COCONINO COUNTY BOARD OF...       15
28324                          LYNN FITCH FOR MISSISSIPP       15
13169                                      GUEST MICHAEL       16
20246                          VAL GUEST FOR STATE HOUSE       16
16729                             VAL GUEST FOR SC HOUSE       16
236                             FRIENDS OF MICHAEL GUEST       16
12859                                              GUEST       16
26791                                   ORR FOR TX HOUSE       17
10144                                        ORR ANGELIA       17
27287                                 ANGELIA ORR FOR TX       17
4525                                ANGELIA ORR CAMPAIGN       17
18702                                          ORR KEVIN       17
4528                     CHRISTIAN MANUEL HAYES CAMPAIGN       18
4530                               CITIZENS FOR AMY ELIK       18
4531                        CITIZENS FOR C D DAVIDSMEYER       18
4532                            CITIZENS FOR FRED CRESPO       18
4537                            CITIZENS FOR MIKE COFFEY       18
804                         ROBERT ADERHOLT FOR CONGRESS       19
17559                              ADERHOLT ROBERT BROWN       19
33777                                    ADERHOLT ROBERT       19
5388                               ADERHOLT ROBERT B REP       19
1153                               ADERHOLT FOR CONGRESS       19
23223                                 SENATOR JOHN THUNE       20
15984                            THUNE VICTORY COMMITTEE       20
17160                                       THUNE JOHN R       20
34672                              JOHN THUNE FOR SENATE       20
311                                           THUNE JOHN       20
32045                 THE COMMITTEE TO ELECT BILL ROEMER       21
33115                          COMMITTEE TO ELECT ROEMER       21
4029                                         ROEMER BILL       21
1836                      COMMITTEE TO ELECT BILL ROEMER       21
21285                          CMTE TO ELECT BILL ROEMER       21
34486                          PI KAPPA ALPHA FRATERNITY       22
30226                    DECATUR ALUMI ALPHA KAPPA ALPHA       22
30223                           AAC OF ALPHA KAPPA ALPHA       22
28780                                    KAPPA ALPHA PSI       22
34484                                  KAPPA ALPHA ORDER       22
16300                              CLYBORNE FOR CONGRESS       23
16295                                      NY STATE DACC       23
16285                               HEARTLAND VALUES PAC       23
16309                            JIM MCGREEVEY FOR MAYOR       23
16294                                  KEVIN VOLK FOR AZ       23
1932                 SANDRE SWANSON FOR STATE SENATE  ID       24
1930                      NATIONAL ASSOCIATION OF MANUFA       24
1927                              FRIENDS OF SCOTT LIPPS       24
1918   FOOD MARKETPLACE INC POLITICAL ACTION COMMITTE...       24
1917                 51ST MAYORAL INAUGURATION COMMITTEE       24
18807                             GEREMY LANDIN CAMPAIGN       25
18818                                       350NH ACTION       25
18786                           FRIENDS OF CHRIS REYKDAL       25
18801                      ALEX MOHAJER FOR STATE SENATE       25
18808  MICHAEL COOK FOR PLANO ISD SCHOOL BOARD TRUSTE...       25
24101                                   VIZKID ANALYTICS       26
24091             COMMITTEE TO RE ELECT DIGIROLAMO MAYOR       26
24094                LAMONT MCCLURE FOR COUNTY EXECUTIVE       26
24090             CENTRAL PA BUILDING CONSTRUCTION TRADE       26
24098                                STEVE TOTH CAMPAIGN       26
23274                                         JAVIER FOR       27
13252                             JAVIER MARTINEZ FOR NM       27
2850                  COMMITTEE TO ELECT JAVIER MARTINEZ       27
19199         CMTE TO ELECT JAVIER MARTINEZ FOR NM HOUSE       27
32115                      CMTE TO ELECT JAVIER MARTINEZ       27
10647                           FRIENDS OF DONNA BULLOCK       28
9540                             FRIENDS OF JOHN BULLOCK       28
19338                                      BULLOCK JAMES       28
30182                              MONTANANS FOR BULLOCK       28
19570                                    BULLOCK MICHAEL       28
34831                                       TOLE MICHAEL       29
34853                                     CAMILLE FOR ID       29
34837                                     VAN HULST ERIC       29
34852                   BRANDON SHIPPY FOR STATE SENATOR       29
34846                                 ZAHRADNICK MICHAEL       29
27407                                        MAGIE STEVE       30
28450                       REPRESENTATIVE STEPHEN MAGIE       30
30896                     STEVE MAGIE CAMPAIGN COMMITTEE       30
22999                     STEVE MAGIE FOR REPRESENTATIVE       30
29680                        STEPHEN MAGIE CAMPAIGN CMTE       30
33695                                 NIKOLAKAKOS FOR HD       31
33950                                 NIKOLAKAKOS GEORGE       31
13428                          GEORGE NIKOLAKAKOS FOR HD       31
25901                 GEORGE NIKOLAKAKOS FOR STATE HOUSE       31
16713                  GEORGE NIKOLAKAKOS HOUSE DISTRICT       31
28257                    ADRIN NAZARIAN FOR CITY COUNCIL       32
19607                              ADRIN NAZARIAN FOR CC       32
34038  WORKING FAMILIES IN SUPPORT OF ADRIN NAZARIAN ...       32
34062                          NAZARIAN FOR CITY COUNCIL       32
22109           NAZARIAN FOR CITY COUNCIL  GENERAL ADRIN       32
34093                     AMERICANS FOR FINANCIAL REFORM       33
34103                       GAY AND LESBIAN FUND FEDERAL       33
34110          LEE CHATFIELD FOR STATE REPRESENTATIVE MI       33
34083                       FXK YO RECALLS OF THAO PRICE       33
34081                    CLAUDIA JIMENEZ FOR RICHMOND CC       33
24474                              CONSOLIDATED PRINTING       34
24475    CREDIT UNION LEGISLATIVE ACTION COUNCIL OF CUNA       34
24465  COMMITTEE TO ELECT ANA VALDEMOROS SLC COUNCIL UT4       34
24478                NORMAN SANDERSON CAMPAIGN COMMITTEE       34
24481                     BRIAN IGNATOWSKI FOR STATE REP       34
24212           AMERICANS FOR CONTRACEPTION VICTORY FUND       35
24214                                     VIBRANT AUSTIN       35
24216                            FRED DURHAL FOR DETROIT       35
24222                       MICHAEL BRANDENBURG CAMPAIGN       35
24210                                    MATTES NICHOLAS       35
26810     COMMITTEE TO ELECT BARBARA KIRKMEYER TO SENATE       36
27916                                      KIRKMEYER FOR       36
20889                             KIRKMEYER FOR CONGRESS       36
2706   COMMITTEE TO ELECT BARBARA KIRKMEYER TO STATE ...       36
13504                         KIRKMEYER FOR STATE SENATE       36
14989                                OHAEBOSIM FOR HOUSE       37
22536                                KC OHAEBOSIM FOR KS       37
15153                          KC OHAEBOSIM FOR KS HOUSE       37
23668                    COMMITTEE TO ELECT KC OHAEBOSIM       37
32345                            OHAEBOSIM FOR THE HOUSE       37
16977                                  ERBELE FOR SENATE       38
6843                             ERBELE FOR STATE SENATE       38
24221                             ROBERT ERBELE CAMPAIGN       38
31231                                      ERBELE ROBERT       38
17187                                  BOB ERBELE FOR ND       38
18814                     BEATY FOR STATE REPRESENTATIVE       39
28330                             BEATY FOR SCHOOL BOARD       39
9600               HOWARD BEATY FOR STATE REPRESENTATIVE       39
34680                             FRIENDS OF LACEY BEATY       39
31647                              HOWARD BEATY CAMPAIGN       39
1812                            PAT PETTEY FOR KS SENATE       40
31117                                  PAT PETTEY FOR KS       40
7401                                PETTEY FOR KS SENATE       40
23671                      COMMITTEE TO ELECT PAT PETTEY       40
389                                           PETTEY PAT       40
18151                       INSURED RETIREMENT INSTITUTE       41
27515               INSURED RETIREMENT INSTITUTE PAC IRI       41
3047   INSURED RETIREMENT INSTITUTE POLITICAL ACTION ...       41
26032           INSURED RETIREMENT INSTITUTE PAC IRI PAC       41
23727  INSURED RETIREMENT INSTITUTE POLITICAL ACTION ...       41
11181                 REPUBLICAN PARTY OF OZAUKEE COUNTY       42
10700                  EDGEFIELD COUNTY REPUBLICAN PARTY       42
10397                   BEAUFORT COUNTY REPUBLICAN PARTY       42
14961                     TOOELE COUNTY REPUBLICAN PARTY       42
10398           REPUBLICAN PARTY OF POTTAWATTAMIE COUNTY       42
15136                          JOHN CARMICHAEL FOR HOUSE       43
28140                       JOHN CARMICHAEL FOR KS HOUSE       43
22516                            CARMICHAEL FOR KS HOUSE       43
14978           JOHN CARMICHAEL FOR STATE REPRESENTATIVE       43
23651                                  CARMICHAEL FOR KS       43
4291                           ERIC SAM HARLESS CAMPAIGN       44
8058                                SAM HARLESS CAMPAIGN       44
7206                      SAM HARLESS CAMPAIGN COMMITTEE       44
10076                         HARLESS CAMPAIGN COMMITTEE       44
16343                         COMMITTEE TO ELECT HARLESS       44
7823                                  DOYLE FOR ASSEMBLY       45
28600                                        DOYLE BRIAN       45
12563                                     DOYLE BENJAMIN       45
11793                                      DOYLE MATTHEW       45
6132                              FRIENDS OF STEVE DOYLE       45
13850                                      HELTON FOR WV       46
29094                                ESTHER FOR CONGRESS       46
7937                              HELTON FOR STATE HOUSE       46
5925                    COMMITTEE TO ELECT ESTHER HELTON       46
23387               THE COMMITTEE TO ELECT ESTHER HELTON       46
34559                   THE COMMITTEE TO ELECT RYAN WELD       47
6055                                RYAN WELD FOR SENATE       47
8495                     COMMITTEE TO RE ELECT RYAN WELD       47
6820                        COMMITTEE TO ELECT RYAN WELD       47
24189                                    WELD FOR SENATE       47
13632                         TARA NETHERCOTT FOR SENATE       48
13284                 COMMITTEE TO ELECT TARA NETHERCOTT       48
31388                              NETHERCOTT FOR SENATE       48
18173                   FRIENDS TO ELECT TARA NETHERCOTT       48
17481                                    NETHERCOTT TARA       48
29712    BRANDON ARRINGTON FOR OSCEOLA COUNTY COMMISSION       49
26729                         BRANDON ARRINGTON CAMPAIGN       49
5452                          KRISTEN ARRINGTON CAMPAIGN       49
21978                        ARRINGTON VICTORY COMMITTEE       49
3553                      THE BRANDON ARRINGTON CAMPAIGN       49
2098                         MD STATE BOARD OF ELECTIONS       50
16297                        NC STATE BOARD OF ELECTIONS       50
11811                        VA STATE BOARD OF ELECTIONS       50
5630                            STATE BOARD OF ELECTIONS       50
12056                 VIRIGINIA STATE BOARD OF ELECTIONS       50
33941                                     BREWSTER LARRY       51
13729                    COMMITTEE TO ELECT JIM BREWSTER       51
13429                              LARRY BREWSTER FOR HD       51
16720                  LARRY BREWSTER FOR HOUSE DISTRICT       51
16958                     LARRY BREWSTER FOR STATE HOUSE       51
23978          CAMPAIGN COMMITTEE TO ELECT MARY CAVANAGH       52
12108                                ELECT MARY CAVANAGH       52
7891                                       MARY CAVANAGH       52
2421                    COMMITTEE TO ELECT MARY CAVANAGH       52
3059                                   CTE MARY CAVANAGH       52
11065                                 FLORA FOR ASSEMBLY       53
6356                            HEATH FLORA FOR ASSEMBLY       53
22244                     HEATH FLORA FOR STATE ASSEMBLY       53
25874                             FLORA FOR ASSEMBLY  ID       53
22625                       HEATH FLORA FOR ASSEMBLY  ID       53
16999                         BERNIE SATROM FOR ND HOUSE       54
9825                    COMMITTEE TO ELECT BERNIE SATROM       54
10168                                             BERNIE       54
31267                                      SATROM BERNIE       54
17227              RE ELECT REPRESENTATIVE BERNIE SATROM       54
15627                     COMMITTEE TO ELECT JEFF ZENGER       55
16685        COMMITTEE TO ELECT JEFF ZENGER FOR NC HOUSE       55
12100   COMMITTEE TO ELECT JEFF ZENGER TO NC STATE HOUSE       55
33066         COMMITTEE TO ELECT ZEFF ZENGER TO NC HOUSE       55
3512          COMMITTEE TO ELECT JEFF ZENGER TO NC HOUSE       55
24752              DON BURKHART FOR STATE REPRESENTATIVE       56
25561                                 BURKHART FOR HOUSE       56
1250                     DONALD BURKHART FOR STATE HOUSE       56
33256            FRIENDS OF REPRESENTATIVE JEFF BURKHART       56
2023                    COMMITTEE TO ELECT JEFF BURKHART       56
22430                              REYES FOR ASSEMBLY ID       57
13051                                   REYES FOR SENATE       57
31820                                 REYES FOR ASSEMBLY       57
31924                                        REYES JAMES       57
15697                              FRIENDS OF SEAN REYES       57
13437                          DAVID YATES FOR KY SENATE       58
21166                      DAVID YATES FOR STATE SENATOR       58
3625                        DAVID YATES FOR STATE SENATE       58
22561                             YATES FOR STATE SENATE       58
5267                                         YATES LINDA       58
10931                                     ADKINS MICHAEL       59
33441                            FRIENDS OF MARIE ADKINS       59
22856                                      ADKINS FOR KS       59
506                                   MARIE FOR CONGRESS       59
31937                                    WOODSON MARIE P       59
20480                                         HARMON DON       60
4545                               FRIENDS OF DON HARMON       60

### Classic clustering method 2: Agglomerative Clustering

I also tried Hierarchical Clustering. My theory here was that this methodology would be well suited to string cleaning because you could try to group strings by looking at the impact of changing one additional letter on the clusters and choosing the level that gets you closest to what you want.

In [ ]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import pairwise_distances

# Pre calculate pairwise distance using already built tfidf matrix
dist_matrix = pairwise_distances(tfidf, metric='cosine')

# Initiate Agglomerative Clustering using the precomputed metric 
hierac_clustering = AgglomerativeClustering(
    n_clusters=None 
    , metric='precomputed' 
    , linkage='average'
    , distance_threshold=0.4
)

# Fit model
hierac_labels = hierac_clustering.fit_predict(dist_matrix) 

# Create DF to view results
data_res_hier = pd.DataFrame({'text': to_cat, 'cluster':hierac_labels})
data_res_hier.sort_values(by = 'cluster')